<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>vimrc</string>
		<string>pentadactylrc</string>
		<string>vimperatorrc</string>
		<string>vimpcrc</string>
	</array>
	<key>name</key>
	<string>Vim-like Dotfiles</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>comment</key>
			<string>comments</string>
			<key>contentName</key>
			<string>comment.line</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.vimlikedotfiles</string>
	<key>uuid</key>
	<string>f5c1f79f-0481-40d2-9b21-74db3d61e14c</string>
</dict>
</plist>
