[theme]
primary = "light white"
secondary = "light black"
title = "green"
playing = "green"
playing_bg = "black"
highlight = "light white"
highlight_bg = "#484848"
error = "light white"
error_bg = "red"
statusbar = "black"
statusbar_progress = "green"
statusbar_bg = "green"
cmdline = "light white"
cmdline_bg = "black"

[keybindings]
" " = "toggleplay"
"Backspace" = "stop"
"Ctrl+d" = "quit"
"o" = "next"
"O" = "previous"
"<" = "seek -500"
">" = "seek +500"
# "Alt+j" = "move down 10"
# "Alt+k" = "move up 10"
