" Author: Philipp Moers <soziflip@gmail.com>
" A gvimrc for GUI only stuff


" hide toolbar
set guioptions-=T

" hide menubar
set guioptions-=m

" hide tabbar
set guioptions-=e

" hide scrollbars
set guioptions-=r
set guioptions-=R
set guioptions-=l
set guioptions-=L
set guioptions-=b

" font
" set guifont=Monospace
set guifont=Monospace\ 14

" FIX colors
colorscheme badwolf


