#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from i3pystatus import Status


# The i3pystatus process can be notified about updates with
#       pkill -USR1 -f 'i3pystatus'"



status = Status(standalone=True)


# Colors
COLOR_DEFAULT = "#DDDDDD";
#  COLOR_GREEN   = "#AABF9B";
COLOR_GREEN   = "#009C9C";
COLOR_RED     = "#F2935C";


# Displays clock like this:
# Tue 30 Jul 11:59:46 PM KW31
#                          ^-- calendar week
status.register("clock",
    format = " %a %d.%m.%Y  %H:%M:%S  ",
    on_leftclick = "xfce4-display-settings",
    on_rightclick = "xfce4-settings-manager",
    on_middleclick = "sudo poweroff",
)

# Shows the average load of the last minute and the last 5 minutes
# (the default value for format is used)
# status.register("load")



# Displays whether a DHCP client is running
# status.register("runwatch",
#     name = "DHCP",
#     path = "/var/run/dhclient*.pid",)

# Shows the address and up/down state of eth0. If it is up the address is shown in
# green (the default value of color_up) and the CIDR-address is shown
# (i.e. 10.10.10.42/24).
# If it's down just the interface name (eth0) will be displayed in red
# (defaults of format_down and color_down)
#
# Note: the network module requires PyPI package netifaces
# status.register("network",
#     interface = "eth0",
#     format_up = "{v4cidr}",)


# find out wlan interface name
from netifaces import interfaces
ifaces = interfaces()
for iface in ifaces:
    if (iface.startswith('wlp') or iface.startswith('wlan')):
        wlan_interface = iface

# Note: requires both netifaces and basiciw (for essid and quality)
status.register("network",
    interface = wlan_interface,
    # hints = { "markup" : "pango" },
    dynamic_color = False,
    # format_up = " <span color=\"#199C25\">{essid}</span> {quality:03.0f}% ",
    format_up = " {essid} {v4} {quality:02.0f}%",
    format_down = "WiFi down",
    # color_up = COLOR_GREEN,
    color_up = COLOR_DEFAULT,
    color_down = COLOR_RED,
    #  upper_limit = 800.0,
    interval = 4,
)

# Shows disk usage of /
status.register("disk",
   path = "/home/",
   #  format = "{used}/{total}G [{avail}G]",
   on_leftclick = "thunar",
   format = " {avail}G",
   interval = 9,
)
status.register("disk",
   path = "/",
   format = " DISK: {avail}G",
   on_leftclick = "thunar",
   interval = 9,
   hints = { "separator" : False, "separator_block_width": 0} ,
)

# Show memory usage
status.register("mem",
    format = "MEM: {percent_used_mem}%",
    warn_percentage = 50,
    alert_percentage = 70,
    color = COLOR_DEFAULT,
    warn_color = COLOR_RED,
    alert_color = "#FF0000",
    on_leftclick = "xfce4-terminal --execute htop",
    interval = 9,
    hints = { "separator" : False, "separator_block_width": 0} ,
)


# Shows your CPU temperature, if you have a Intel CPU
status.register("temp",
    format = "{temp:.0f}°C ",
    on_leftclick = "xfce4-terminal --execute htop",
    hints = { "separator" : False, "separator_block_width": 0} ,
)

# Shows CPU usage
status.register("cpu_usage",
    format = " CPU: {usage}% ",
    on_leftclick = "xfce4-terminal --execute htop",
    hints = { "separator" : False, "separator_block_width": 0} ,
)


# some random jokes and shit
# status.register("shell",
#     command = "fortune",
#     interval = 20,
# )


# wheather
# status.register("weather",
#     format = " TEMP: {current_temp} ",
#     location_code = "GMXX1002:1:GM",
# )


# Shows pulseaudio default sink volume
#
# Note: requires libpulseaudio from PyPI
status.register("pulseaudio",
    format = "  {volume}",
    on_leftclick     = "pavucontrol",
    on_upscroll     = "amixer sset Master 1%+; pkill -USR1 -x -f '^python.? /home/.*/\.i3/i3pystatus$'",
    on_downscroll   = "amixer sset Master 1%-; pkill -USR1 -x -f '^python.? /home/.*/\.i3/i3pystatus$'",
)

# Shows mpd status
# Format:
# Cloud connected▶Reroute to Remain
# status.register("mpd",
#     format = " {status} {artist} - {title} ",
#     status = {
#         "pause": "▷",
#         "play": "▶",
#         "stop": "◾",
#     },
#     on_leftclick = "ario"
#     ,)
status.register("shell",

    # UNIX commands and pipes ftw...

    # (the following command works in sh...)
    # command = "pgrep --exact mpd > /dev/null && mpc status | sed '2d' | sed 's/repeat: .*//' | tr '\n' '-' | sed 's/-volume: \(.*\)%.*/ - VOLUME: \1/' | sed 's/\(.*\)/\U\1/g'|| true",
    # (...but the backslash sequences in sed must be escaped 
    #  so python does not interpret them)
    command = """pgrep --exact 'mpd|mopidy' > /dev/null && 
                    mpc status | 
                    sed '2d' | 
                    sed 's/repeat: .*//' | 
                    tr '\\n' '-' | 
                    sed 's/-volume: \\(.*\\)%.*/ | \\1 /' || true""",

    # note: the shell.py script does throw errors on empty strings. i hacked
    #       it to accept them, so that there is nothing displayed without mpd.

    hints = { "separator" : False, "separator_block_width": 0} ,
    interval = 120, # we will be notified by ./i3pystatus-mpd-notification.sh
    on_leftclick    = "mpc next; pkill -USR1 -x -f '^python.? /home/.*/\.i3/i3pystatus$'",
    on_rightclick   = "mpc prev; pkill -USR1 -x -f '^python.? /home/.*/\.i3/i3pystatus$'",
    on_upscroll     = "mpc volume +1; pkill -USR1 -x -f '^python.? /home/.*/\.i3/i3pystatus$'",
    on_downscroll   = "mpc volume -1; pkill -USR1 -x -f '^python.? /home/.*/\.i3/i3pystatus$'",
)


status.run()
