# joshuto config

numbered_command = false

mouse_support = true
focus_on_create = true
use_trash = true
watch_files = true
xdg_open = false
xdg_open_fork = false
case_insensitive_ext = false
zoxide_update = false

custom_commands = []

[display]
mode = "minimal" # minimal, default, hsplit

automatically_count_files = true
collapse_preview = false
column_ratio = [3, 6, 8]
scroll_offset = 6
show_borders = true
show_hidden = false
show_icons = false
line_number_style = "none" # none, absolute, relative

# size, mtime, user, gourp, perm. can be combined with |.
# `none` to disable, `all` to enable all
# all and none can't be combined with other options
linemode = "size"

[display.sort]
sort_method = "natural" # lexical, mtime, natural, size, ext
case_sensitive = false
directories_first = true
reverse = false

[preview]
# max_preview_size = "2MB" # original config, but: invalid type: string "2MB", expected u64
max_preview_size = 2097152 # "2MB"
preview_script = "~/.config/joshuto/preview_file.sh" # make sure it's marked as executable

[search]
# insensitive, sensitive, smart
string_case_sensitivity = "insensitive"
glob_case_sensitivity = "sensitive"
regex_case_sensitivity = "sensitive"
fzf_case_sensitivity = "insensitive"

[tab]
home_page = "home" # inherit, home, root
