[default_view]

keymap = [
  { keys = ["escape"], commands = ["escape"] },
  { keys = ["alt+i"], commands = ["new_tab"] },
  { keys = ["alt+t"], commands = ["new_tab --cursor"] },
  { keys = ["T"], commands = ["new_tab --current"] },
  { keys = ["W"], commands = ["close_tab"] },
  { keys = ["ctrl+w"], commands = ["close_tab"] },
  { keys = ["q"], commands = ["close_tab"] },
  { keys = ["ctrl+c"], commands = ["quit"] },
  { keys = ["ctrl+d"], commands = ["quit --output-current-directory"] },
  { keys = ["Q"], commands = ["quit --output-current-directory"] }, # cd into current directory (see joshuto fish/bash function)

  { keys = ["z", "d"], commands = ["set_display_mode default"] },
  { keys = ["z", "m"], commands = ["set_display_mode minimal"] },
  { keys = ["z", "s"], commands = ["set_display_mode hsplit"] },
  { keys = ["R"], commands = ["reload_dirlist"] },
  { keys = ["z", "h"], commands = ["toggle_hidden"] },
  { keys = ["ctrl+h"], commands = ["toggle_hidden"] },
  { keys = ["."], commands = ["toggle_hidden"] },
  { keys = ["\t"], commands = ["tab_switch 1"] },
  { keys = ["backtab"], commands = ["tab_switch -1"] },
  { keys = ["alt+n"], commands = ["tab_switch 1"] },
  { keys = ["alt+p"], commands = ["tab_switch -1"] },

  { keys = ["alt+1"], commands = ["tab_switch_index 1"] },
  { keys = ["alt+2"], commands = ["tab_switch_index 2"] },
  { keys = ["alt+3"], commands = ["tab_switch_index 3"] },
  { keys = ["alt+4"], commands = ["tab_switch_index 4"] },
  { keys = ["alt+5"], commands = ["tab_switch_index 5"] },
  { keys = ["alt+6"], commands = ["tab_switch_index 6"] },
  { keys = ["alt+7"], commands = ["tab_switch_index 7"] },
  { keys = ["alt+8"], commands = ["tab_switch_index 8"] },
  { keys = ["alt+9"], commands = ["tab_switch_index 9"] },

  { keys = ["1"], commands = ["numbered_command 1"] },
  { keys = ["2"], commands = ["numbered_command 2"] },
  { keys = ["3"], commands = ["numbered_command 3"] },
  { keys = ["4"], commands = ["numbered_command 4"] },
  { keys = ["5"], commands = ["numbered_command 5"] },
  { keys = ["6"], commands = ["numbered_command 6"] },
  { keys = ["7"], commands = ["numbered_command 7"] },
  { keys = ["8"], commands = ["numbered_command 8"] },
  { keys = ["9"], commands = ["numbered_command 9"] },

  # arrow keys
  { keys = ["g", "arrow_up"], commands = ["cursor_move_up", "cursor_move_up", "cursor_move_up", "cursor_move_up", "cursor_move_up", "cursor_move_up", "cursor_move_up", "cursor_move_up"] },
  { keys = ["g", "arrow_down"], commands = ["cursor_move_down", "cursor_move_down", "cursor_move_down", "cursor_move_down", "cursor_move_down", "cursor_move_down", "cursor_move_down", "cursor_move_down"] },
  { keys = ["arrow_up"], commands = ["cursor_move_up"] },
  { keys = ["arrow_down"], commands = ["cursor_move_down"] },
  { keys = ["arrow_left"], commands = ["cd .."] },
  { keys = ["arrow_right"], commands = ["open"] },
  { keys = ["\n"], commands = ["open"] },
  { keys = ["home"], commands = ["cursor_move_home"] },
  { keys = ["end"], commands = ["cursor_move_end"] },
  { keys = ["page_up"], commands = ["cursor_move_page_up 0.5"] },
  { keys = ["page_down"], commands = ["cursor_move_page_down 0.5"] },
  { keys = ["ctrl+u"], commands = ["cursor_move_page_up 0.5"] },
  # { keys = ["ctrl+d"], commands = ["cursor_move_page_down 0.5"] },
  { keys = ["ctrl+b"], commands = ["cursor_move_page_up"] },
  { keys = ["ctrl+f"], commands = ["cursor_move_page_down"] },

  # vim-like keybindings
  { keys = ["j"], commands = ["cursor_move_down"] },
  { keys = ["k"], commands = ["cursor_move_up"] },
  { keys = ["h"], commands = ["cd .."] },
  { keys = ["l"], commands = ["open"] },
  { keys = ["g", "g"], commands = ["cursor_move_home"] },
  { keys = ["G"], commands = ["cursor_move_end"] },

  { keys = ["H"], commands = ["cursor_move_page_home"] },
  { keys = ["L"], commands = ["cursor_move_page_middle"] },
  { keys = ["M"], commands = ["cursor_move_page_end"] },

  { keys = ["["], commands = ["parent_cursor_move_up"] },
  { keys = ["]"], commands = ["parent_cursor_move_down"] },
  # { keys = ["["], commands = ["cd ..", "cursor_move_up", "open"] }, # for versions where the parent cursor move is not yet fixed (https://github.com/kamiyaa/joshuto/issues/570)
  # { keys = ["]"], commands = ["cd ..", "cursor_move_down", "open"] },  # for versions where the parent cursor move is not yet fixed (https://github.com/kamiyaa/joshuto/issues/570)

  { keys = ["c", "d"], commands = [":cd "] },
  { keys = ["d", "d"], commands = ["cut_files"] },
  { keys = ["y", "y"], commands = ["copy_files"] },
  { keys = ["y", "f"], commands = ["copy_filename"] },
  { keys = ["y", "n"], commands = ["copy_filename"] },
  { keys = ["y", "."], commands = ["copy_filename_without_extension"] },
  { keys = ["y", "p"], commands = ["copy_filepath"] },
  { keys = ["y", "a"], commands = ["copy_filepath --all-selected=true"] },
  { keys = ["y", "d"], commands = ["copy_dirpath"] },

  # in difference to ranger, symlinks are created on yank, not paste, see https://github.com/kamiyaa/joshuto/issues/544#issuecomment-2426252447
  { keys = ["y", "l"], commands = ["symlink_files --relative=false"] },
  { keys = ["y", "L"], commands = ["symlink_files --relative=true"] },
  { keys = ["p", "p"], commands = ["paste_files"] },
  { keys = ["p", "o"], commands = ["paste_files --overwrite=true"] },

  { keys = ["a", "p"], commands = ["shell apack archive.zip %s"] },
  { keys = ["u", "p"], commands = ["shell aunpack %s"] },

  # { keys = ["y", "b"], commands = ["shell cp -r %s %s.$(date +%F-%%H%M%S).bak"] },
  # { keys = ["y", "B"], commands = ["shell sudo cp -r %s %s.$(date +%F-%H%M%S).bak"] },
  { keys = ["y", "b"], commands = ["shell backup-file.sh %s"] },
  { keys = ["y", "B"], commands = ["shell sudo backup-file.sh %s"] },

  { keys = ["m", "v", "d"], commands = ["shell mv-to-dir.sh %s"] },

  { keys = ["delete"], commands = ["delete_files"] },
  { keys = ["d", "D"], commands = ["delete_files"] },
  { keys = ["x", "t"], commands = ["delete_files"] }, # should use trash (see `use_trash` setting!)
  { keys = ["x", "r"], commands = ["delete_files --permanently"] }, # bypass trash
  { keys = ["x", "R"], commands = ["shell sudo rm -rf %s"] },
  { keys = ["u", "t"], commands = ["shell trash-restore"] },

  { keys = ["c", "w"], commands = [":rename "] },
  { keys = ["c", "i", "w"], commands = [":rename "] },
  { keys = ["c", "a", "w"], commands = [":rename "] },
  { keys = ["A"], commands = ["rename_append_base"] },
  { keys = ["I"], commands = ["rename_prepend"] },
  { keys = ["c", "W"], commands = ["bulk_rename"] },

  { keys = [" "], commands = ["select --toggle=true"] },
  { keys = ["s"], commands = ["select --toggle=true"] },
  { keys = ["t"], commands = ["select --all=true --toggle=true"] },
  { keys = ["u", "s"], commands = ["select --all=false --toggle=false"] },
  { keys = ["v"], commands = ["toggle_visual"] },
  { keys = ["V"], commands = ["toggle_visual"] },

  { keys = ["w"], commands = ["show_tasks --exit-key=w"] },
  { keys = ["+"], commands = ["set_mode"] }, # chmod

  { keys = [":"], commands = [":"] },
  { keys = [";"], commands = [":shell "] },
  { keys = ["i", "f"], commands = ["shell fish -C 'set -x JOSHUTO 1'"] },
  { keys = ["i", "b"], commands = ["shell bash"] },
  { keys = ["i", "u"], commands = ["shell thunar ."] },
  { keys = ["i", "t"], commands = ["shell tig status"] },
  { keys = ["g", "s"], commands = ["shell tig status"] },
  { keys = ["g", "l", "l"], commands = ["shell tig log"] },
  { keys = ["g", "p", "l"], commands = ["shell git pull"] },
  { keys = ["g", "p", "s"], commands = ["shell git push"] },
  { keys = ["d", "u"], commands = ["shell ncdu ."] },
  # { keys = ["d", "u"], commands = ["shell du -h --max-depth=1 ."] },

  { keys = ["a", "f"], commands = [":touch "] },
  { keys = ["a", "d"], commands = [":mkdir "] },
  { keys = ["m", "k"], commands = [":mkdir "] },

  { keys = ["/"], commands = [":search "] },
  { keys = ["|"], commands = [":search_inc "] },
  { keys = ["\\"], commands = [":search_glob "] },
  { keys = ["f", "z"], commands = ["search_fzf"] },
  { keys = ["f", "i"], commands = ["subdir_fzf"] },
  { keys = ["f", "l"], commands = [":shell fzf_wrapper --locate --joshuto "] }, # TODO: don't nest joshuto instances
  { keys = ["f", "f"], commands = [":filter "] },
  { keys = ["u", "f"], commands = ["filter"] },
  { keys = ["n"], commands = ["search_next"] },
  { keys = ["N"], commands = ["search_prev"] },

  { keys = ["o", "w"], commands = ["open_with"] },
  { keys = ["e", "e"], commands = ["shell nvim %s"] },
  { keys = ["i", "v", "v"], commands = ["shell nvim"] },
  { keys = ["i", "v", "d"], commands = ["shell neovide"] },

  { keys = ["o", "r"], commands = ["sort reverse"] },
  { keys = ["o", "l"], commands = ["sort lexical"] },
  { keys = ["o", "m"], commands = ["sort mtime"] },
  { keys = ["o", "n"], commands = ["sort natural"] },
  { keys = ["o", "b"], commands = ["sort natural"] }, # "basename" like in ranger
  { keys = ["o", "s"], commands = ["sort size"] },
  { keys = ["o", "e"], commands = ["sort ext"] },

  { keys = ["m", "s"], commands = ["linemode size"] },
  { keys = ["m", "t"], commands = ["linemode mtime"] },
  { keys = ["m", "T"], commands = ["linemode size | mtime"] },
  { keys = ["m", "u"], commands = ["linemode user"] },
  { keys = ["m", "U"], commands = ["linemode user | group"] },
  { keys = ["m", "p"], commands = ["linemode perm"] },

  { keys = ["g", "e"     ], commands = ["cd /etc"] },
  { keys = ["g", "m"     ], commands = ["cd /mnt"] },
  { keys = ["g", "r"     ], commands = ["cd /"] },
  { keys = ["g", "t"     ], commands = ["cd /tmp"] },
  { keys = ["g", "h"     ], commands = ["cd ~/"] },
  { keys = ["'", "b"     ], commands = ["cd ~/"] },
  { keys = ["'", "c"     ], commands = ["cd ~/.config"] },
  { keys = ["'", "d"     ], commands = ["cd ~/dotfiles"] },
  { keys = ["'", "e"     ], commands = ["cd ~/tmp/telegram"] },
  { keys = ["'", "h"     ], commands = ["cd ~/"] },
  { keys = ["'", "i", "e"], commands = ["cd ~/img-screenshots"] },
  { keys = ["'", "i", "m"], commands = ["cd ~/Sync/img-memes"] },
  { keys = ["'", "i", "p"], commands = ["cd ~/img-personal"] },
  { keys = ["'", "p"     ], commands = ["cd ~/src-projects"] },
  { keys = ["'", "s", "c"], commands = ["cd ~/Sync/companies"] },
  { keys = ["'", "s", "e"], commands = ["cd ~/Sync/img-screenshots"] },
  { keys = ["'", "s", "f"], commands = ["cd ~/Sync/finance"] },
  { keys = ["'", "s", "g"], commands = ["cd ~/Sync/groups"] },
  { keys = ["'", "s", "i"], commands = ["cd ~/Sync/img"] },
  { keys = ["'", "s", "m"], commands = ["cd ~/Sync/misc"] },
  { keys = ["'", "s", "p"], commands = ["cd ~/Sync/people"] },
  { keys = ["'", "s", "s"], commands = ["cd ~/Sync"] },
  { keys = ["'", "s", "t"], commands = ["cd ~/Sync/things"] },
  { keys = ["'", "s", "w"], commands = ["cd ~/Sync/wohnen"] },
  { keys = ["'", "t"     ], commands = ["cd ~/tmp"] },
  { keys = ["'", "w", "m"], commands = ["cd ~/work/reply/misc"] },
  { keys = ["'", "w", "p"], commands = ["cd ~/work-projects"] },
  { keys = ["'", "w", "w"], commands = ["cd ~/work/reply"] },

  { keys = ["'", "'"], commands = ["cd_bookmark"] },
  { keys = ["m", "m"], commands = ["add_bookmark"] },

  { keys = ["?"], commands = ["help"] },
]

[task_view]

keymap = [
  # arrow keys
  { keys = ["arrow_up"], commands = ["cursor_move_up"] },
  { keys = ["arrow_down"], commands = ["cursor_move_down"] },
  { keys = ["home"], commands = ["cursor_move_home"] },
  { keys = ["end"], commands = ["cursor_move_end"] },

  # vim-like keybindings
  { keys = ["j"], commands = ["cursor_move_down"] },
  { keys = ["k"], commands = ["cursor_move_up"] },
  { keys = ["g", "g"], commands = ["cursor_move_home"] },
  { keys = ["G"], commands = ["cursor_move_end"] },

  { keys = ["w"], commands = ["show_tasks"] },
  { keys = ["escape"], commands = ["show_tasks"] },
]

[help_view]

keymap = [
  # arrow keys
  { keys = ["arrow_up"], commands = ["cursor_move_up"] },
  { keys = ["arrow_down"], commands = ["cursor_move_down"] },
  { keys = ["home"], commands = ["cursor_move_home"] },
  { keys = ["end"], commands = ["cursor_move_end"] },

  # vim-like keybindings
  { keys = ["j"], commands = ["cursor_move_down"] },
  { keys = ["k"], commands = ["cursor_move_up"] },
  { keys = ["g", "g"], commands = ["cursor_move_home"] },
  { keys = ["G"], commands = ["cursor_move_end"] },

  { keys = ["w"], commands = ["show_tasks"] },
  { keys = ["escape"], commands = ["show_tasks"] },
]
