# a2jmidid
# Autogenerated from man page /usr/share/man/man1/a2jmidid.1.gz
# using Deroffing man parser
complete -c a2jmidid -s e -l export-hw --description 'forces a2jmidid to bridge hardware ports as wel… [See Man Page]'
complete -c a2jmidid -s j --description 'specifies which jack-server to use AUTHOR Eric … [See Man Page]'

