# acpi_listen
# Autogenerated from man page /usr/share/man/man8/acpi_listen.8.gz
# using Deroffing man parser
complete -c acpi_listen -s c -l count --description 'Receive up to a maximum number of ACPI events, then exit.'
complete -c acpi_listen -s s -l socketfile --description 'This option changes the name of the UNIX domain… [See Man Page]'
complete -c acpi_listen -s t -l time --description 'Listen for the specified time in seconds, before exiting.'
complete -c acpi_listen -s v -l version --description 'Print version information and exit.'
complete -c acpi_listen -s h -l help --description 'Show help and exit.'

