# aeolus
# Autogenerated from man page /usr/share/man/man1/aeolus.1.gz
# using Deroffing man parser
complete -c aeolus -s h --description 'Display this text.'
complete -c aeolus -s t --description 'Text mode user interface.'
complete -c aeolus -s u --description 'Use presets file in user\'s home dir.'
complete -c aeolus -s N --description 'Name to use as JACK and ALSA client [aeolus].'
complete -c aeolus -s S --description 'Name of stops directory [stops].'
complete -c aeolus -s I --description 'Name of instrument directory [Aeolus].'
complete -c aeolus -s W --description 'Name of waves directory [waves].'
complete -c aeolus -s J --description 'Use JACK (default), with options:.'
complete -c aeolus -s s --description 'Select JACK server.'
complete -c aeolus -s B --description 'Ambisonics B format output.'
complete -c aeolus -s A --description 'Use ALSA, with options:.'
complete -c aeolus -s d --description 'Alsa device [default].'
complete -c aeolus -s r --description 'Sample frequency [48000].'
complete -c aeolus -s p --description 'Period size [1024].'
complete -c aeolus -s n --description 'Number of fragments [2] AUTHOR aeolus was writt… [See Man Page]'

