# alsactl
# Autogenerated from man page /usr/share/man/man1/alsactl.1.gz
# using Deroffing man parser
complete -c alsactl -s h -l help --description 'Help: show available flags and commands.'
complete -c alsactl -s d -l debug --description 'Use debug mode: a bit more verbose.'
complete -c alsactl -s v -l version --description 'Print alsactl version number.'
complete -c alsactl -s f -l file --description 'Select the configuration file to use.'
complete -c alsactl -s F -l force --description 'Used with restore command.'
complete -c alsactl -s g -l ignore --description 'Used with store and restore commands.'
complete -c alsactl -s P -l pedantic --description 'Used with restore command.'
complete -c alsactl -s I -l no-init-fallback --description 'Don\'t initialize cards if restore fails.   Since version 1. 0.'
complete -c alsactl -s r -l runstate --description 'Save restore and init state to this file.'
complete -c alsactl -s R -l remove --description 'Remove runstate file at first.'
complete -c alsactl -s E -l env --description 'Set environment variable (useful for init actio… [See Man Page]'
complete -c alsactl -s i -l initfile --description 'The configuration file for init.'

