# antspotlight
# Autogenerated from man page /usr/share/man/man6/antspotlight.6x.gz
# using Deroffing man parser
complete -c antspotlight -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c antspotlight -o root --description 'Draw on the root window.'
complete -c antspotlight -o install --description 'Install a private colormap for the window.'
complete -c antspotlight -o visual --description 'Specify which visual to use.'
complete -c antspotlight -o fps --description 'Display the current frame rate, CPU load, and polygon count.'
complete -c antspotlight -o delay --description 'Per-frame delay.'

