# apache2
# Autogenerated from man page /usr/share/man/man8/apache2.8.gz
# using Type1
complete -c apache2 -s d --description 'Set the initial value for the ServerRoot direct… [See Man Page]'
complete -c apache2 -s f --description 'Uses the directives in the file config on startup.'
complete -c apache2 -s k --description 'Signals apache2 to start, restart, or stop.'
complete -c apache2 -s C --description 'Process the configuration directive before read… [See Man Page]'
complete -c apache2 -s c --description 'Process the configuration directive after reading config files.'
complete -c apache2 -s D --description 'Sets a configuration parameter which can be use… [See Man Page]'
complete -c apache2 -s e --description 'Sets the LogLevel to level during server startup.'
complete -c apache2 -s E --description 'Send error messages during server startup to file.'
complete -c apache2 -s R --description 'When the server is compiled using the SHARED_CO… [See Man Page]'
complete -c apache2 -s h --description 'Output a short summary of available command line options.'
complete -c apache2 -s l --description 'Output a list of modules compiled into the server.'
complete -c apache2 -s L --description 'Output a list of directives together with expec… [See Man Page]'
complete -c apache2 -s M --description 'Dump a list of loaded Static and Shared Modules.'
complete -c apache2 -s S --description 'Show the settings as parsed from the config fil… [See Man Page]'
complete -c apache2 -s t --description 'Run syntax tests for configuration files only.'
complete -c apache2 -s v --description 'Print the version of apache2, and then exit.'
complete -c apache2 -s V --description 'Print the version and build parameters of apach… [See Man Page]'

