# apt-key
# Autogenerated from man page /usr/share/man/man8/apt-key.8.gz
# using Deroffing man parser
complete -c apt-key -l keyring --description 'With this option it is possible to specify a sp… [See Man Page]'
complete -c apt-key -s '.' --description 'del keyid.'

