# aptitude-run-state-bundle
# Autogenerated from man page /usr/share/man/man1/aptitude-run-state-bundle.1.gz
# using Deroffing man parser
complete -c aptitude-run-state-bundle -l append-args --description 'Place the options that give the location of the… [See Man Page]'
complete -c aptitude-run-state-bundle -l help --description 'Display a brief usage summary.'
complete -c aptitude-run-state-bundle -l prepend-args --description 'Place the options that give the location of the… [See Man Page]'
complete -c aptitude-run-state-bundle -l no-clean --description 'Do not remove the unpacked state directory afte… [See Man Page]'
complete -c aptitude-run-state-bundle -l really-clean --description 'Delete the state directory after running aptitu… [See Man Page]'
complete -c aptitude-run-state-bundle -l statedir --description 'Instead of treating the input file as a state b… [See Man Page]'
complete -c aptitude-run-state-bundle -l unpack --description 'Unpack the input file to a temporary directory,… [See Man Page]'
complete -c aptitude-run-state-bundle -l 'statedir.' --description '.'
complete -c aptitude-run-state-bundle -l 'no-clean.' --description '.'

