# ardour2
# Autogenerated from man page /usr/share/man/man1/ardour2.1.gz
# using Deroffing man parser
complete -c ardour2 -s b --description 'Print all possible keyboard binding names.'
complete -c ardour2 -s U --description 'Specify the path to the GTK RC file to use.'
complete -c ardour2 -l help --description 'Displays the help message.  FILES.'

