# arpsnmp
# Autogenerated from man page /usr/share/man/man8/arpsnmp.8.gz
# using Deroffing man parser
complete -c arpsnmp -s d --description 'flag is used enable debugging.'
complete -c arpsnmp -s f --description 'flag is used to set the ethernet/ip address database filename.'
complete -c arpsnmp -s s --description 'flag is used to specify the path to the sendmail program.'
complete -c arpsnmp -s m --description 'option is used to specify the e-mail address to… [See Man Page]'

