# as10k1
# Autogenerated from man page /usr/share/man/man1/as10k1.1.gz
# using Type1
complete -c as10k1 -s l --description 'Specify a listing file, default is none.'
complete -c as10k1 -s o --description 'Specify an output file, default is based on inp… [See Man Page]'
complete -c as10k1 -s d --description 'Turn on debug messages. RS.'
complete -c as10k1 -s h --description 'Prints a short help message.'

