# at
# Autogenerated from man page /usr/share/man/man1/at.1.gz
# using Deroffing man parser
complete -c at -s V --description 'prints the version number to standard error and… [See Man Page]'
complete -c at -s q --description 'uses the specified queue.'
complete -c at -s m --description 'Send mail to the user when the job has complete… [See Man Page]'
complete -c at -s M --description 'Never send mail to the user.'
complete -c at -s f --description 'Reads the job from  file rather than standard input.'
complete -c at -s t --description 'run the job at R time , given in the format [[CC]YY]MMDDhhmm[.'
complete -c at -s l --description 'Is an alias for  atq.'
complete -c at -s r --description 'Is an alias for  atrm.'
complete -c at -s d --description 'Is an alias for  atrm.'
complete -c at -s b --description 'is an alias for  batch .'
complete -c at -s v --description 'Shows the time the job will be executed before reading the job.'
complete -c at -s c --description 'cats the jobs listed on the command line to standard output.'

