# avahi-resolve-host-name
# Autogenerated from man page /usr/share/man/man1/avahi-resolve-host-name.1.gz
# using Deroffing man parser
complete -c avahi-resolve-host-name -s n -l name --description 'Translate one or more fully qualified host name… [See Man Page]'
complete -c avahi-resolve-host-name -s a -l address --description 'Translate one or more addresses into fully qual… [See Man Page]'
complete -c avahi-resolve-host-name -s v -l verbose --description 'Enable verbose mode.'
complete -c avahi-resolve-host-name -s 6 --description 'When resolving a host name, look for IPv6 addre… [See Man Page]'
complete -c avahi-resolve-host-name -s 4 --description 'When resolving a host name, look for IPv4 addre… [See Man Page]'
complete -c avahi-resolve-host-name -s h -l help --description 'Show help.'
complete -c avahi-resolve-host-name -s V -l version --description 'Show version information.'

