# avahi-resolve-address
# Autogenerated from man page /usr/share/man/man1/avahi-resolve-address.1.gz
# using Deroffing man parser
complete -c avahi-resolve-address -s n -l name --description 'Translate one or more fully qualified host name… [See Man Page]'
complete -c avahi-resolve-address -s a -l address --description 'Translate one or more addresses into fully qual… [See Man Page]'
complete -c avahi-resolve-address -s v -l verbose --description 'Enable verbose mode.'
complete -c avahi-resolve-address -s 6 --description 'When resolving a host name, look for IPv6 addre… [See Man Page]'
complete -c avahi-resolve-address -s 4 --description 'When resolving a host name, look for IPv4 addre… [See Man Page]'
complete -c avahi-resolve-address -s h -l help --description 'Show help.'
complete -c avahi-resolve-address -s V -l version --description 'Show version information.'

