# avirecompress
# Autogenerated from man page /usr/share/man/man1/avirecompress.1.gz
# using Deroffing man parser
complete -c avirecompress -s h -l help --description 'Show help message SEE ALSO aviplay(1).'

