# badblocks
# Autogenerated from man page /usr/share/man/man8/badblocks.8.gz
# using Deroffing man parser
complete -c badblocks -s b --description 'Specify the size of blocks in bytes.   The default is 1024.'
complete -c badblocks -s c --description 'is the number of blocks which are tested at a time.'
complete -c badblocks -s e --description 'Specify a maximum number of bad blocks before a… [See Man Page]'
complete -c badblocks -s d --description 'This parameter, if passed and non-zero, will ca… [See Man Page]'
complete -c badblocks -s f --description 'Normally, badblocks will refuse to do a read/wr… [See Man Page]'
complete -c badblocks -s i --description 'Read a list of already existing known bad blocks.'
complete -c badblocks -s n --description 'Use non-destructive read-write mode.'
complete -c badblocks -s o --description 'Write the list of bad blocks to the specified file.'
complete -c badblocks -s p --description 'Repeat scanning the disk until there are no new… [See Man Page]'
complete -c badblocks -s s --description 'Show the progress of the scan by writing out ro… [See Man Page]'
complete -c badblocks -s t --description 'Specify a test pattern to be read (and written) to disk blocks.'
complete -c badblocks -s v --description 'Verbose mode.'
complete -c badblocks -s w --description 'Use write-mode test.'
complete -c badblocks -s B --description 'Use buffered I/O and do not use Direct I/O, eve… [See Man Page]'
complete -c badblocks -s l --description 'option in  e2fsck (8) or mke2fs (8).'
complete -c badblocks -s X --description 'Internal flag only to be used by e2fsck (8) and mke2fs (8).'

