# bibtex8
# Autogenerated from man page /usr/share/man/man1/bibtex8.1.gz
# using Deroffing man parser
complete -c bibtex8 -s '?' -l help --description 'display this help text.'
complete -c bibtex8 -s 7 -l traditional --description 'operate in the original 7-bit mode.'
complete -c bibtex8 -s 8 -l 8bit --description 'force 8-bit mode, no CS file used.'
complete -c bibtex8 -s c -l csfile --description 'read FILE as the BibTeX character set and sort definition file.'
complete -c bibtex8 -s d -l debug --description 'report debugging information.'
complete -c bibtex8 -s s -l statistics --description 'report internal statistics.'
complete -c bibtex8 -s t -l trace --description 'report execution tracing.'
complete -c bibtex8 -s v -l version --description 'report BibTeX version.'
complete -c bibtex8 -s B -l big --description 'set large BibTeX capacity.'
complete -c bibtex8 -s H -l huge --description 'set huge BibTeX capacity.'
complete -c bibtex8 -s W -l wolfgang --description 'set really huge BibTeX capacity for Wolfgang.'
complete -c bibtex8 -s M -l min_crossrefs --description 'set min_crossrefs to ##.'
complete -c bibtex8 -l mcites --description 'allow ## cites in the . aux files.'
complete -c bibtex8 -l mentints --description 'allow ## integer entries in the . bib databases.'
complete -c bibtex8 -l mentstrs --description 'allow ## string entries in the . bib databases.'
complete -c bibtex8 -l mfields --description 'allow ## fields in the . bib databases.'
complete -c bibtex8 -l mpool --description 'set the string pool to ## bytes.'
complete -c bibtex8 -l mstrings --description 'allow ## unique strings.'
complete -c bibtex8 -l mwizfuns --description 'allow ## wizard functions AUTHORS bibtex8  was … [See Man Page]'

