# blenderplayer
# Autogenerated from man page /usr/share/man/man1/blenderplayer.1.gz
# using Deroffing man parser
complete -c blenderplayer -o 'g
:' --description 'TP 29 Name Default      Description .'
complete -c blenderplayer -s h --description ': Prints this command summary.'
complete -c blenderplayer -s w --description ': display in a window   optional parameters    … [See Man Page]'
complete -c blenderplayer -s f --description ': start game in full screen mode   optional par… [See Man Page]'
complete -c blenderplayer -s s --description ': start player in stereo.'
complete -c blenderplayer -s D --description ': start player in dome mode.'
complete -c blenderplayer -s m --description ': maximum anti-aliasing (eg.  2,4,8,16).'
complete -c blenderplayer -s i --description ': parent windows ID.'
complete -c blenderplayer -s d --description ': turn debugging on.'
complete -c blenderplayer -s g --description ': game engine options Name Default      Description.'
complete -c blenderplayer -l ------------------------- --description '.'
complete -c blenderplayer -l ---------------------------------- --description '.'

