# blkid
# Autogenerated from man page /usr/share/man/man8/blkid.8.gz
# using Deroffing man parser
complete -c blkid -s c --description 'Read from  cachefile instead of reading from th… [See Man Page]'
complete -c blkid -s d --description 'Don\'t encode non-printing characters.'
complete -c blkid -s g --description 'Perform a garbage collection pass on the blkid … [See Man Page]'
complete -c blkid -s h --description 'Display a usage message and exit.'
complete -c blkid -s i --description 'Display I/O Limits (aka I/O topology) information.'
complete -c blkid -s l --description 'Look up only one device that matches the search… [See Man Page]'
complete -c blkid -s k --description 'List all known filesystems and RAIDs and exit.'
complete -c blkid -s t --description 'option.'
complete -c blkid -s L --description 'Look up the device that uses this label (equal … [See Man Page]'
complete -c blkid -s n --description 'Restrict the probing functions to the specified… [See Man Page]'
complete -c blkid -s o --description 'Display  blkid \'s output using the specified format.'
complete -c blkid -s O --description 'Probe at the given offset (only useful with -p).'
complete -c blkid -s p --description 'Switch to low-level superblock probing mode (bypass cache).'
complete -c blkid -s s --description 'For each (specified) device, show only the tags… [See Man Page]'
complete -c blkid -s S --description 'Overwrite device/file size (only useful with -p).'
complete -c blkid -s u --description 'Restrict the probing functions to the specified… [See Man Page]'
complete -c blkid -s U --description 'Look up the device that uses this uuid.'
complete -c blkid -s v --description 'Display version number and exit.'
complete -c blkid -s w --description 'Write the device cache to  writecachefile inste… [See Man Page]'

