# blueman-assistant
# Autogenerated from man page /usr/share/man/man1/blueman-assistant.1.gz
# using Deroffing man parser
complete -c blueman-assistant -l device --description 'Address of the device to configure.'

