# bzip2
# Autogenerated from man page /usr/share/man/man1/bzip2.1.gz
# using Deroffing man parser
complete -c bzip2 -s c -l stdout --description 'Compress or decompress to standard output.'
complete -c bzip2 -s d -l decompress --description 'Force decompression.'
complete -c bzip2 -s z -l compress --description 'The complement to -d: forces compression, regar… [See Man Page]'
complete -c bzip2 -s t -l test --description 'Check integrity of the specified file(s), but d… [See Man Page]'
complete -c bzip2 -s f -l force --description 'Force overwrite of output files.'
complete -c bzip2 -s k -l keep --description 'Keep (don\'t delete) input files during compress… [See Man Page]'
complete -c bzip2 -s s -l small --description 'Reduce memory usage, for compression, decompres… [See Man Page]'
complete -c bzip2 -s q -l quiet --description 'Suppress non-essential warning messages.'
complete -c bzip2 -s v -l verbose --description 'Verbose mode -- show the compression ratio for … [See Man Page]'
complete -c bzip2 -s h -l help --description 'Print a help message and exit.'
complete -c bzip2 -s L -l license -s V -l version --description 'Display the software version, license terms and conditions.'
complete -c bzip2 -s 1 -l 'fast)' -s 9 -l 'best)' --description 'Set the block size to 100 k, 200 k .   900 k when compressing.'
complete -c bzip2 -l repetitive-fast -l repetitive-best --description 'These flags are redundant in versions 0. 9. 5 and above.'
complete -c bzip2 -o vvvv --description '.'

