# cabextract
# Autogenerated from man page /usr/share/man/man1/cabextract.1.gz
# using Deroffing man parser
complete -c cabextract -s d --description 'Extracts all files into the directory dir.'
complete -c cabextract -s f --description 'When testing or extracting cabinet files, corru… [See Man Page]'
complete -c cabextract -s F --description 'Only files with names that match the shell patt… [See Man Page]'
complete -c cabextract -s h --description 'Prints a page of help and exits.'
complete -c cabextract -s l --description 'Lists the contents of the given cabinet files, … [See Man Page]'
complete -c cabextract -s L --description 'When extracting cabinet files, makes each extra… [See Man Page]'
complete -c cabextract -s p --description 'Files shall be extracted to standard output.'
complete -c cabextract -s q --description 'When extracting cabinet files, suppresses all m… [See Man Page]'
complete -c cabextract -s s --description 'When testing, listing or extracting cabinets wh… [See Man Page]'
complete -c cabextract -s t --description 'Tests the integrity of the cabinet.'
complete -c cabextract -s v --description 'If given alone on the command line, prints the … [See Man Page]'

