# calendar
# Autogenerated from man page /usr/share/man/man1/calendar.1.gz
# using Darwin man parser
complete -c calendar -s A --description 'Print lines from today and next num days (forward, future).'
complete -c calendar -s a --description 'Process the calendar files of all users and mai… [See Man Page]'
complete -c calendar -s B --description 'Print lines from today and previous num days (backward, past).'
complete -c calendar -s b --description 'Enforce special date calculation mode for KOI8 calendars.'
complete -c calendar -s l --description 'Print lines from today and next num days (forward, future).'
complete -c calendar -s w --description 'Print lines from today and next num days, only … [See Man Page]'
complete -c calendar -s f --description 'Use calendarfile as the default calendar file.'
complete -c calendar -s t --description 'Act like the specified value is today instead o… [See Man Page]'

