# cancel
# Autogenerated from man page /usr/share/man/man1/cancel.1.gz
# using Deroffing man parser
complete -c cancel -s E --description 'br Forces encryption when connecting to the server.'
complete -c cancel -s U --description 'br Specifies the username to use when connecting to the server.'
complete -c cancel -s a --description 'br Cancel all jobs on the named destination, or… [See Man Page]'
complete -c cancel -s h --description 'br Chooses an alternate server.'
complete -c cancel -s u --description '.'

