# captoinfo
# Autogenerated from man page /usr/share/man/man1/captoinfo.1.gz
# using Deroffing man parser
complete -c captoinfo -s v --description 'print out tracing information on standard error… [See Man Page]'
complete -c captoinfo -s V --description 'print out the version of the program in use on … [See Man Page]'
complete -c captoinfo -s 1 --description 'cause the fields to print out one to a line.'
complete -c captoinfo -s w --description 'change the output to width characters.  FILES.'

