# check-language-support
# Autogenerated from man page /usr/share/man/man1/check-language-support.1.gz
# using Deroffing man parser
complete -c check-language-support -s h -l help --description 'show this help message and exit.'
complete -c check-language-support -s l -l language --description 'target language code - if omitted, check for al… [See Man Page]'
complete -c check-language-support -s d -l datadir --description 'use an alternative data directory instead of th… [See Man Page]'
complete -c check-language-support -s a -l all --description 'check all available languages.'
complete -c check-language-support -l show-installed --description 'show installed packages as well as missing ones… [See Man Page]'

