# chgpasswd
# Autogenerated from man page /usr/share/man/man8/chgpasswd.8.gz
# using Deroffing man parser
complete -c chgpasswd -s c -l crypt-method --description 'Use the specified method to encrypt the passwords.'
complete -c chgpasswd -s e -l encrypted --description 'Supplied passwords are in encrypted form.'
complete -c chgpasswd -s h -l help --description 'Display help message and exit.'
complete -c chgpasswd -s m -l md5 --description 'Use MD5 encryption instead of DES when the supp… [See Man Page]'
complete -c chgpasswd -s s -l sha-rounds --description 'Use the specified number of rounds to encrypt the passwords.'

