# chromium-browser
# Autogenerated from man page /usr/share/man/man1/chromium-browser.1.gz
# using Deroffing man parser
complete -c chromium-browser -l user-data-dir --description 'Specifies the directory that user data (your "p… [See Man Page]'
complete -c chromium-browser -l app --description 'Runs  URL in "app mode": with no browser toolbars.'
complete -c chromium-browser -l incognito --description 'Open in incognito mode.'
complete -c chromium-browser -l proxy-server --description 'Specify the HTTP/SOCKS4/SOCKS5 proxy server to … [See Man Page]'
complete -c chromium-browser -l no-proxy-server --description 'Disables the proxy server.'
complete -c chromium-browser -l proxy-auto-detect --description 'Autodetect proxy configuration.'
complete -c chromium-browser -l proxy-pac-url --description 'Specify proxy autoconfiguration URL.'
complete -c chromium-browser -l password-store --description 'Set the password store to use.'
complete -c chromium-browser -l version --description 'Show version information.'
complete -c chromium-browser -l display --description 'See the GTK documentation for more: <http://library. gnome.'

