# ckeygen
# Autogenerated from man page /usr/share/man/man1/ckeygen.1.gz
# using Deroffing man parser
complete -c ckeygen -s b -l bits --description 'Number of bits in the key to create (default: 1024).'
complete -c ckeygen -s f -l filename --description 'Filename of the key file.'
complete -c ckeygen -s t -l type --description 'Type of key (rsa or dsa).'
complete -c ckeygen -s C -l comment --description 'Provide a new comment.'
complete -c ckeygen -s N -l newpass --description 'Provide new passphrase.'
complete -c ckeygen -s P -l pass --description 'Provide old passphrase.'
complete -c ckeygen -s l -l fingerprint --description 'Show fingerprint of key file.'
complete -c ckeygen -s p -l changepass --description 'Change passphrase of private key file.'
complete -c ckeygen -s q -l quiet --description 'Be quiet.'
complete -c ckeygen -s y -l showpub --description 'Read private key file and print public key.'
complete -c ckeygen -l version --description 'Display version number only.'

