# clementine
# Autogenerated from man page /usr/share/man/man1/clementine.1.gz
# using Type1
complete -c clementine -s p -l play --description 'Start the playlist currently playing.'
complete -c clementine -s t -l play-pause --description 'Play if stopped, pause if playing.'
complete -c clementine -s u -l pause --description 'Pause playback.'
complete -c clementine -s s -l stop --description 'Stop playback.'
complete -c clementine -s r -l previous --description 'Skip backwards in playlist.'
complete -c clementine -s f -l next --description 'Skip forwards in playlist.'
complete -c clementine -s v -l volume --description 'Set the volume to <value> percent.'
complete -c clementine -l volume-up --description 'Increase the volume by 4%.'
complete -c clementine -l volume-down --description 'Decrease the volume by 4%.'
complete -c clementine -l seek-to --description 'Seek the currently playing track to an absolute position.'
complete -c clementine -l seek-by --description 'Seek the currently playing track by a relative amount.'
complete -c clementine -s a -l append --description 'Append files/URLs to the playlist.'
complete -c clementine -s l -l load --description 'Loads files/URLs, replacing current playlist.'
complete -c clementine -s k -l play-track --description 'Play the <n>th track in the playlist  . PP  Other options:.'
complete -c clementine -s h -l help --description 'Show summary of options.'
complete -c clementine -s o -l show-osd --description 'Display the on-screen-display.'
complete -c clementine -s e -l engine --description 'Select engine.'

