# cmakemodules
# Autogenerated from man page /usr/share/man/man1/cmakemodules.1.gz
# using Deroffing man parser
complete -c cmakemodules -l ------------------ --description '.'
complete -c cmakemodules -l ------------------------------------------------- --description 'This convenience include finds if wxWindows is … [See Man Page]'

