# colorfire
# Autogenerated from man page /usr/share/man/man1/colorfire.1.gz
# using Deroffing man parser
complete -c colorfire -l root --description 'Draw on the root window.'
complete -c colorfire -l maxfps --description 'Set maximum frame rate.'
complete -c colorfire -l vsync --description 'Limit redraws to specified number of vertical refreshes.'
complete -c colorfire -l dpms --description 'Stop rendering new frames if the display is not on.   0 - 1.'
complete -c colorfire -l texture --description '.'

