# corelist
# Autogenerated from man page /usr/share/man/man1/corelist.1.gz
# using Type1
complete -c corelist -s a --description 'lists all versions of the given module (or the … [See Man Page]'
complete -c corelist -s d --description 'finds the first perl version where a module has… [See Man Page]'
complete -c corelist -s '?' -o help --description 'help! help! help! to see more help, try --man.'
complete -c corelist -o man --description 'all of the help.'

