# ctie
# Autogenerated from man page /usr/share/man/man1/ctie.1.gz
# using Deroffing man parser
complete -c ctie -s c --description 'Create a single change file from the given R changefiles .'
complete -c ctie -s m --description 'Create a new master file by applying the given changefiles .'

