# cuebreakpoints
# Autogenerated from man page /usr/share/man/man1/cuebreakpoints.1.gz
# using Deroffing man parser
complete -c cuebreakpoints -s h -l help --description 'displays a usage message and exits.'
complete -c cuebreakpoints -s i -l input-format --description 'sets the expected format of the input file(s) t… [See Man Page]'
complete -c cuebreakpoints -l append-gaps --description 'appends pregaps to the end of the previous track.'
complete -c cuebreakpoints -l prepend-gaps --description 'prefixes pregaps to the beginning of each subsequent track.'
complete -c cuebreakpoints -l split-gaps --description 'option.'

