# cupsctl
# Autogenerated from man page /usr/share/man/man8/cupsctl.8.gz
# using Deroffing man parser
complete -c cupsctl -s E --description 'br Enables encryption on the connection to the scheduler.'
complete -c cupsctl -s U --description 'br Specifies an alternate username to use when … [See Man Page]'
complete -c cupsctl -s h --description 'br Specifies the server address.'
complete -c cupsctl -l '[no-]debug-logging' --description 'br Enables or disables debug logging in the error_log file.'
complete -c cupsctl -l '[no-]remote-admin' --description 'br Enables or disables remote administration.'
complete -c cupsctl -l '[no-]remote-any' --description 'br Enables or disables printing from any address, e. g.'
complete -c cupsctl -l '[no-]remote-printers' --description 'br Enables or disables the display of remote pr… [See Man Page]'
complete -c cupsctl -l '[no-]share-printers' --description 'br Enables or disables sharing of local printer… [See Man Page]'
complete -c cupsctl -l '[no-]user-cancel-any' --description '.'

