# cupsaccept
# Autogenerated from man page /usr/share/man/man8/cupsaccept.8.gz
# using Deroffing man parser
complete -c cupsaccept -s E --description 'br Forces encryption when connecting to the server.'
complete -c cupsaccept -s U --description 'br Sets the username that is sent when connecti… [See Man Page]'
complete -c cupsaccept -s h --description 'br Chooses an alternate server.'
complete -c cupsaccept -s r --description '.'

