# cupsd
# Autogenerated from man page /usr/share/man/man8/cupsd.8.gz
# using Deroffing man parser
complete -c cupsd -s c --description 'br Uses the named configuration file.'
complete -c cupsd -s f --description 'br Run cupsd in the foreground; the default is … [See Man Page]'
complete -c cupsd -s F --description 'br Run cupsd in the foreground but detach the p… [See Man Page]'
complete -c cupsd -s h --description 'br Shows the program usage.'
complete -c cupsd -s l --description 'br This option is passed to cupsd when it is ru… [See Man Page]'
complete -c cupsd -s t --description '.'

