# cups-lpd
# Autogenerated from man page /usr/share/man/man8/cups-lpd.8.gz
# using Deroffing man parser
complete -c cups-lpd -s h --description 'br Sets the CUPS server (and port) to use.'
complete -c cups-lpd -s n --description 'br Disables reverse address lookups; normally c… [See Man Page]'
complete -c cups-lpd -s o --description '.'

