# cupsreject
# Autogenerated from man page /usr/share/man/man8/cupsreject.8.gz
# using Deroffing man parser
complete -c cupsreject -s E --description 'br Forces encryption when connecting to the server.'
complete -c cupsreject -s U --description 'br Sets the username that is sent when connecti… [See Man Page]'
complete -c cupsreject -s h --description 'br Chooses an alternate server.'
complete -c cupsreject -s r --description '.'

