# cyclone
# Autogenerated from man page /usr/share/man/man1/cyclone.1.gz
# using Deroffing man parser
complete -c cyclone -l root --description 'Draw on the root window.'
complete -c cyclone -l maxfps --description 'Set maximum frame rate.'
complete -c cyclone -l vsync --description 'Limit redraws to specified number of vertical refreshes.'
complete -c cyclone -l dpms --description 'Stop rendering new frames if the display is not on.   0 - 1.'
complete -c cyclone -l cyclones --description 'Number of cyclones.   1 - 10.   Default: 1.'
complete -c cyclone -l particles --description 'Particles per cyclone.   1 - 10000.   Default: 200.'
complete -c cyclone -l size --description 'Particle size.   1 - 100.   Default: 7.'
complete -c cyclone -l complexity --description 'Cyclone complexity.   1 - 10.   Default: 3.'
complete -c cyclone -l speed --description 'Speed.   1 - 100.   Default: 10.'
complete -c cyclone -l stretch --description 'Stretch.   Default: True.'
complete -c cyclone -l showcurves --description 'Show Curves.'

