# cytune
# Autogenerated from man page /usr/share/man/man8/cytune.8.gz
# using Deroffing man parser
complete -c cytune -s s --description 'Set the current threshold to  value characters.'
complete -c cytune -s t --description 'Set the current flush timeout to  value units.'
complete -c cytune -s g --description 'Get the current threshold and timeout.'
complete -c cytune -s S --description 'Set the default threshold to  value characters.'
complete -c cytune -s T --description 'Set the default flush timeout to  value units.'
complete -c cytune -s G --description 'Get the default threshold and flush timeout values.'
complete -c cytune -s q --description 'Gather statistics about the R tty .'
complete -c cytune -s i --description 'Statistics will be gathered every interval seconds.'

