# dbus-uuidgen
# Autogenerated from man page /usr/share/man/man1/dbus-uuidgen.1.gz
# using Deroffing man parser
complete -c dbus-uuidgen -l 'get[' --description 'If a filename is not given, defaults to localst… [See Man Page]'
complete -c dbus-uuidgen -l 'ensure[' --description 'If a filename is not given, defaults to localst… [See Man Page]'
complete -c dbus-uuidgen -l version --description 'Print the version of dbus-uuidgen.'

