# debconf-apt-progress
# Autogenerated from man page /usr/share/man/man1/debconf-apt-progress.1.gz
# using Type1
complete -c debconf-apt-progress -l config --description 'Print environment variables necessary to start … [See Man Page]'
complete -c debconf-apt-progress -l start --description 'Start up a progress bar, running from 0 to 100 by default.'
complete -c debconf-apt-progress -l from --description 'If used with --start, make the progress bar beg… [See Man Page]'
complete -c debconf-apt-progress -l to --description 'If used with --start, make the progress bar end… [See Man Page]'
complete -c debconf-apt-progress -l stop --description 'Stop a running progress bar.'
complete -c debconf-apt-progress -l no-progress --description 'Avoid starting, stopping, or stepping the progress bar.'
complete -c debconf-apt-progress -l dlwaypoint --description 'Specify what percent of the progress bar to use… [See Man Page]'
complete -c debconf-apt-progress -l logfile --description 'Send the normal output from apt to the given file.'
complete -c debconf-apt-progress -l logstderr --description 'Send the normal output from apt to stderr.'

