# debconf-set-selections
# Autogenerated from man page /usr/share/man/man1/debconf-set-selections.1.gz
# using Type1
complete -c debconf-set-selections -l verbose -s v --description 'verbose output.'

