# delgroup
# Autogenerated from man page /usr/share/man/man8/delgroup.8.gz
# using Deroffing man parser
complete -c delgroup -l conf --description 'Use FILE instead of the default files R /etc/deluser.'
complete -c delgroup -l group --description 'Remove a group.'
complete -c delgroup -l help --description 'Display brief instructions.'
complete -c delgroup -l quiet --description 'Suppress progress messages.'
complete -c delgroup -l system --description 'Only delete if user/group is a system user/group.'
complete -c delgroup -l backup --description 'Backup all files contained in the userhome and … [See Man Page]'
complete -c delgroup -l backup-to --description 'Place the backup files not in / but in the dire… [See Man Page]'
complete -c delgroup -l remove-home --description 'Remove the home directory of the user and its mailspool.'
complete -c delgroup -l remove-all-files --description 'Remove all files from the system owned by this user.'
complete -c delgroup -l force --description 'parameter; this may prevent to remove the root … [See Man Page]'
complete -c delgroup -l only-if-empty --description 'is given, the group won\'t be removed if it has … [See Man Page]'
complete -c delgroup -l version --description 'Display version and copyright information.  RETURN VALUE.'

