# devdump
# Autogenerated from man page /usr/share/man/man1/devdump.1.gz
# using Deroffing man parser
complete -c devdump -s h --description 'print a summary of all options.'
complete -c devdump -s d --description 'Print information from the primary volume descr… [See Man Page]'
complete -c devdump -s f --description 'generate output as if a \'find .'
complete -c devdump -s i --description 'Specifies the path of the iso9660 image that we… [See Man Page]'
complete -c devdump -s l --description 'generate output as if a \'ls -lR\' command had be… [See Man Page]'
complete -c devdump -s N --description 'Quick hack to help examine single session disc … [See Man Page]'
complete -c devdump -s p --description 'Print path table information.'
complete -c devdump -s R --description 'Extract information from Rock Ridge extensions … [See Man Page]'
complete -c devdump -s J --description 'Extract information from Joliet extensions (if … [See Man Page]'
complete -c devdump -s j --description 'Convert Joliet file names (if present) to the supplied charset.'
complete -c devdump -s T --description 'Quick hack to help examine multi-session images… [See Man Page]'
complete -c devdump -o help -o version --description 'i =name, dev =name.'
complete -c devdump -s x --description 'Extract specified file to stdout.'

