# dfutool
# Autogenerated from man page /usr/share/man/man1/dfutool.1.gz
# using Deroffing man parser
complete -c dfutool -s h --description 'Gives a list of possible commands.'
complete -c dfutool -s d --description 'The command specifies the device to use.  COMMANDS.'

