# dh
# Autogenerated from man page /usr/share/man/man1/dh.1.gz
# using Type1
complete -c dh -l with --description 'Add the debhelper commands specified by the giv… [See Man Page]'
complete -c dh -l without --description 'The inverse of --with, disables using the given addon.'
complete -c dh -l list -s l --description 'List all available addons.'

