# dh_auto_install
# Autogenerated from man page /usr/share/man/man1/dh_auto_install.1.gz
# using Type1
complete -c dh_auto_install -l destdir --description 'Install files into the specified directory.'

