# dh_builddeb
# Autogenerated from man page /usr/share/man/man1/dh_builddeb.1.gz
# using Type1
complete -c dh_builddeb -l destdir --description 'Use this if you want the generated .'
complete -c dh_builddeb -l filename --description 'Use this if you want to force the generated .'

