# dh_dkms
# Autogenerated from man page /usr/share/man/man1/dh_dkms.1.gz
# using Type1
complete -c dh_dkms -s l -l legacy --description 'Add code to also support \\s-1DKMS\\s0 versions < 2. 1. 0. 0.'
complete -c dh_dkms -s V -s V --description 'If \\f(CW\\*(C`PACKAGE_VERSION\\*(C\' in dkms.'

