# dh_installtex
# Autogenerated from man page /usr/share/man/man1/dh_installtex.1.gz
# using Type1
complete -c dh_installtex -s n -l noscripts --description 'Do not modify postinst/prerm scripts.'
complete -c dh_installtex -l priority --description 'Set the default priority to n instead of 20.'

