# dh_installudev
# Autogenerated from man page /usr/share/man/man1/dh_installudev.1.gz
# using Type1
complete -c dh_installudev -l name --description 'When this parameter is used, dh_installudev loo… [See Man Page]'
complete -c dh_installudev -l priority --description 'Sets the priority string of the rules. d symlink.'

