# dh_installchangelogs
# Autogenerated from man page /usr/share/man/man1/dh_installchangelogs.1.gz
# using Type1
complete -c dh_installchangelogs -s k -l keep --description 'Keep the original name of the upstream changelog.'
complete -c dh_installchangelogs -o Xitem -l exclude --description 'Exclude upstream changelog files that contain i… [See Man Page]'

