# dh_shlibdeps
# Autogenerated from man page /usr/share/man/man1/dh_shlibdeps.1.gz
# using Type1
complete -c dh_shlibdeps -o Xitem -l exclude --description 'Exclude files that contain item anywhere in the… [See Man Page]'
complete -c dh_shlibdeps -o uparams -l dpkg-shlibdeps-params --description 'This is another way to pass params to dpkg-shlibdeps\\|(1).'
complete -c dh_shlibdeps -o 'ldirectory[:directory' --description 'With recent versions of dpkg-shlibdeps, this op… [See Man Page]'

