# dhparam
# Autogenerated from man page /usr/share/man/man1/dhparam.1ssl.gz
# using Type1
complete -c dhparam -o inform --description 'This specifies the input format.'
complete -c dhparam -o outform --description 'This specifies the output format, the options h… [See Man Page]'
complete -c dhparam -o in --description 'This specifies the input filename to read param… [See Man Page]'
complete -c dhparam -o out --description 'This specifies the output filename parameters to.'
complete -c dhparam -o dsaparam --description 'If this option is used, \\s-1DSA\\s0 rather than … [See Man Page]'
complete -c dhparam -s 2 -s 5 --description 'The generator to use, either 2 or 5.  2 is the default.'
complete -c dhparam -o rand --description 'a file or files containing random data used to … [See Man Page]'
complete -c dhparam -o noout --description 'this option inhibits the output of the encoded … [See Man Page]'
complete -c dhparam -o text --description 'this option prints out the \\s-1DH\\s0 parameters… [See Man Page]'
complete -c dhparam -s C --description 'this option converts the parameters into C code.'

