# dpkg-scanpackages
# Autogenerated from man page /usr/share/man/man1/dpkg-scanpackages.1.gz
# using Deroffing man parser
complete -c dpkg-scanpackages -s t -l type --description 'Scan for *. type packages, instead of *. deb.'
complete -c dpkg-scanpackages -s u -l udeb --description 'Obsolete alias for -tudeb.'
complete -c dpkg-scanpackages -s e -l extra-override --description 'Scan file to find supplementary overrides (the … [See Man Page]'
complete -c dpkg-scanpackages -s a -l arch --description 'Use a pattern consisting of *_all. deb and *_arch.'
complete -c dpkg-scanpackages -s m -l multiversion --description 'Include all found packages in the output.'
complete -c dpkg-scanpackages -s M -l medium --description 'Add an X-Medium field containing the value id-string.'
complete -c dpkg-scanpackages -s h -l help --description 'Show the usage message and exit.'
complete -c dpkg-scanpackages -l version --description 'Show the version and exit.'

