# dpkg-preconfigure
# Autogenerated from man page /usr/share/man/man8/dpkg-preconfigure.8.gz
# using Type1
complete -c dpkg-preconfigure -o ftype -l frontend --description 'Select the frontend to use.'
complete -c dpkg-preconfigure -o pvalue -l priority --description 'Set the lowest priority of questions you are interested in.'
complete -c dpkg-preconfigure -l terse --description 'Enables terse output mode.  This affects only some frontends.'
complete -c dpkg-preconfigure -l apt --description 'Run in apt mode.'

