# dpkg-parsechangelog
# Autogenerated from man page /usr/share/man/man1/dpkg-parsechangelog.1.gz
# using Deroffing man parser
complete -c dpkg-parsechangelog -s l --description 'Specifies the change log file to read information from.'
complete -c dpkg-parsechangelog -s F --description 'Specifies the format of the changelog.'
complete -c dpkg-parsechangelog -s L --description 'Specify an additional directory to search for parser scripts.'
complete -c dpkg-parsechangelog -s h -l help --description 'Show the usage message and exit.'
complete -c dpkg-parsechangelog -l version --description 'Show the version and exit.'
complete -c dpkg-parsechangelog -l format --description 'Set the output format.'
complete -c dpkg-parsechangelog -l since -s s -s v --description 'include all changes later than version.'
complete -c dpkg-parsechangelog -l until -s u --description 'include all changes earlier than version.'
complete -c dpkg-parsechangelog -l from -s f --description 'include all changes equal or later than version.'
complete -c dpkg-parsechangelog -l to -s t --description 'include all changes up to or equal than version.'
complete -c dpkg-parsechangelog -l count -s c -s n --description 'include number entries from the top (or the tai… [See Man Page]'
complete -c dpkg-parsechangelog -l offset -s o --description 'change the starting point for --count, counted … [See Man Page]'
complete -c dpkg-parsechangelog -l all --description 'include all changes.'

