# dpkg-deb
# Autogenerated from man page /usr/share/man/man1/dpkg-deb.1.gz
# using Deroffing man parser
complete -c dpkg-deb -l showformat --description 'This option is used to specify the format of th… [See Man Page]'
complete -c dpkg-deb -s z --description 'Specify which compression level to use on the c… [See Man Page]'
complete -c dpkg-deb -s Z --description 'Specify which compression type to use when building a package.'
complete -c dpkg-deb -l new --description 'Ensures that  dpkg-deb builds a `new\' format archive.'
complete -c dpkg-deb -l old --description 'Forces  dpkg-deb to build an `old\' format archive.'
complete -c dpkg-deb -l nocheck --description 'Inhibits  "dpkg-deb --build" \'s usual checks on… [See Man Page]'
complete -c dpkg-deb -s v -l verbose --description 'Enables verbose output.'
complete -c dpkg-deb -s b -l build --description 'Creates a debian archive from the filesystem tr… [See Man Page]'
complete -c dpkg-deb -s I -l info --description 'Provides information about a binary package archive.'
complete -c dpkg-deb -s W -l show --description 'Provides information about a binary package arc… [See Man Page]'
complete -c dpkg-deb -s f -l field --description 'Extracts control file information from a binary… [See Man Page]'
complete -c dpkg-deb -s c -l contents --description 'Lists the contents of the filesystem tree archi… [See Man Page]'
complete -c dpkg-deb -s x -l extract --description 'Extracts the filesystem tree from a package arc… [See Man Page]'
complete -c dpkg-deb -s X -l vextract --description 'Is like.'
complete -c dpkg-deb -s R -l raw-extract --description 'Extracts the filesystem tree from a package arc… [See Man Page]'
complete -c dpkg-deb -l fsys-tarfile --description 'Extracts the filesystem tree data from a binary… [See Man Page]'
complete -c dpkg-deb -s e -l control --description 'Extracts the control information files from a p… [See Man Page]'
complete -c dpkg-deb -s h -l help --description 'Show the usage message and exit.'
complete -c dpkg-deb -l version --description 'Show the version and exit.'
complete -c dpkg-deb -s D -l debug --description 'Enables debugging output.  This is not very interesting.'

