# dpkg-scansources
# Autogenerated from man page /usr/share/man/man1/dpkg-scansources.1.gz
# using Deroffing man parser
complete -c dpkg-scansources -s n -l no-sort --description 'Don\'t sort the index records.'
complete -c dpkg-scansources -s e -l extra-override --description 'Scan file to find supplementary overrides (the … [See Man Page]'
complete -c dpkg-scansources -s s -l source-override --description 'Use file as the source override file (the file … [See Man Page]'
complete -c dpkg-scansources -l debug --description 'Turn debugging on.'
complete -c dpkg-scansources -l help --description 'Show the usage message and exit.'
complete -c dpkg-scansources -l version --description 'Show the version and exit.'

