# dssi_osc_send
# Autogenerated from man page /usr/share/man/man1/dssi_osc_send.1.gz
# using Deroffing man parser
complete -c dssi_osc_send -s c --description 'Send a `control\' message.'
complete -c dssi_osc_send -s p --description 'Send a `program\' message.'
complete -c dssi_osc_send -s m --description 'Send `midi\' message.'
complete -c dssi_osc_send -s C --description 'Send a `configure\' message.'
complete -c dssi_osc_send -s s --description 'Send a `show\' message.    dssi_osc_send -s <OSC URL>.'
complete -c dssi_osc_send -s h --description 'Send a `hide\' message.    dssi_osc_send -h <OSC URL>.'
complete -c dssi_osc_send -s q --description 'Send a `quit\' message.    dssi_osc_send -q <OSC URL>.'
complete -c dssi_osc_send -s e --description 'Send a `exiting\' message.    dssi_osc_send -e <OSC URL>.'

