# dumpcap
# Autogenerated from man page /usr/share/man/man1/dumpcap.1.gz
# using Type1
complete -c dumpcap -s a --description 'Specify a criterion that specifies when Dumpcap… [See Man Page]'
complete -c dumpcap -s b --description 'Cause Dumpcap to run in \\*(L"multiple files\\*(R" mode.'
complete -c dumpcap -s B --description 'Set capture buffer size (in \\s-1MB\\s0, default is 1MB).'
complete -c dumpcap -s c --description 'Set the maximum number of packets to read when … [See Man Page]'
complete -c dumpcap -s d --description 'Dump the code generated for the capture filter … [See Man Page]'
complete -c dumpcap -s D --description 'Print a list of the interfaces on which Dumpcap… [See Man Page]'
complete -c dumpcap -s f --description 'Set the capture filter expression.'
complete -c dumpcap -s h --description 'Print the version and options and exits.'
complete -c dumpcap -s i --description 'Set the name of the network interface or pipe t… [See Man Page]'
complete -c dumpcap -s I --description 'Put the interface in \\*(L"monitor mode\\*(R"; th… [See Man Page]'
complete -c dumpcap -s L --description 'List the data link types supported by the interface and exit.'
complete -c dumpcap -s M --description 'When used with -D, -L and -S, print machine-readable output.'
complete -c dumpcap -s n --description 'Write the output file in the pcap-ng format ins… [See Man Page]'
complete -c dumpcap -s p --description 'Don\'t put the interface into promiscuous mode.'
complete -c dumpcap -s q --description 'When capturing packets, don\'t display the conti… [See Man Page]'
complete -c dumpcap -s s --description 'Set the default snapshot length to use when cap… [See Man Page]'
complete -c dumpcap -s S --description 'Print statistics for each interface once every second.'
complete -c dumpcap -s v --description 'Print the version and exit.'
complete -c dumpcap -s w --description 'Write raw packet data to outfile.'

