# dumpe2fs
# Autogenerated from man page /usr/share/man/man8/dumpe2fs.8.gz
# using Deroffing man parser
complete -c dumpe2fs -s b --description 'print the blocks which are reserved as bad in the filesystem.'
complete -c dumpe2fs -s o --description 'use the block  superblock when examining the filesystem.'
complete -c dumpe2fs -s f --description 'force dumpe2fs to display a filesystem even tho… [See Man Page]'
complete -c dumpe2fs -s h --description 'only display the superblock information and not… [See Man Page]'
complete -c dumpe2fs -s i --description 'display the filesystem data from an image file … [See Man Page]'
complete -c dumpe2fs -s x --description 'print the detailed group information block numb… [See Man Page]'
complete -c dumpe2fs -s V --description 'print the version number of  dumpe2fs and exit.'

