# dvd+rw-booktype
# Autogenerated from man page /usr/share/man/man1/dvd+rw-booktype.1.gz
# using Deroffing man parser
complete -c dvd+rw-booktype -o dvd-rom --description 'This is useful for addressing DVD-ROM compatibi… [See Man Page]'

