# dvi2tty
# Autogenerated from man page /usr/share/man/man1/dvi2tty.1.gz
# using Deroffing man parser
complete -c dvi2tty -s o --description 'Write output to file ``file\'\'.'
complete -c dvi2tty -s p --description 'Print the pages chosen by list.'
complete -c dvi2tty -s P --description 'Like -p except that page numbers refer to the s… [See Man Page]'
complete -c dvi2tty -s w --description 'Specify terminal width  n.  Legal range 16-132.  Default is 80.'
complete -c dvi2tty -s q --description 'Don\'t pipe the output through a pager.'
complete -c dvi2tty -s f --description 'Pipe through a pager, $PAGER if defined, or wha… [See Man Page]'
complete -c dvi2tty -s F --description 'Specify the pager program to be used.'
complete -c dvi2tty -o Fprog --description 'Use ``prog\'\' as program to pipe output into.'
complete -c dvi2tty -s l --description 'Mark pagebreaks with the two-character sequence ``^L\'\'.'
complete -c dvi2tty -s u --description 'Don\'t make any attempts to find special Scandin… [See Man Page]'
complete -c dvi2tty -s s --description 'Try to find the special Scandinavian characters… [See Man Page]'

