# dvitomp
# Autogenerated from man page /usr/share/man/man1/dvitomp.1.gz
# using Deroffing man parser
complete -c dvitomp -o help --description 'write usage summary and exit.'
complete -c dvitomp -o version --description 'output version information and exit.'

