# e4defrag
# Autogenerated from man page /usr/share/man/man8/e4defrag.8.gz
# using Deroffing man parser
complete -c e4defrag -s c --description 'Get a current fragmentation count and an ideal … [See Man Page]'
complete -c e4defrag -s v --description 'option, the current fragmentation count and the… [See Man Page]'

