# empathy
# Autogenerated from man page /usr/share/man/man1/empathy.1.gz
# using Deroffing man parser
complete -c empathy -s n -l no-connect --description 'Don\'t connect on startup.'
complete -c empathy -s h -l start-hidden --description 'Don\'t display the contact list or any other dialogs on startup.'
complete -c empathy -s v -l version --description 'Show version ENVIRONMENT.'

