# enchant-lsmod
# Autogenerated from man page /usr/share/man/man1/enchant-lsmod.1.gz
# using Deroffing man parser
complete -c enchant-lsmod -o lang --description 'Show dictionary to be used for given language_tag.'
complete -c enchant-lsmod -o list-dicts --description 'List preferred dictionaries for language tags.'
complete -c enchant-lsmod -s h --description 'Show help info and exit.'
complete -c enchant-lsmod -s v --description 'Show version and exit.'

