# envy24control
# Autogenerated from man page /usr/share/man/man1/envy24control.1.gz
# using Deroffing man parser
complete -c envy24control -s c --description 'Use the card specified by card-number rather th… [See Man Page]'
complete -c envy24control -s D --description 'Use the card specified by control-name rather t… [See Man Page]'
complete -c envy24control -s o --description 'Limit number of analog line outputs to display.'
complete -c envy24control -s i --description 'Limit number of analog line inputs to display.'
complete -c envy24control -s p --description 'Limit number of PCM outputs to display.   Default is 8.'
complete -c envy24control -s s --description 'Limit number of SPDIF inputs/outputs to display.'
complete -c envy24control -s f --description 'From/to this file will envy24control read/write… [See Man Page]'
complete -c envy24control -s v --description 'It is not possible to manage something (muting, volume levels).'
complete -c envy24control -s m --description 'Use MIDI controller values to control the Fader… [See Man Page]'
complete -c envy24control -s M --description 'Use an enhanced mapping from midi controller va… [See Man Page]'
complete -c envy24control -s w --description 'Specify the initial width of the envy24control window.'
complete -c envy24control -s t --description 'Using -t 1 enlarges the channel mixers to the s… [See Man Page]'

