# epsffit
# Autogenerated from man page /usr/share/man/man1/epsffit.1.gz
# using Deroffing man parser
complete -c epsffit -s c --description 'Center the image in the given bounding box.'
complete -c epsffit -s r --description 'Rotate the image by 90 degrees counter-clockwise.'
complete -c epsffit -s a --description 'Adjust the aspect ratio to fit the bounding box.'
complete -c epsffit -s m --description 'Rotates the image to maximise the size if it wo… [See Man Page]'
complete -c epsffit -s s --description 'Add a showpage at the end of the file to force … [See Man Page]'

