# erb1
# Autogenerated from man page /usr/share/man/man1/erb1.8.1.gz
# using Deroffing man parser
complete -c erb1 -s x --description 'print ruby script.'
complete -c erb1 -s n --description 'print ruby script with line number.'
complete -c erb1 -s v --description 'enables verbose mode.'
complete -c erb1 -s d --description 'set debugging flags (set $DEBUG to true).'
complete -c erb1 -s r --description 'load a library.'
complete -c erb1 -s K --description 'specifies KANJI code-set (euc or sjis) or UTF-8 (utf8).'
complete -c erb1 -s S --description 'set $SAFE (0. 4).'
complete -c erb1 -s T --description 'specify trim_mode (0. 2).'
complete -c erb1 -s P --description 'disregard the lin which starts in "%"  SEE ALSO.'

