# euphoria
# Autogenerated from man page /usr/share/man/man1/euphoria.1.gz
# using Deroffing man parser
complete -c euphoria -l root --description 'Draw on the root window.'
complete -c euphoria -l maxfps --description 'Set maximum frame rate.'
complete -c euphoria -l vsync --description 'Limit redraws to specified number of vertical refreshes.'
complete -c euphoria -l dpms --description 'Stop rendering new frames if the display is not on.   0 - 1.'
complete -c euphoria -l preset --description 'Ds 1 - Regular (--regular) 2 - Grid (--grid) 3 … [See Man Page]'
complete -c euphoria -l wisps --description 'Number of wisps.   0 - 128.   Default: 5.'
complete -c euphoria -l bgwisps --description 'Number of background layers.   0 - 128.   Default: 0.'
complete -c euphoria -l density --description 'Mesh Density.   2 - 1000.   Default: 25.'
complete -c euphoria -l visibility --description 'Visibility.   1 - 100.   Default: 35.'
complete -c euphoria -l speed --description 'Speed.   1 - 100.   Default: 15.'
complete -c euphoria -l feedback --description 'Feedback.   0 - 100.   Default: 0.'
complete -c euphoria -l feedbackspeed --description 'Feedback speed.   1 - 100.   Default: 1.'
complete -c euphoria -l feedbacksize --description 'Feedback size.   1 - 10.   Default: 8.'
complete -c euphoria -l wireframe --description 'Render in wireframe instead of solid.'
complete -c euphoria -l texture --description '.'

