# exo-csource
# Autogenerated from man page /usr/share/man/man1/exo-csource.1.gz
# using Deroffing man parser
complete -c exo-csource -l build-list --description 'option, a list of (name, file) pairs to generat… [See Man Page]'
complete -c exo-csource -s h -l help --description '.'
complete -c exo-csource -s v -l version --description '.'
complete -c exo-csource -l extern --description '.'
complete -c exo-csource -l static --description '.'
complete -c exo-csource -l name --description '.'

