# extractres
# Autogenerated from man page /usr/share/man/man1/extractres.1.gz
# using Deroffing man parser
complete -c extractres -s m --description 'option combines the resources of the same name … [See Man Page]'

