# faad
# Autogenerated from man page /usr/share/man/man1/faad.1.gz
# using Type1
complete -c faad -s a -l adtsout --description 'Sets the processing to output to the specified … [See Man Page]'
complete -c faad -s b -l bits --description 'Set the output (individual) sample format.'
complete -c faad -s d -l downmix --description 'Set the processing to downsample from 5.'
complete -c faad -s f -l format --description 'Set the output file format.'
complete -c faad -s g --description 'Set the processing to not perform gapless decoding.'
complete -c faad -s h -l help --description 'Shows a usage summary.'
complete -c faad -s i -l info --description 'Shows information about the about the input file.'
complete -c faad -s l -l objecttype --description 'Sets the MPEG\\hy(4 profile and object type for … [See Man Page]'
complete -c faad -s o -l outfile --description 'Sets the filename for processing output.'
complete -c faad -s q -l quiet --description 'Quiet - Suppresses status messages during processing.'
complete -c faad -s t -l oldformat --description 'Sets the processing to use the old MPEG\\(hy4 AA… [See Man Page]'

