# faillog
# Autogenerated from man page /usr/share/man/man8/faillog.8.gz
# using Deroffing man parser
complete -c faillog -s a -l all --description 'Display (or act on) faillog records for all use… [See Man Page]'
complete -c faillog -s h -l help --description 'Display help message and exit.'
complete -c faillog -s l -l lock-secs --description 'Lock account for SEC seconds after failed login.'
complete -c faillog -s m -l maximum --description 'Set the maximum number of login failures after … [See Man Page]'
complete -c faillog -s r -l reset --description 'Reset the counters of login failures.'
complete -c faillog -s t -l time --description 'Display faillog records more recent than DAYS.'
complete -c faillog -s u -l user --description 'Display faillog record or maintains failure cou… [See Man Page]'

