# fdformat
# Autogenerated from man page /usr/share/man/man8/fdformat.8.gz
# using Deroffing man parser
complete -c fdformat -s n -l no-verify --description 'Skip the verification that is normally performe… [See Man Page]'
complete -c fdformat -s V -l version --description 'Output version information and exit.'
complete -c fdformat -s h -l help --description 'Display help and exit.'

