# fdisk
# Autogenerated from man page /usr/share/man/man8/fdisk.8.gz
# using Deroffing man parser
complete -c fdisk -s b --description 'Specify the sector size of the disk.'
complete -c fdisk -s c --description 'Specify the compatiblity mode, \'dos\' or \'nondos\'.'
complete -c fdisk -s C --description 'Specify the number of cylinders of the disk.'
complete -c fdisk -s H --description 'Specify the number of heads of the disk.'
complete -c fdisk -s S --description 'Specify the number of sectors per track of the disk.'
complete -c fdisk -s h --description 'Print help and then exit.'
complete -c fdisk -s l --description 'List the partition tables for the specified dev… [See Man Page]'
complete -c fdisk -s s --description 'Print the size (in blocks) of each given partition.'
complete -c fdisk -s u --description 'When listing partition tables, show sizes in \'s… [See Man Page]'
complete -c fdisk -o 'c[' --description 'Specify the compatiblity mode, \'dos\' or \'nondos\'.'
complete -c fdisk -o 'u[' --description 'When listing partition tables, show sizes in \'s… [See Man Page]'
complete -c fdisk -s v --description 'Print version number of fdisk program and exit.'

