# filefrag
# Autogenerated from man page /usr/share/man/man8/filefrag.8.gz
# using Deroffing man parser
complete -c filefrag -s B --description 'Force the use of the older FIBMAP ioctl instead… [See Man Page]'
complete -c filefrag -s b --description 'Use 1024 byte blocksize for the output.'
complete -c filefrag -s s --description 'Sync the file before requesting the mapping.'
complete -c filefrag -s v --description 'Be verbose when checking for file fragmentation.'
complete -c filefrag -s x --description 'Display mapping of extended attributes.'

