# file-roller
# Autogenerated from man page /usr/share/man/man1/file-roller.1.gz
# using Deroffing man parser
complete -c file-roller -s a -l add-to --description 'Add files to the specified archive and quit the program.'
complete -c file-roller -s d -l add --description 'Add files asking the name of the archive and quit the program.'
complete -c file-roller -s e -l extract-to --description 'Extract archives to the specified folder and quit the program.'
complete -c file-roller -s f -l extract --description 'Extract archives asking the destination folder … [See Man Page]'
complete -c file-roller -s h -l extract-here --description 'Extract archives using the archive name as dest… [See Man Page]'
complete -c file-roller -l default-dir --description 'Default folder to use for the \'--add\' and \'--extract\' commands.'
complete -c file-roller -l force --description 'Create destination folder without asking confirmation.'

