# finger
# Autogenerated from man page /usr/share/man/man1/finger.1.gz
# using Darwin man parser
complete -c finger -s s --description 'finger Finger displays the user\'s login name, r… [See Man Page]'
complete -c finger -s l --description 'Produces a multi-line format displaying all of … [See Man Page]'
complete -c finger -s p --description 'Prevents the l option of finger finger from dis… [See Man Page]'
complete -c finger -s m --description 'Prevent matching of user names.'

