# firefox
# Autogenerated from man page /usr/share/man/man1/firefox.1.gz
# using Deroffing man parser
complete -c firefox -s h -l help --description 'Prints the command line options.'
complete -c firefox -s g -l debug --description 'Starts firefox in a debugger.'
complete -c firefox -s d -l debugger --description 'Specify the debugger in which to start firefox.'
complete -c firefox -s a -l debugger-args --description 'Specify arguments to pass to the debugger.'
complete -c firefox -o no-remote --description 'Don\'t connect to any other running instances of firefox.'
complete -c firefox -o ProfileManager --description 'Start the profilemanager.'
complete -c firefox -s P --description 'Start firefox with the profile named profile.'
complete -c firefox -o safe-mode --description 'Start firefox in safe-mode.'
complete -c firefox -o new-tab --description 'Open url in a new tab.'
complete -c firefox -o new-window --description 'Open url in a new window.'
complete -c firefox -s v -o version --description 'Print the current version of firefox.'
complete -c firefox -o UILocale --description 'Start firefox with the specified locale locale.'
complete -c firefox -o preferences --description 'Open the preferences dialog.'
complete -c firefox -o private --description 'Start firefox in private browsing mode.'
complete -c firefox -o private-toggle --description 'Toggle private browsing mode.'
complete -c firefox -o setDefaultBrowser --description 'Set firefox as the default web browser.'
complete -c firefox -o search --description 'Search for term with your default search engine.'
complete -c firefox -o jsconsole --description 'Open the Error console.'

