# fixcvsdiff
# Autogenerated from man page /usr/share/man/man1/fixcvsdiff.1.gz
# using Deroffing man parser
complete -c fixcvsdiff -s b --description 'Keep a . bak backup file.'
complete -c fixcvsdiff -s p --description 'Print out the cvs add and cvs remove commands t… [See Man Page]'

