# flipdiff
# Autogenerated from man page /usr/share/man/man1/flipdiff.1.gz
# using Deroffing man parser
complete -c flipdiff -s p -l strip-match --description 'When comparing filenames, ignore the first n pa… [See Man Page]'
complete -c flipdiff -s q -l quiet --description 'Quieter output.'
complete -c flipdiff -s U -l unified --description 'Attempt to display n lines of context (requires… [See Man Page]'
complete -c flipdiff -s d -l drop-context --description 'Don\\*(Aqt display any context on files that mat… [See Man Page]'
complete -c flipdiff -s i -l ignore-case --description 'Consider upper- and lower-case to be the same.'
complete -c flipdiff -s w -l ignore-all-space --description 'Ignore whitespace changes in patches.'
complete -c flipdiff -s b -l ignore-space-change --description 'Ignore changes in the amount of whitespace.'
complete -c flipdiff -s B -l ignore-blank-lines --description 'Ignore changes whose lines are all blank.'
complete -c flipdiff -s z -l decompress --description 'Decompress files with extensions . gz and . bz2.'
complete -c flipdiff -l in-place --description 'Write output to the original input files.'
complete -c flipdiff -l help --description 'Display a short usage message.'
complete -c flipdiff -l version --description 'Display the version number of flipdiff.'

