# flux
# Autogenerated from man page /usr/share/man/man1/flux.1.gz
# using Deroffing man parser
complete -c flux -l root --description 'Draw on the root window.'
complete -c flux -l maxfps --description 'Set maximum frame rate.'
complete -c flux -l vsync --description 'Limit redraws to specified number of vertical refreshes.'
complete -c flux -l dpms --description 'Stop rendering new frames if the display is not on.   0 - 1.'
complete -c flux -l fluxes --description 'Number of flux fields.   1 - 100.   Default: 1.'
complete -c flux -l particles --description 'Particles per field.   1 - 1000.   Default: 20.'
complete -c flux -l trail --description 'Trail length of particles.   3 - 10000.   Default: 40.'
complete -c flux -l geometry --description 'Ds 0 - Points (--points) 1 - Spheres (--spheres… [See Man Page]'
complete -c flux -l size --description 'Particle Size.   1 - 100.   Default: 15.'
complete -c flux -l complexity --description 'Sphere Complexity.   0 - 100.   Default: 3.'
complete -c flux -l randomize --description 'Frequency of randomization.   0 - 100.   Default: 0.'
complete -c flux -l expansion --description 'Expansion rate.   0 - 100.   Default: 40.'
complete -c flux -l rotation --description 'Rotation rate.   0 - 100.   Default: 30.'
complete -c flux -l wind --description 'Crosswind speed.   0 - 100.   Default: 20.'
complete -c flux -l instability --description 'Instability.   0 - 100.   Default: 20.'
complete -c flux -l blur --description 'Motion Blur.   0 - 100.   Default: 0.'
complete -c flux -l preset --description '.'

