# fontmatrix
# Autogenerated from man page /usr/share/man/man1/fontmatrix.1.gz
# using Type1
complete -c fontmatrix -s l -l lang --description 'Overrides the system locale and runs Fontmatrix in language xx.'
complete -c fontmatrix -s v -l version --description 'Prints the Fontmatrix version number and exits.'
complete -c fontmatrix -s f -l file --description 'Open the specified file.'
complete -c fontmatrix -s h -l help --description 'Print a brief usage summary.'

