# foo2slx-wrapper
# Autogenerated from man page /usr/share/man/man1/foo2slx-wrapper.1.gz
# using Deroffing man parser
complete -c foo2slx-wrapper -s c --description 'Print in color (else monochrome).'
complete -c foo2slx-wrapper -s m --description 'Media code to send to printer [0].'
complete -c foo2slx-wrapper -s p --description 'Paper size code to send to printer [6].'
complete -c foo2slx-wrapper -s n --description 'Number of copies [1].'
complete -c foo2slx-wrapper -s r --description 'Set device resolution in pixels/inch [1200x600].'
complete -c foo2slx-wrapper -s s --description 'Source (Input Slot) code to send to printer [0].'
complete -c foo2slx-wrapper -s 2 -s 3 -s 4 -s 5 -s 6 -s 8 -s 9 -o 10 -o 12 -o 14 -o 15 -o 16 -o 18 --description 'Print in N-up.   Requires the psutils package.'
complete -c foo2slx-wrapper -s o --description 'Orientation used for N-up.'
complete -c foo2slx-wrapper -s u --description 'Set the offset of the start of the printable re… [See Man Page]'
complete -c foo2slx-wrapper -s l --description 'Set the offset of the end of the printable regi… [See Man Page]'
complete -c foo2slx-wrapper -s L --description 'Send the logical clipping values from -u/-l in the ZjStream.'
complete -c foo2slx-wrapper -s g --description 'Additional options to pass to Ghostscript, such… [See Man Page]'
complete -c foo2slx-wrapper -s G --description 'Convert profile.'
complete -c foo2slx-wrapper -s I --description 'Select profile intent from the ICM file.'
complete -c foo2slx-wrapper -s S --description 'Output just a single color plane from a color p… [See Man Page]'
complete -c foo2slx-wrapper -s D --description 'Set Debug level [0].'

