# foo2oak
# Autogenerated from man page /usr/share/man/man1/foo2oak.1.gz
# using Deroffing man parser
complete -c foo2oak -s c --description 'Force color mode if autodetect doesn\'t work.'
complete -c foo2oak -s d --description 'Duplex code to send to printer [1].'
complete -c foo2oak -s g --description 'Set page dimensions in pixels [10200x6600].'
complete -c foo2oak -s m --description 'Media code to send to printer [1].'
complete -c foo2oak -s p --description 'Paper code to send to printer [1].'
complete -c foo2oak -s n --description 'Number of copies [1].'
complete -c foo2oak -s r --description 'Set device resolution in pixels/inch [600x600].'
complete -c foo2oak -s s --description 'Source (InputSlot) code to send to printer [7].'
complete -c foo2oak -s J --description 'Filename string to send to printer.'
complete -c foo2oak -s U --description 'Username string to send to printer.'
complete -c foo2oak -s u --description 'Set the offset of the start of the printable re… [See Man Page]'
complete -c foo2oak -s l --description 'Set the offset of the end of the printable regi… [See Man Page]'
complete -c foo2oak -s L --description 'Send logical clipping amounts implied by -u/-l … [See Man Page]'
complete -c foo2oak -s A --description 'AllIsBlack: convert C=1,M=1,Y=1 to just K=1.'
complete -c foo2oak -s B --description 'BlackClears: K=1 forces C,M,Y to 0.'
complete -c foo2oak -s M --description 'Mirror bytes.'
complete -c foo2oak -s z --description 'Model is 0 for the HP Color LaserJet 1500, and … [See Man Page]'
complete -c foo2oak -s S --description 'Output just a single color plane from a color p… [See Man Page]'
complete -c foo2oak -s D --description 'Set Debug level [0].'

