# foo2hiperc
# Autogenerated from man page /usr/share/man/man1/foo2hiperc.1.gz
# using Deroffing man parser
complete -c foo2hiperc -s c --description 'Force color mode if autodetect doesn\'t work.'
complete -c foo2hiperc -s d --description 'Duplex code to send to printer [1].'
complete -c foo2hiperc -s g --description 'Set page dimensions in pixels [5100x6600].'
complete -c foo2hiperc -s m --description 'Media code to send to printer [0].'
complete -c foo2hiperc -s p --description 'Paper code to send to printer [2].'
complete -c foo2hiperc -s n --description 'Number of copies [1].'
complete -c foo2hiperc -s r --description 'Set device resolution in pixels/inch [600x600].'
complete -c foo2hiperc -s s --description 'Source (InputSlot) code to send to printer [0].'
complete -c foo2hiperc -s t --description 'Draft mode.   Every other pixel is white.'
complete -c foo2hiperc -s J --description 'Filename string to send to printer.'
complete -c foo2hiperc -s U --description 'Username string to send to printer.'
complete -c foo2hiperc -s u --description 'Set the offset of the start of the printable re… [See Man Page]'
complete -c foo2hiperc -s l --description 'Set the offset of the end of the printable regi… [See Man Page]'
complete -c foo2hiperc -s L --description 'Send logical clipping amounts implied by -u/-l … [See Man Page]'
complete -c foo2hiperc -s A --description 'AllIsBlack: convert C=1,M=1,Y=1 to just K=1.'
complete -c foo2hiperc -s B --description 'BlackClears: K=1 forces C,M,Y to 0.'
complete -c foo2hiperc -s Z --description 'Use uncompressed (0) or compressed (1) JBIG data.'
complete -c foo2hiperc -s S --description 'Output just a single color plane from a color p… [See Man Page]'
complete -c foo2hiperc -s D --description 'Set Debug level [0].'

