# foomatic-ppd-options
# Autogenerated from man page /usr/share/man/man1/foomatic-ppd-options.1.gz
# using Deroffing man parser
complete -c foomatic-ppd-options -s d --description 'Set the debug level.  0 disables debug messages.'

