# foomatic-compiledb
# Autogenerated from man page /usr/share/man/man1/foomatic-compiledb.1.gz
# using Deroffing man parser
complete -c foomatic-compiledb -s t --description 'Output file type, either ppd or xml.'
complete -c foomatic-compiledb -s f --description 'Force: Write into the destination directory eve… [See Man Page]'
complete -c foomatic-compiledb -s j --description 'n = number of work processes to run driver .'

