# foomatic-ppdfile
# Autogenerated from man page /usr/share/man/man1/foomatic-ppdfile.1.gz
# using Deroffing man parser
complete -c foomatic-ppdfile -s d --description 'The (optional) driver name to use.'
complete -c foomatic-ppdfile -s p --description 'printer id The printer id.'
complete -c foomatic-ppdfile -s w --description 'Return a PPD file that conforms to the Microsof… [See Man Page]'
complete -c foomatic-ppdfile -s A --description 'Return all printer entries in the database.'
complete -c foomatic-ppdfile -s P --description 'Return all printer entries in the database whic… [See Man Page]'

