# foomatic-configure
# Autogenerated from man page /usr/share/man/man1/foomatic-configure.1.gz
# using Deroffing man parser
complete -c foomatic-configure -s n --description 'Configure this print queue.'
complete -c foomatic-configure -s N --description 'Use this proper human-readable name/description.'
complete -c foomatic-configure -s L --description 'Short phrase describing this printer\'s location.'
complete -c foomatic-configure -s c --description 'Printer is connected thusly (ex file:/dev/lp0).'
complete -c foomatic-configure -s d --description 'Foomatic database name for desired printer driver.'
complete -c foomatic-configure -s p --description 'Foomatic id for printer.'
complete -c foomatic-configure -l ppd --description 'PPD file, for example the one supplied by the m… [See Man Page]'
complete -c foomatic-configure -s s --description 'Explicit spooler type (cups, lpd, lprng, pdq, ppr, direct).'
complete -c foomatic-configure -s o --description 'Set the default of option to value.'
complete -c foomatic-configure -s D --description 'Set this queue as the default queue (just give -n queuename).'
complete -c foomatic-configure -s R --description 'Remove this whole queue entirely (just give -n queuename).'
complete -c foomatic-configure -s C --description 'Copy sourcequeue from sourcespooler (or the cur… [See Man Page]'
complete -c foomatic-configure -s Q --description 'Query existing configuration (gives XML summary).'
complete -c foomatic-configure -s r --description 'List also remotely defined queues (CUPS only).'
complete -c foomatic-configure -s P --description 'Get Perl dump of current configuration (as a Pe… [See Man Page]'
complete -c foomatic-configure -s O --description 'Print XML Overview of all known printer/drivers… [See Man Page]'
complete -c foomatic-configure -s X --description 'Print XML data for -p printer and/or -d driver object.'
complete -c foomatic-configure -s q --description 'Run quietly Commands No commands, just options … [See Man Page]'

