# foomatic-rip
# Autogenerated from man page /usr/share/man/man1/foomatic-rip.1.gz
# using Deroffing man parser
complete -c foomatic-rip -s v --description 'verbose mode for debugging.'
complete -c foomatic-rip -s q --description 'quiet mode - minimal information output.'
complete -c foomatic-rip -s P --description '<printer> is the configured printer which shoul… [See Man Page]'
complete -c foomatic-rip -l ppd --description 'The PPD file <ppdfile> should be applied for pr… [See Man Page]'
complete -c foomatic-rip -s J --description 'The <jobtitle> will be printed in the head line… [See Man Page]'
complete -c foomatic-rip -s o --description 'Option settings for this job, do .'
complete -c foomatic-rip -l ------------------- --description 'This way you can print directly to your printer, use.'

