# fping6
# Autogenerated from man page /usr/share/man/man8/fping6.8.gz
# using Deroffing man parser
complete -c fping6 -s a --description 'Show systems that are alive.'
complete -c fping6 -s A --description 'Display targets by address rather than DNS name.'
complete -c fping6 -o bn --description 'Number of bytes of ping data to send.'
complete -c fping6 -o Bn --description 'In the default mode,  fping sends several req… [See Man Page]'
complete -c fping6 -s c --description 'Number of request packets to send to each target.'
complete -c fping6 -s C --description 'Similar to -c, but the per-target statistics ar… [See Man Page]'
complete -c fping6 -s d --description 'Use DNS to lookup address of return ping packet.'
complete -c fping6 -s e --description 'Show elapsed (round-trip) time of packets.'
complete -c fping6 -s f --description 'Read list of targets from a file.'
complete -c fping6 -s g --description 'Generate a target list from a supplied IP netma… [See Man Page]'
complete -c fping6 -s h --description 'Print usage message.'
complete -c fping6 -o in --description 'The minimum amount of time (in milliseconds) be… [See Man Page]'
complete -c fping6 -s l --description 'Loop sending packets to each target indefinitely.'
complete -c fping6 -s m --description 'Send pings to each of a target host\'s multiple interfaces.'
complete -c fping6 -s n --description 'Same as -d.'
complete -c fping6 -s p --description 'In looping or counting modes (-l, -c, or -C), t… [See Man Page]'
complete -c fping6 -s q --description 'Quiet.'
complete -c fping6 -o Qn --description 'Like -q, but show summary results every n seconds.'
complete -c fping6 -o rn --description 'Retry limit (default 3).'
complete -c fping6 -s s --description 'Print cumulative statistics upon exit.'
complete -c fping6 -o Saddr --description 'Set source address.'
complete -c fping6 -o tn --description 'Initial target timeout in milliseconds (default 500).'
complete -c fping6 -o Tn --description 'Select timeout in seconds (default 10).'
complete -c fping6 -s u --description 'Show targets that are unreachable.'
complete -c fping6 -o 'Q).' --description 'when all requests have been sent (or when interrupted).'
complete -c fping6 -s v --description 'Print  fping version information.'

