# free
# Autogenerated from man page /usr/share/man/man1/free.1.gz
# using Deroffing man parser
complete -c free -s b --description 'Display the amount of memory in bytes.'
complete -c free -s c --description 'Display the result count times.   Requires the -s option.'
complete -c free -s g --description 'Display the amount of memory in gigabytes.'
complete -c free -s k --description 'Display the amount of memory in kilobytes.'
complete -c free -s l --description 'Show detailed low and high memory statistics.'
complete -c free -s m --description 'Display the amount of memory in megabytes.'
complete -c free -s o --description 'Display the output in old format, the only diff… [See Man Page]'
complete -c free -s s --description 'Continuously display the result delay seconds apart.'
complete -c free -s t --description 'Display a line showing the column totals.'
complete -c free -s V --description 'Display version information.  FILES.'

