# gacutil
# Autogenerated from man page /usr/share/man/man1/gacutil.1.gz
# using Deroffing man parser
complete -c gacutil -o package --description '.'
complete -c gacutil -s i --description '.'
complete -c gacutil -s l --description '.'
complete -c gacutil -s u --description '.'
complete -c gacutil -o us --description 'Uninstalls an assembly using the specified asse… [See Man Page]'
complete -c gacutil -o ul --description 'Uninstalls one or more assemblies from the glob… [See Man Page]'

