# gbx2
# Autogenerated from man page /usr/share/man/man1/gbx2.1.gz
# using Type1
complete -c gbx2 -s h --description 'display help and exit.'
complete -c gbx2 -s g --description 'enter debugging mode.'
complete -c gbx2 -s V --description 'display version.'
complete -c gbx2 -s p --description 'disable preloading.'

