# gdbus
# Autogenerated from man page /usr/share/man/man1/gdbus.1.gz
# using Deroffing man parser
complete -c gdbus -l xml --description 'option is used, the returned introspection XML … [See Man Page]'
complete -c gdbus -l recurse --description 'option can be used to introspect children (and … [See Man Page]'
complete -c gdbus -l only-properties --description 'option can be used to only print the interfaces… [See Man Page]'

