# gdbus-codegen
# Autogenerated from man page /usr/share/man/man1/gdbus-codegen.1.gz
# using Deroffing man parser
complete -c gdbus-codegen -l interface-prefix --description 'A prefix to strip from all D-Bus interface name… [See Man Page]'
complete -c gdbus-codegen -l generate-docbook --description 'Generate Docbook Documentation for each D-Bus i… [See Man Page]'
complete -c gdbus-codegen -l generate-c-code --description 'Generate C code for all D-Bus interfaces and pu… [See Man Page]'
complete -c gdbus-codegen -l c-namespace --description 'The namespace to use for generated C code.'
complete -c gdbus-codegen -l c-generate-object-manager --description 'If this option is passed, suitable #GDBusObject… [See Man Page]'
complete -c gdbus-codegen -l annotate --description 'Used to inject D-Bus annotations into the given XML files.'
complete -c gdbus-codegen -l 'generate-c-code)' --description '.'
complete -c gdbus-codegen -l 'generate-docbook).' --description 'GENERATING C CODE.'
complete -c gdbus-codegen -o derived --description 'FooBar, two concrete instantiable types, FooBar… [See Man Page]'

