# gedit
# Autogenerated from man page /usr/share/man/man1/gedit.1.gz
# using Deroffing man parser
complete -c gedit -s b -l background --description 'Run  gedit in the background.'
complete -c gedit -l encoding --description 'Set the character encoding to be used for openi… [See Man Page]'
complete -c gedit -s g -l geometry --description 'Set the X geometry window size (WIDTHxHEIGHT+X+Y).'
complete -c gedit -l list-encodings --description 'Display list of possible values for the encodin… [See Man Page]'
complete -c gedit -l new-window --description 'Create a new toplevel window in an existing instance of  gedit.'
complete -c gedit -l new-document --description 'Create a new document in an existing instance of  gedit.'
complete -c gedit -s s -l standalone --description 'Run  gedit in standalone mode.'
complete -c gedit -s w -l wait --description 'Open files and block the  gedit process.'
complete -c gedit -l help --description 'Prints the command line options.'
complete -c gedit -l version --description 'Output version information and exit.'

