# genccode
# Autogenerated from man page /usr/share/man/man8/genccode.8.gz
# using Deroffing man parser
complete -c genccode -s h -s '?' -l help --description 'Print help about usage and exit.'
complete -c genccode -s a -l assembly --description 'Output assembly code instead of C code.'
complete -c genccode -s d -l destdir --description 'Set the destination directory to R destination .'
complete -c genccode -s n -l name --description 'Set the data name to  name instead of the default.'
complete -c genccode -s f -l filename --description 'Normally, an ICU data file such as mydata.'
complete -c genccode -s e -l entrypoint --description 'Set the data entry point (used for linking agai… [See Man Page]'
complete -c genccode -s t -l type --description 'option).  VERSION 4. 8. 1.'

