# gennorm2
# Autogenerated from man page /usr/share/man/man8/gennorm2.8.gz
# using Deroffing man parser
complete -c gennorm2 -s h -s '?' -l help --description 'Print help about usage and exit.'
complete -c gennorm2 -s V -l version --description 'Print the version of  gennorm2 and exit.'
complete -c gennorm2 -s c -l copyright --description 'Include a copyright notice.'
complete -c gennorm2 -s v -l verbose --description 'Display extra informative messages during execution.'
complete -c gennorm2 -s u -l unicode --description 'Specify Unicode version number, such as 5. 2. 0.'
complete -c gennorm2 -s s -l sourcedir --description 'Specify the input directory.'
complete -c gennorm2 -l fast --description 'optimize the .'

