# genrsa
# Autogenerated from man page /usr/share/man/man1/genrsa.1ssl.gz
# using Type1
complete -c genrsa -o out --description 'the output filename.'
complete -c genrsa -o passout --description 'the output file password source.'
complete -c genrsa -o des -o des3 -o idea --description 'These options encrypt the private key with the … [See Man Page]'
complete -c genrsa -o F4 -s 3 --description 'the public exponent to use, either 65537 or 3.'
complete -c genrsa -o rand --description 'a file or files containing random data used to … [See Man Page]'
complete -c genrsa -o engine --description 'specifying an engine (by its unique id string) … [See Man Page]'

