# ghc-pkg-7
# Autogenerated from man page /usr/share/man/man1/ghc-pkg-7.4.1.1.gz
# using Deroffing man parser
complete -c ghc-pkg-7 -l user --description 'Use the current user\'s package database.'
complete -c ghc-pkg-7 -l global --description 'Use the global package database.'
complete -c ghc-pkg-7 -s f -l package-conf --description 'Use the specified package config file.'
complete -c ghc-pkg-7 -l global-conf --description 'Location of the global package config.'
complete -c ghc-pkg-7 -l force --description 'Ignore missing dependencies, directories, and libraries.'
complete -c ghc-pkg-7 -l force-files --description 'Ignore missing directories and libraries only.'
complete -c ghc-pkg-7 -s g -l auto-ghc-libs --description 'Automatically build libs for GHCi (with register).'
complete -c ghc-pkg-7 -s '?' -l help --description 'Display a help message and exit.'
complete -c ghc-pkg-7 -s V -l version --description 'Output version information and exit.'
complete -c ghc-pkg-7 -l simple-output --description 'Print output in easy-to-parse format for some commands.'
complete -c ghc-pkg-7 -l names-only --description 'Only print package names, not versions; can onl… [See Man Page]'
complete -c ghc-pkg-7 -l ignore-case --description 'Ignore case for substring matching.  ENVIRONMENT VARIABLES.'

