# gigolo
# Autogenerated from man page /usr/share/man/man1/gigolo.1.gz
# using Type1
complete -c gigolo -s i -l new-instance --description 'Don\'t find and show an already running instance… [See Man Page]'
complete -c gigolo -s l -l list-schemes --description 'Print a list of supported URI schemes and exit.'
complete -c gigolo -s v -l verbose --description 'Be verbose and print some more information to stdout.'
complete -c gigolo -s V -l version --description 'Show version information.'

