# git-verify-tag
# Autogenerated from man page /usr/share/man/man1/git-verify-tag.1.gz
# using Deroffing man parser
complete -c git-verify-tag -s v -l verbose --description 'Print the contents of the tag object before validating it.'

