# git-shortlog
# Autogenerated from man page /usr/share/man/man1/git-shortlog.1.gz
# using Deroffing man parser
complete -c git-shortlog -s h -l help --description 'Print a short usage message and exit.'
complete -c git-shortlog -s n -l numbered --description 'Sort output according to the number of commits … [See Man Page]'
complete -c git-shortlog -s s -l summary --description 'Suppress commit description and provide a commi… [See Man Page]'
complete -c git-shortlog -s e -l email --description 'Show the email address of each author.'
complete -c git-shortlog -l 'format[' --description 'Instead of the commit subject, use some other i… [See Man Page]'
complete -c git-shortlog -o 'w[<width>[' --description 'Linewrap the output by wrapping each line at width.'
complete -c git-shortlog -l format --description 'option of git log, such as * [%h] %s.'

