# git-stripspace
# Autogenerated from man page /usr/share/man/man1/git-stripspace.1.gz
# using Deroffing man parser
complete -c git-stripspace -s s -l strip-comments --description 'Skip and remove all lines starting with #.'

