# git-name-rev
# Autogenerated from man page /usr/share/man/man1/git-name-rev.1.gz
# using Deroffing man parser
complete -c git-name-rev -l tags --description 'Do not use branch names, but only tags to name the commits.'
complete -c git-name-rev -l refs --description 'Only use refs whose names match a given shell pattern.'
complete -c git-name-rev -l all --description 'List all commits reachable from all refs.'
complete -c git-name-rev -l stdin --description 'Read from stdin, append "(<rev_name>)" to all s… [See Man Page]'
complete -c git-name-rev -l name-only --description 'Instead of printing both the SHA-1 and the name… [See Man Page]'
complete -c git-name-rev -l no-undefined --description 'Die with error code != 0 when a reference is un… [See Man Page]'
complete -c git-name-rev -l always --description 'Show uniquely abbreviated commit object as fallback.'

