# git-mailsplit
# Autogenerated from man page /usr/share/man/man1/git-mailsplit.1.gz
# using Deroffing man parser
complete -c git-mailsplit -o 'o<directory>' --description 'Directory in which to place the individual messages.'
complete -c git-mailsplit -s b --description 'If any file doesn\\(cqt begin with a From line, … [See Man Page]'
complete -c git-mailsplit -o 'd<prec>' --description 'Instead of the default 4 digits with leading ze… [See Man Page]'
complete -c git-mailsplit -o 'f<nn>' --description 'Skip the first <nn> numbers, for example if -f3… [See Man Page]'
complete -c git-mailsplit -l keep-cr --description 'Do not remove r from lines ending with rn.'

