# git-fast-import
# Autogenerated from man page /usr/share/man/man1/git-fast-import.1.gz
# using Deroffing man parser
complete -c git-fast-import -l date-format --description 'Specify the type of dates the frontend will sup… [See Man Page]'
complete -c git-fast-import -l force --description 'Force updating modified existing branches, even… [See Man Page]'
complete -c git-fast-import -l max-pack-size --description 'Maximum size of each output packfile.'
complete -c git-fast-import -l big-file-threshold --description 'Maximum size of a blob that fast-import will at… [See Man Page]'
complete -c git-fast-import -l depth --description 'Maximum delta depth, for blob and tree deltification.'
complete -c git-fast-import -l active-branches --description 'Maximum number of branches to maintain active at once.'
complete -c git-fast-import -l export-marks --description 'Dumps the internal marks table to <file> when complete.'
complete -c git-fast-import -l import-marks --description 'Before processing any input, load the marks spe… [See Man Page]'
complete -c git-fast-import -l import-marks-if-exists --description 'Like --import-marks but instead of erroring out… [See Man Page]'
complete -c git-fast-import -l relative-marks --description 'After specifying --relative-marks the paths spe… [See Man Page]'
complete -c git-fast-import -l no-relative-marks --description 'Negates a previous --relative-marks.'
complete -c git-fast-import -l cat-blob-fd --description 'Specify the file descriptor that will be writte… [See Man Page]'
complete -c git-fast-import -l done --description 'Require a done command at the end of the stream.'
complete -c git-fast-import -l export-pack-edges --description 'After creating a packfile, print a line of data… [See Man Page]'
complete -c git-fast-import -l quiet --description 'Disable all non-fatal output, making fast-impor… [See Man Page]'
complete -c git-fast-import -l stats --description 'Display some basic statistics about the objects… [See Man Page]'
complete -c git-fast-import -l 'import-marks.' --description 'Inline data format.'
complete -c git-fast-import -l ------------------------------- --description '  # my very first test commit   commit refs/hea… [See Man Page]'
complete -c git-fast-import -l --------------- --description '    active_branches = 1 cur, 5 max pos  clock n… [See Man Page]'
complete -c git-fast-import -l ----------------- --description 'END OF CRASH REPORT TIPS AND TRICKS.'

