# git-remote
# Autogenerated from man page /usr/share/man/man1/git-remote.1.gz
# using Deroffing man parser
complete -c git-remote -s v -l verbose --description 'Be a little more verbose and show remote url after name.'
complete -c git-remote -s f --description 'option, git fetch <name> is run immediately aft… [See Man Page]'
complete -c git-remote -l tags --description 'option, git fetch <name> imports every tag from… [See Man Page]'
complete -c git-remote -l no-tags --description 'option, git fetch <name> does not import tags f… [See Man Page]'
complete -c git-remote -s t --description 'option, instead of the default glob refspec for… [See Man Page]'
complete -c git-remote -s m --description 'option, a symbolic-ref refs/remotes/<name>/HEAD… [See Man Page]'
complete -c git-remote -l mirror --description 'refs/remotes/ namespace, but rather everything … [See Man Page]'
complete -c git-remote -s d --description 'refs/remotes/<name>/HEAD is deleted.'
complete -c git-remote -s a --description 'HEAD, then the symbolic-ref refs/remotes/<name>… [See Man Page]'
complete -c git-remote -l add --description 'set-url.'
complete -c git-remote -l push --description '.'
complete -c git-remote -l delete --description 'show.'
complete -c git-remote -s n --description 'option, the remote heads are not queried first … [See Man Page]'
complete -c git-remote -l dry-run --description 'option, report what branches will be pruned, bu… [See Man Page]'
complete -c git-remote -l prune --description 'option, prune all the remotes that are updated.'

