# git-pack-redundant
# Autogenerated from man page /usr/share/man/man1/git-pack-redundant.1.gz
# using Deroffing man parser
complete -c git-pack-redundant -l all --description 'Processes all packs.'
complete -c git-pack-redundant -l alt-odb --description 'Don\\(cqt require objects present in packs from … [See Man Page]'
complete -c git-pack-redundant -l verbose --description 'Outputs some statistics to stderr.'

