# git-repack
# Autogenerated from man page /usr/share/man/man1/git-repack.1.gz
# using Deroffing man parser
complete -c git-repack -s a --description 'Instead of incrementally packing the unpacked o… [See Man Page]'
complete -c git-repack -s A --description 'Same as -a, unless -d is used.'
complete -c git-repack -s d --description 'After packing, if the newly created packs make … [See Man Page]'
complete -c git-repack -s l --description 'Pass the --local option to git pack-objects.'
complete -c git-repack -s f --description 'Pass the --no-reuse-delta option to git-pack-ob… [See Man Page]'
complete -c git-repack -s F --description 'Pass the --no-reuse-object option to git-pack-o… [See Man Page]'
complete -c git-repack -s q --description 'Pass the -q option to git pack-objects.'
complete -c git-repack -s n --description 'Do not update the server information with git u… [See Man Page]'
complete -c git-repack -l window -l depth --description 'These two options affect how the objects contai… [See Man Page]'
complete -c git-repack -l window-memory --description 'This option provides an additional limit on top… [See Man Page]'
complete -c git-repack -l max-pack-size --description 'Maximum size of each output pack file.'
complete -c git-repack -o 'd.' --description 'git prune leaves behind, but git fsck --full shows as dangling.'
complete -c git-repack -l local --description 'option to git pack-objects.  See git-pack-objects(1).'
complete -c git-repack -l no-reuse-delta --description 'option to git-pack-objects, see git-pack-objects(1).'
complete -c git-repack -l no-reuse-object --description 'option to git-pack-objects, see git-pack-objects(1).'
complete -c git-repack -l 'window;' --description '<n> bytes in memory.'

