# git-annotate
# Autogenerated from man page /usr/share/man/man1/git-annotate.1.gz
# using Deroffing man parser
complete -c git-annotate -s b --description 'Show blank SHA-1 for boundary commits.'
complete -c git-annotate -l root --description 'Do not treat root commits as boundaries.'
complete -c git-annotate -l show-stats --description 'Include additional statistics at the end of blame output.'
complete -c git-annotate -s L --description 'Annotate only the given line range.'
complete -c git-annotate -s l --description 'Show long rev (Default: off).'
complete -c git-annotate -s t --description 'Show raw timestamp (Default: off).'
complete -c git-annotate -s S --description 'Use revisions from revs-file instead of calling… [See Man Page]'
complete -c git-annotate -l reverse --description 'Walk history forward instead of backward.'
complete -c git-annotate -s p -l porcelain --description 'Show in a format designed for machine consumption.'
complete -c git-annotate -l line-porcelain --description 'Show the porcelain format, but output commit in… [See Man Page]'
complete -c git-annotate -l incremental --description 'Show the result incrementally in a format desig… [See Man Page]'
complete -c git-annotate -l encoding --description 'Specifies the encoding used to output author na… [See Man Page]'
complete -c git-annotate -l contents --description 'When <rev> is not specified, the command annota… [See Man Page]'
complete -c git-annotate -l date --description 'The value is one of the following alternatives:… [See Man Page]'
complete -c git-annotate -s M --description 'Detect moved or copied lines within a file.'
complete -c git-annotate -s C --description 'In addition to -M, detect lines moved or copied… [See Man Page]'
complete -c git-annotate -s h --description 'Show help message.'

