# git-help
# Autogenerated from man page /usr/share/man/man1/git-help.1.gz
# using Deroffing man parser
complete -c git-help -s a -l all --description 'Prints all the available commands on the standard output.'
complete -c git-help -s i -l info --description 'Display manual page for the command in the info format.'
complete -c git-help -s m -l man --description 'Display manual page for the command in the man format.'
complete -c git-help -s w -l web --description 'Display manual page for the command in the web (HTML) format.'
complete -c git-help -l 'web.' --description '.'

