# gksudo
# Autogenerated from man page /usr/share/man/man1/gksudo.1.gz
# using Deroffing man parser
complete -c gksudo -l debug -s d --description 'Print information on the screen that might be u… [See Man Page]'
complete -c gksudo -l user -s u --description 'Call <command> as the specified user.'
complete -c gksudo -l disable-grab -s g --description 'Disable the "locking" of the keyboard, mouse, a… [See Man Page]'
complete -c gksudo -l prompt -s P --description 'Ask the user if they want to have their keyboar… [See Man Page]'
complete -c gksudo -l preserve-env -s k --description 'Preserve the current environments, does not set… [See Man Page]'
complete -c gksudo -l login -s l --description 'Make this a login shell.'
complete -c gksudo -l description -s D --description 'Provide a descriptive name for the command to b… [See Man Page]'
complete -c gksudo -l message -s m --description 'Replace the standard message shown to ask for p… [See Man Page]'
complete -c gksudo -l print-pass -s p --description 'Ask gksu to print the password to stdout, just … [See Man Page]'
complete -c gksudo -l su-mode -s w --description 'Force gksu to use su(1) as its backend for runn… [See Man Page]'
complete -c gksudo -l sudo-mode -s S --description 'Force gksu to use sudo(1) as its backend for ru… [See Man Page]'

