# glcells
# Autogenerated from man page /usr/share/man/man6/glcells.6x.gz
# using Deroffing man parser
complete -c glcells -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c glcells -o root --description 'Draw on the root window.'
complete -c glcells -o install --description 'Install a private colormap for the window.'
complete -c glcells -o visual --description 'Specify which visual to use.'
complete -c glcells -o pause --description 'Specifies the pause at the end of the animation… [See Man Page]'
complete -c glcells -o maxcells --description 'Specifies the maximum number of cells on screen… [See Man Page]'
complete -c glcells -o radius --description 'Specifies the radius of the cells.  Default is 40.'
complete -c glcells -o seeds --description 'Specifies the number of cells when animation starts.'
complete -c glcells -o quality --description 'Specifies subdivision quality of the spheres us… [See Man Page]'
complete -c glcells -o minfood --description 'Food is ditributed randomly on the screen (Yes,… [See Man Page]'
complete -c glcells -o maxfood --description 'Food is ditributed randomly on the screen (Yes,… [See Man Page]'
complete -c glcells -o divideage --description 'Specifies the minimum age in frames a cell need… [See Man Page]'
complete -c glcells -o mindist --description 'Specifies the minimum distance between cells.  Default 1. 4.'
complete -c glcells -o delay --description 'How long to pause between frames.   Default is 20000, or 0.'
complete -c glcells -o fps --description 'Display the current frame rate, CPU load, and polygon count.'
complete -c glcells -o wireframe --description 'Draw wireframe only.'
complete -c glcells -o keepold --description 'Dead cells stay on screen.'

