# glib-compile-schemas
# Autogenerated from man page /usr/share/man/man1/glib-compile-schemas.1.gz
# using Deroffing man parser
complete -c glib-compile-schemas -s h -l help --description '.'
complete -c glib-compile-schemas -l targetdir --description '.'
complete -c glib-compile-schemas -l dry-run --description '.'
complete -c glib-compile-schemas -l allow-any-name --description '.'

