# glxinfo
# Autogenerated from man page /usr/share/man/man1/glxinfo.1.gz
# using Deroffing man parser
complete -c glxinfo -s v --description 'Print visuals info in verbose form.'
complete -c glxinfo -s t --description 'Print verbose table.'
complete -c glxinfo -o display --description 'Specify the X display to interrogate.'
complete -c glxinfo -s h --description 'Print usage information.'
complete -c glxinfo -s i --description 'Force an indirect rendering context.'
complete -c glxinfo -s b --description 'Find the "best" visual and print its number.'
complete -c glxinfo -s l --description 'Print interesting OpenGL limits.'

