# gnome-character-map
# Autogenerated from man page /usr/share/man/man1/gnome-character-map.1.gz
# using Deroffing man parser
complete -c gnome-character-map -l font --description 'Font to start with, ex: \'Serif 27\'.'
complete -c gnome-character-map -l display --description 'X display to use.'

