# gnome-screensaver
# Autogenerated from man page /usr/share/man/man1/gnome-screensaver.1.gz
# using Deroffing man parser
complete -c gnome-screensaver -l no-daemon --description 'Don\'t become a daemon.'
complete -c gnome-screensaver -l debug --description 'Enable debugging code.'

