# gpasswd
# Autogenerated from man page /usr/share/man/man1/gpasswd.1.gz
# using Deroffing man parser
complete -c gpasswd -s a -l add --description 'Add the user to the named group.'
complete -c gpasswd -s d -l delete --description 'Remove the user from the named group.'
complete -c gpasswd -s h -l help --description 'Display help message and exit.'
complete -c gpasswd -s r -l remove-password --description 'Remove the password from the named group.'
complete -c gpasswd -s R -l restrict --description 'Restrict the access to the named group.'
complete -c gpasswd -s A -l administrators --description 'Set the list of administrative users.'
complete -c gpasswd -s M -l members --description 'Set the list of group members.'

