# gpg-zip
# Autogenerated from man page /usr/share/man/man1/gpg-zip.1.gz
# using Deroffing man parser
complete -c gpg-zip -s e -l encrypt --description 'Encrypt data.'
complete -c gpg-zip -s d -l decrypt --description 'Decrypt data.'
complete -c gpg-zip -s c -l symmetric --description 'Encrypt with a symmetric cipher using a passphrase.'
complete -c gpg-zip -s s -l sign --description 'Make a signature.  See  gpg (1).'
complete -c gpg-zip -s r -l recipient --description 'Encrypt for user id USER.  See  gpg (1).'
complete -c gpg-zip -s u -l local-user --description 'Use USER as the key to sign with.  See  gpg (1).'
complete -c gpg-zip -l list-archive --description 'List the contents of the specified archive.'
complete -c gpg-zip -s o -l output --description 'Write output to specified file R FILE .'
complete -c gpg-zip -l gpg --description 'Use the specified command instead of  gpg .'
complete -c gpg-zip -l gpg-args --description 'Pass the specified options to  gpg (1).'
complete -c gpg-zip -l tar --description 'Use the specified command instead of  tar .'
complete -c gpg-zip -l tar-args --description 'Pass the specified options to   tar (1).'
complete -c gpg-zip -s h -l help --description 'Output a short usage information.'
complete -c gpg-zip -l cipher-algo --description 'option to gpg (1).'
complete -c gpg-zip -l version --description 'Output the program version.'

