# grap2graph
# Autogenerated from man page /usr/share/man/man1/grap2graph.1.gz
# using Deroffing man parser
complete -c grap2graph -o unsafe --description 'Run   pic (1) and  groff (1) in the `unsafe\' mo… [See Man Page]'
complete -c grap2graph -o format --description 'Specify an output format; the default is PNG (P… [See Man Page]'

