# groupadd
# Autogenerated from man page /usr/share/man/man8/groupadd.8.gz
# using Deroffing man parser
complete -c groupadd -s f -l force --description 'This option causes the command to simply exit w… [See Man Page]'
complete -c groupadd -s g -l gid --description 'The numerical value of the group\\*(Aqs ID.'
complete -c groupadd -s h -l help --description 'Display help message and exit.'
complete -c groupadd -s K -l key --description 'Overrides /etc/login.'
complete -c groupadd -s o -l non-unique --description 'This option permits to add a group with a non-unique GID.'
complete -c groupadd -s p -l password --description 'The encrypted password, as returned by crypt(3).'
complete -c groupadd -s r -l system --description 'Create a system group.'

