# grpck
# Autogenerated from man page /usr/share/man/man8/grpck.8.gz
# using Deroffing man parser
complete -c grpck -s r --description 'Execute the grpck command in read-only mode.'
complete -c grpck -s s --description 'Sort entries in /etc/group and /etc/gshadow by GID.'

