# grub-mkconfig
# Autogenerated from man page /usr/share/man/man8/grub-mkconfig.8.gz
# using Deroffing man parser
complete -c grub-mkconfig -s o -l output --description 'output generated config to FILE [default=stdout].'
complete -c grub-mkconfig -s h -l help --description 'print this message and exit.'
complete -c grub-mkconfig -s v -l version --description 'print the version information and exit REPORTIN… [See Man Page]'

