# grub-fstest
# Autogenerated from man page /usr/share/man/man1/grub-fstest.1.gz
# using Deroffing man parser
complete -c grub-fstest -s c -l diskcount --description 'N input files.'
complete -c grub-fstest -s d -l debug --description 'Set debug environment variable.'
complete -c grub-fstest -s n -l length --description 'Handle N bytes in output file.'
complete -c grub-fstest -s r -l root --description 'Set root device.'
complete -c grub-fstest -s s -l skip --description 'Skip N bytes from output file.'
complete -c grub-fstest -s v -l verbose --description 'Print verbose messages.'
complete -c grub-fstest -s '?' -l help --description 'give this help list.'
complete -c grub-fstest -l usage --description 'give a short usage message.'
complete -c grub-fstest -s V -l version --description 'print program version.'

