# grub-script-check
# Autogenerated from man page /usr/share/man/man1/grub-script-check.1.gz
# using Deroffing man parser
complete -c grub-script-check -s h -l help --description 'display this message and exit.'
complete -c grub-script-check -s V -l version --description 'print version information and exit.'
complete -c grub-script-check -s v -l verbose --description 'print the script as it is being processed REPOR… [See Man Page]'

