# grub-mkpasswd-pbkdf2
# Autogenerated from man page /usr/share/man/man1/grub-mkpasswd-pbkdf2.1.gz
# using Deroffing man parser
complete -c grub-mkpasswd-pbkdf2 -s c -l iteration-count --description 'Number of PBKDF2 iterations.'
complete -c grub-mkpasswd-pbkdf2 -s l -l buflen --description 'Length of generated hash.'
complete -c grub-mkpasswd-pbkdf2 -s s -l salt --description 'Length of salt REPORTING BUGS Report bugs to <bug-grub@gnu.'

