# grub-mklayout
# Autogenerated from man page /usr/share/man/man1/grub-mklayout.1.gz
# using Deroffing man parser
complete -c grub-mklayout -s i -l input --description 'set input filename.  Default is STDIN.'
complete -c grub-mklayout -s o -l output --description 'set output filename.  Default is STDOUT.'
complete -c grub-mklayout -s h -l help --description 'display this message and exit.'
complete -c grub-mklayout -s V -l version --description 'print version information and exit.'
complete -c grub-mklayout -s v -l verbose --description 'print verbose messages.'

