# gsc
# Autogenerated from man page /usr/share/man/man1/gsc.1.gz
# using Deroffing man parser
complete -c gsc -s : --description 'Comma separated list of run-time options.'
complete -c gsc -s e --description 'Evaluate an expression.'
complete -c gsc -s f --description 'Skip initialization file.'
complete -c gsc -s v --description 'Show version of program.'

