# gst-xmllaunch-0
# Autogenerated from man page /usr/share/man/man1/gst-xmllaunch-0.10.1.gz
# using Type1
complete -c gst-xmllaunch-0 -l help --description 'Print help synopsis and available FLAGS.'
complete -c gst-xmllaunch-0 -l silent --description 'Do not output status information.'
complete -c gst-xmllaunch-0 -l exclude -o XTYPE --description 'Do not output status information of TYPE.'
complete -c gst-xmllaunch-0 -l output -o oFILE --description 'Save XML representation of pipeline to FILE and exit.'
complete -c gst-xmllaunch-0 -l gst-info-mask --description 'GStreamer info flags to set (list with --help).'
complete -c gst-xmllaunch-0 -l gst-debug-mask --description 'GStreamer debugging flags to set (list with --help).'
complete -c gst-xmllaunch-0 -l gst-mask --description 'GStreamer info and debugging flags to set (list with --help).'
complete -c gst-xmllaunch-0 -l gst-plugin-spew --description 'GStreamer info flags to set Enable printout of … [See Man Page]'

