# gthumb
# Autogenerated from man page /usr/share/man/man1/gthumb.1.gz
# using Deroffing man parser
complete -c gthumb -s h -l help --description 'Show summary of options.'
complete -c gthumb -l help-all --description 'Show all help options.'
complete -c gthumb -l help-gtk --description 'Show GTK+ options.'
complete -c gthumb -l help-sm-client --description 'Show session management options.'
complete -c gthumb -l help-clutter --description 'Show Clutter options.  APPLICATION OPTIONS.'
complete -c gthumb -s n -l new-window --description 'Open a new window.'
complete -c gthumb -s f -l fullscreen --description 'Start in fullscreen mode.'
complete -c gthumb -s s -l slideshow --description 'Automatically start a slideshow.'
complete -c gthumb -s i -l import-photos --description 'Automatically import digital camera photos.'
complete -c gthumb -s v -l version --description 'Show version.'
complete -c gthumb -l display --description 'X display to use.'
complete -c gthumb -l clutter-display --description 'X display to use.'
complete -c gthumb -l clutter-screen --description 'X screen to use.'

