# gtk-update-icon-cache
# Autogenerated from man page /usr/share/man/man1/gtk-update-icon-cache.1.gz
# using Deroffing man parser
complete -c gtk-update-icon-cache -l force -s f --description 'Overwrite an existing cache file even if it app… [See Man Page]'
complete -c gtk-update-icon-cache -l ignore-theme-index -s t --description 'Don\\*(Aqt check for the existence of \\*(Aqindex.'
complete -c gtk-update-icon-cache -l index-only -s i --description 'Don\\*(Aqt include image data in the cache.'
complete -c gtk-update-icon-cache -l source -s c --description 'Output a C header file declaring a constant nam… [See Man Page]'
complete -c gtk-update-icon-cache -l quiet -s q --description 'Turn off verbose output.'
complete -c gtk-update-icon-cache -l validate -s v --description 'Validate existing icon cache.'

