# gtk-window-decorator
# Autogenerated from man page /usr/share/man/man1/gtk-window-decorator.1.gz
# using Deroffing man parser
complete -c gtk-window-decorator -l minimal --description 'Runs only with minimal window decorations.'
complete -c gtk-window-decorator -l replace --description 'Replaces any running window decorator.'
complete -c gtk-window-decorator -l help --description 'Prints the list of accepted options.'

