# gucharmap
# Autogenerated from man page /usr/share/man/man1/gucharmap.1.gz
# using Deroffing man parser
complete -c gucharmap -l font --description 'Font to start with, ex: \'Serif 27\'.'
complete -c gucharmap -l display --description 'X display to use.'

