# guitarix
# Autogenerated from man page /usr/share/man/man1/guitarix.1.gz
# using Deroffing man parser
complete -c guitarix -s h -l help --description 'Show help options.'
complete -c guitarix -l help-all --description 'Show all help options.'
complete -c guitarix -l help-gtk --description 'GTK configuration options.'
complete -c guitarix -l help-jack --description 'JACK configuration options.'
complete -c guitarix -l help-file --description 'File options.'
complete -c guitarix -l help-debug --description 'Debug options.'
complete -c guitarix -s v -l version --description 'Print version string and exit.'

