# gxditview
# Autogenerated from man page /usr/share/man/man1/gxditview.1.gz
# using Deroffing man parser
complete -c gxditview -o help --description 'This option indicates that a brief summary of t… [See Man Page]'
complete -c gxditview -o page --description 'This option specifies the page number of the do… [See Man Page]'
complete -c gxditview -o backingStore --description 'Redisplay of the  groff intermediate output win… [See Man Page]'
complete -c gxditview -o printCommand --description 'The default command displayed in the dialog box… [See Man Page]'
complete -c gxditview -o resolution --description 'The  groff intermediate output file will be dis… [See Man Page]'
complete -c gxditview -o filename --description 'The default filename displayed in the dialog bo… [See Man Page]'
complete -c gxditview -o bg --description 'This option specifies the color to use for the … [See Man Page]'
complete -c gxditview -o bd --description 'This option specifies the color to use for the … [See Man Page]'
complete -c gxditview -o bw --description 'This option specifies the width in pixels of th… [See Man Page]'
complete -c gxditview -o fg --description 'This option specifies the color to use for displaying text.'
complete -c gxditview -o fn --description 'This option specifies the font to be used for d… [See Man Page]'
complete -c gxditview -o rv --description 'This option indicates that reverse video should… [See Man Page]'
complete -c gxditview -o geometry --description 'This option specifies the preferred size and po… [See Man Page]'
complete -c gxditview -o display --description 'This option specifies the X\\~server to contact.'
complete -c gxditview -s T --description '.'
complete -c gxditview -o rS --description 'is documented in the groff_man (7) man page).  groff \'s option.'
complete -c gxditview -s X --description 'produces intermediate output for the Postscript… [See Man Page]'
complete -c gxditview -o xrm --description 'This option specifies a resource string to be used.'

