# hbf2gf
# Autogenerated from man page /usr/share/man/man1/hbf2gf.1.gz
# using Deroffing man parser
complete -c hbf2gf -s q --description 'makes hbf2gf quiet.  hbf2gf.'
complete -c hbf2gf -s p --description 'is set, no.'
complete -c hbf2gf -s g --description 'is set, no.'
complete -c hbf2gf -s n --description 'if set, the extension is `c.'
complete -c hbf2gf -s t --description '[ -q ] %subfont-name This mode is intended for … [See Man Page]'
complete -c hbf2gf -l version --description 'returns the current version of hbf2gf and the u… [See Man Page]'
complete -c hbf2gf -l help --description 'parameter.'

