# hbpldecode
# Autogenerated from man page /usr/share/man/man1/hbpldecode.1.gz
# using Deroffing man parser
complete -c hbpldecode -s d --description 'Basename of . pbm file for saving decompressed planes.'
complete -c hbpldecode -s h --description 'Print hex file offsets.'
complete -c hbpldecode -s o --description 'Print file offsets.'
complete -c hbpldecode -s D --description 'Set Debug level [0].'

