# hexdump
# Autogenerated from man page /usr/share/man/man1/hexdump.1.gz
# using Darwin man parser
complete -c hexdump -s b --description 'One-byte octal display.'
complete -c hexdump -s c --description 'One-byte character display.'
complete -c hexdump -s C --description 'Canonical hex+ASCII display.'
complete -c hexdump -s d --description 'Two-byte decimal display.'
complete -c hexdump -s e --description 'Specify a format string to be used for displaying data.'
complete -c hexdump -s f --description 'Specify a file that contains one or more newlin… [See Man Page]'
complete -c hexdump -s n --description 'Interpret only length bytes of input.'
complete -c hexdump -s o --description 'Two-byte octal display.'
complete -c hexdump -s s --description 'Skip offset bytes from the beginning of the input.'
complete -c hexdump -s v --description 'Cause hexdump to display all input data.'
complete -c hexdump -s x --description 'Two-byte hexadecimal display.'

