# hp-check
# Autogenerated from man page /usr/share/man/man1/hp-check.1.gz
# using Deroffing man parser
complete -c hp-check -s c -l compile --description 'Run-time check:.'
complete -c hp-check -s r -l run --description 'Compile and run-time checks:.'
complete -c hp-check -s b -l both --description 'Set the logging level:.'
complete -c hp-check -o 'l<level>' -l logging --description '<level>: none, info*, error, warn, debug (*defa… [See Man Page]'
complete -c hp-check -s g -o 'ldebug)' --description 'Output plain text only:.'
complete -c hp-check -s t --description 'This help information:.'
complete -c hp-check -s h -l help --description 'NOTES 1.'

