# hp-makeuri
# Autogenerated from man page /usr/share/man/man1/hp-makeuri.1.gz
# using Deroffing man parser
complete -c hp-makeuri -o 'p<port>' -l port --description 'Show the CUPS URI only (quiet mode):.'
complete -c hp-makeuri -s c -l cups --description 'Show the SANE URI only (quiet mode):.'
complete -c hp-makeuri -s s -l sane --description 'Show the HP Fax URI only (quiet mode):.'
complete -c hp-makeuri -s f -l fax --description 'Set the logging level:.'
complete -c hp-makeuri -o 'l<level>' -l logging --description '<level>: none, info*, error, warn, debug (*defa… [See Man Page]'
complete -c hp-makeuri -s g -o 'ldebug)' --description 'This help information:.'
complete -c hp-makeuri -s h -l help --description 'EXAMPLES USB: $ hp-makeuri 001:002 Network: $ hp-makeuri 66.'

