# hp-plugin
# Autogenerated from man page /usr/share/man/man1/hp-plugin.1.gz
# using Deroffing man parser
complete -c hp-plugin -s u -l gui --description 'Run in interactive mode:.'
complete -c hp-plugin -s i -l interactive --description 'Installation for required printer mode:.'
complete -c hp-plugin -l required --description 'Installation for optional printer mode:.'
complete -c hp-plugin -l optional --description 'Set the language:.'
complete -c hp-plugin -s q -l lang -o 'q?' -l lang --description 'OPTIONS Specify the path to the plugin file:.'
complete -c hp-plugin -s p -l path -l plugin --description 'Set the logging level:.'
complete -c hp-plugin -o 'l<level>' -l logging --description '<level>: none, info*, error, warn, debug (*defa… [See Man Page]'
complete -c hp-plugin -s g -o 'ldebug)' --description 'This help information:.'
complete -c hp-plugin -s h -l help --description 'SEE ALSO hp-setup hp-firmware AUTHOR HPLIP (Hew… [See Man Page]'

