# html2text
# Autogenerated from man page /usr/share/man/man1/html2text.1.gz
# using Deroffing man parser
complete -c html2text -o nometa --description 'By default, Debian version of html2text use \'me… [See Man Page]'
complete -c html2text -o ascii --description 'By default, when -nometa is supplied,  html2tex… [See Man Page]'
complete -c html2text -o utf8 --description 'By default, when -nometa is supplied,  html2tex… [See Man Page]'
complete -c html2text -o check --description 'This option is for diagnostic purposes: The HTM… [See Man Page]'
complete -c html2text -o debug-parser --description 'Let  html2text report on the tokens being shift… [See Man Page]'
complete -c html2text -o debug-scanner --description 'Let  html2text report on each lexical token sca… [See Man Page]'
complete -c html2text -o help --description 'Print command line summary and exit.'
complete -c html2text -o nobs --description 'By default, original  html2text renders underli… [See Man Page]'
complete -c html2text -s o --description 'Write the output to  output-file instead of standard output.'
complete -c html2text -o rcfile --description 'Attempt to read the file specified in  path as RC file.'
complete -c html2text -o style --description 'Style  pretty changes some of the default value… [See Man Page]'
complete -c html2text -o unparse --description 'This option is for diagnostic purposes: Instead… [See Man Page]'
complete -c html2text -o version --description 'Print program version and exit.'
complete -c html2text -o width --description 'By default, html2text formats the HTML document… [See Man Page]'

