# hydrogen
# Autogenerated from man page /usr/share/man/man1/hydrogen.1.gz
# using Deroffing man parser
complete -c hydrogen -l lash-no-start-server --description 'it (LASH 0. 5. 3 and later).'
complete -c hydrogen -s d -l driver --description '.'
complete -c hydrogen -s s -l song --description '.'
complete -c hydrogen -l lash-no-autoresume --description 'from a crash.'
complete -c hydrogen -s n -l nosplash --description '.'
complete -c hydrogen -o 'V[Level]' -l 'verbose[' --description 'Level, if present, may be None, Error, Warning,… [See Man Page]'
complete -c hydrogen -s v -l version --description '.'
complete -c hydrogen -s h -l help --description '.'

