# hyperspace
# Autogenerated from man page /usr/share/man/man1/hyperspace.1.gz
# using Deroffing man parser
complete -c hyperspace -l root --description 'Draw on the root window.'
complete -c hyperspace -l maxfps --description 'Set maximum frame rate.'
complete -c hyperspace -l vsync --description 'Limit redraws to specified number of vertical refreshes.'
complete -c hyperspace -l dpms --description 'Stop rendering new frames if the display is not on.   0 - 1.'
complete -c hyperspace -l speed --description 'Speed of fly through.   1 - 100.   Default: 10.'
complete -c hyperspace -l stars --description 'Number of stars.   0 - 10000.   Default: 1000.'
complete -c hyperspace -l starsize --description 'Size of stars.   1 - 100.   Default: 10.'
complete -c hyperspace -l resolution --description 'Resolution of the goo.   4 - 20.   Default: 10.'
complete -c hyperspace -l depth --description 'Depth of the scene.   1 - 10.   Default: 5.'
complete -c hyperspace -l fov --description 'Field of view.   10 - 150.   Default: 10.'
complete -c hyperspace -l no-shader --description 'Disables use of vertex/fragment shaders, in cas… [See Man Page]'

