# icuinfo
# Autogenerated from man page /usr/share/man/man1/icuinfo.1.gz
# using Deroffing man parser
complete -c icuinfo -s h -s '?' -l help --description 'Print help about usage and exit.'
complete -c icuinfo -s V -l version --description 'Print the version of  icuinfo and exit.'
complete -c icuinfo -s c -l copyright --description 'Embeds the standard ICU copyright into the R output-file .'
complete -c icuinfo -s v -l verbose --description 'Display extra informative messages during execution.'
complete -c icuinfo -s i -l icudatadir --description 'Look for any necessary ICU data files in R directory .'
complete -c icuinfo -s L -l list-plugins --description 'If specified, list and diagnose issues with ICU plugins.'
complete -c icuinfo -s K -l cleanup --description 'Attempt to unload plugins before exiting.'
complete -c icuinfo -s m -l milisecond-time --description 'Print the current UTC time in milliseconds.'

