# id3v2
# Autogenerated from man page /usr/share/man/man1/id3v2.1.gz
# using Deroffing man parser
complete -c id3v2 -s h -l help --description 'Display help and exit.'
complete -c id3v2 -s f -l list-frames --description 'Display all possible frames for id3v2.'
complete -c id3v2 -s L -l list-genres --description 'Lists all id3v1 genres.'
complete -c id3v2 -s v -l version --description 'Display version information and exit.'
complete -c id3v2 -s l -l list --description 'Lists the tag(s) on the file(s).'
complete -c id3v2 -s R -l list-rfc822 --description 'Lists using an rfc822-style format for output.'
complete -c id3v2 -s d -l delete-v2 --description 'Deletes id3v2 tags.'
complete -c id3v2 -s s -l delete-v1 --description 'Deletes id3v1 tags.'
complete -c id3v2 -s D -l delete-all --description 'Deletes both id3v1 and id3v2 tags.'
complete -c id3v2 -s C -l convert --description 'Converts id3v1 tag to id3v2.'
complete -c id3v2 -s a -l artist --description 'Set the artist information.'
complete -c id3v2 -s A -l album --description 'Set the album title information.'
complete -c id3v2 -s t -l song --description 'Set the song title information.'
complete -c id3v2 -s c -l comment --description 'Set the comment information.'
complete -c id3v2 -s g -l genre --description 'Set the genre number.'
complete -c id3v2 -s y -l year --description 'Set the year.'
complete -c id3v2 -s T -l track --description 'Set the track number/(optional) total tracks.'

