# ifconfig
# Autogenerated from man page /usr/share/man/man8/ifconfig.8.gz
# using Deroffing man parser
complete -c ifconfig -s a --description 'display all interfaces which are currently avai… [See Man Page]'
complete -c ifconfig -s s --description 'display a short list (like netstat -i).'
complete -c ifconfig -s v --description 'be more verbose for some error conditions.'

