# install-menu
# Autogenerated from man page /usr/share/man/man1/install-menu.1.gz
# using Deroffing man parser
complete -c install-menu -s h -l help --description 'Show the help message and exit.'
complete -c install-menu -l remove --description 'Remove the menu files instead of generating them.'
complete -c install-menu -s v -l verbose --description 'Output messages about what the program is doing.'

