# install-sgmlcatalog
# Autogenerated from man page /usr/share/man/man8/install-sgmlcatalog.8.gz
# using Deroffing man parser
complete -c install-sgmlcatalog -l remove --description 'Indicates to remove the entry for the package package .'

