# intltool-update
# Autogenerated from man page /usr/share/man/man8/intltool-update.8.gz
# using Deroffing man parser
complete -c intltool-update -l pot --description 'PD Generate po template (. pot) only.'
complete -c intltool-update -l headers --description 'PD Executes intltool-extract(8) to extract stri… [See Man Page]'
complete -c intltool-update -l maintain --description 'PD Search for left out files, which should have… [See Man Page]'
complete -c intltool-update -l report --description 'PD Display a status report for all translations… [See Man Page]'
complete -c intltool-update -l dist --description 'PD Merge  LANGCODE . po with existing PO template.'
complete -c intltool-update -l gettext-package --description 'PD Manually specify PO template file name, inst… [See Man Page]'
complete -c intltool-update -l output-file --description 'PD Manually specify output FILENAME after mergi… [See Man Page]'
complete -c intltool-update -l verbose --description 'PD Display lots of feedback.'
complete -c intltool-update -l version --description 'Show version information.'
complete -c intltool-update -s p --description '.'
complete -c intltool-update -s s --description '.'
complete -c intltool-update -s m --description '.'
complete -c intltool-update -s r --description '.'
complete -c intltool-update -s d --description '.'
complete -c intltool-update -s g --description '.'
complete -c intltool-update -s o --description '.'
complete -c intltool-update -s x --description '.'
complete -c intltool-update -l help --description 'Show usage and basic help information.'

