# invoke-rc
# Autogenerated from man page /usr/share/man/man8/invoke-rc.d.8.gz
# using Deroffing man parser
complete -c invoke-rc -l help --description 'Display usage help.'
complete -c invoke-rc -l quiet --description 'Quiet mode, no error messages are generated.'
complete -c invoke-rc -l force --description 'Tries to run the init script regardless of poli… [See Man Page]'
complete -c invoke-rc -l try-anyway --description 'Tries to run the init script if a non-fatal error is detected.'
complete -c invoke-rc -l disclose-deny --description 'Return status code 101 instead of status code 0… [See Man Page]'
complete -c invoke-rc -l query --description 'Returns one of the status codes 100-106.'
complete -c invoke-rc -l no-fallback --description '.'

