# ipptool
# Autogenerated from man page /usr/share/man/man1/ipptool.1.gz
# using Deroffing man parser
complete -c ipptool -s 4 --description 'Specifies that ipptool must connect to the prin… [See Man Page]'
complete -c ipptool -s 6 --description 'Specifies that ipptool must connect to the prin… [See Man Page]'
complete -c ipptool -s C --description 'Specifies that requests should be sent using the HTTP/1.'
complete -c ipptool -s E --description 'Forces TLS encryption when connecting to the se… [See Man Page]'
complete -c ipptool -s I --description 'Specifies that ipptool will continue past errors.'
complete -c ipptool -s L --description 'Specifies that requests should be sent using the HTTP/1.'
complete -c ipptool -s S --description 'Forces (dedicated) SSL encryption when connecti… [See Man Page]'
complete -c ipptool -s T --description 'Specifies a timeout for IPP requests in seconds.'
complete -c ipptool -s V --description 'Specifies the default IPP version to use: 1. 0, 1. 1, 2. 0, 2.'
complete -c ipptool -s X --description 'Specifies that XML (Apple plist) output is desi… [See Man Page]'
complete -c ipptool -s c --description 'Specifies that CSV (comma-separated values) out… [See Man Page]'
complete -c ipptool -s d --description 'Defines the named variable.'
complete -c ipptool -s f --description 'Defines the default request filename for tests.'
complete -c ipptool -s i --description 'Specifies that the (last) file should be repeat… [See Man Page]'
complete -c ipptool -s l --description 'Specifies that plain text output is desired.'
complete -c ipptool -s n --description 'Specifies that the (last) file should be repeat… [See Man Page]'
complete -c ipptool -s t --description 'Specifies that CUPS test report output is desir… [See Man Page]'
complete -c ipptool -s v --description 'Specifies that all request and response attribu… [See Man Page]'

