# iptables-save
# Autogenerated from man page /usr/share/man/man8/iptables-save.8.gz
# using Deroffing man parser
complete -c iptables-save -s M --description 'Specify the path to the modprobe program.'
complete -c iptables-save -s c -l counters --description 'include the current values of all packet and by… [See Man Page]'
complete -c iptables-save -s t -l table --description 'restrict output to only one table.'

