# irqbalance
# Autogenerated from man page /usr/share/man/man1/irqbalance.1.gz
# using Type1
complete -c irqbalance -l oneshot --description 'Causes irqbalance to be run once, after which the daemon exits.'

