# isadump
# Autogenerated from man page /usr/share/man/man8/isadump.8.gz
# using Deroffing man parser
complete -c isadump -s f --description 'Enable flat address space mode.'
complete -c isadump -s y --description 'Disable interactive mode.'
complete -c isadump -s k --description 'Specify a comma-separated list of bytes to send… [See Man Page]'
complete -c isadump -s W --description 'Perform 16-bit reads.'
complete -c isadump -s L --description 'Perform 32-bit reads.'

