# isql
# Autogenerated from man page /usr/share/man/man1/isql.1.gz
# using Deroffing man parser
complete -c isql -s b --description 'Batch mode.  It will not do any prompting.'
complete -c isql -o dx --description 'Delimit columns with x.'
complete -c isql -o x0xXX --description 'Delimit columns with XX, where XX is in hex.'
complete -c isql -s w --description 'Wrap results in an HTML table.'
complete -c isql -s c --description 'Print column names on first row.'
complete -c isql -o mn --description 'Limit column display width to n.'
complete -c isql -s v --description 'Verbose output.'
complete -c isql -l version --description 'This prints the version.  EXAMPLES.'

