# jack-dssi-host
# Autogenerated from man page /usr/share/man/man1/jack-dssi-host.1.gz
# using Deroffing man parser
complete -c jack-dssi-host -s v --description 'Verbose mode.'
complete -c jack-dssi-host -s a --description 'Disable automatic connection of outputs to JACK… [See Man Page]'
complete -c jack-dssi-host -s n --description 'Disable automatic starting of plugin user interfaces (UIs).'
complete -c jack-dssi-host -s p --description 'The project directory to pass to both plugin and UI.'
complete -c jack-dssi-host -s c --description 'The client name to use for ALSA and JACK.'
complete -c jack-dssi-host -o '<i>' --description 'Number of instances of the following plugin to … [See Man Page]'

