# jack_metro
# Autogenerated from man page /usr/share/man/man1/jack_metro.1.gz
# using Deroffing man parser
complete -c jack_metro -s n -l name --description 'br Specify a name for this instance of the metronome.'
complete -c jack_metro -s f -l frequency --description 'br Define the frequency of the "tick" in Hz.'
complete -c jack_metro -s D -l duration --description 'br Define the duration of the "tick" in milliseconds.'
complete -c jack_metro -s a -l attack --description 'br Define the duration of the attack phase of t… [See Man Page]'
complete -c jack_metro -s d -l decay --description 'br Define the duration of the decay phase of th… [See Man Page]'
complete -c jack_metro -l b -l bpm --description '.'

