# javaws
# Autogenerated from man page /usr/share/man/man1/javaws.1.gz
# using Deroffing man parser
complete -c javaws -o about --description 'Shows a sample application that can be used to … [See Man Page]'
complete -c javaws -o viewer --description 'Shows the trusted certificate viewer.'
complete -c javaws -o basedir --description 'Directory where the cache and certificates to b… [See Man Page]'
complete -c javaws -o arg --description 'Adds an application argument before launching.'
complete -c javaws -o param --description 'Adds an applet parameter before launching.'
complete -c javaws -o property --description 'Sets a system property before launching.'
complete -c javaws -o update --description 'Update check if seconds since last checked.'
complete -c javaws -o license --description 'Display the GPL license and exit.'
complete -c javaws -o verbose --description 'Enable verbose output.  Very useful in debugging.'
complete -c javaws -o nosecurity --description 'Disables the secure runtime environment.'
complete -c javaws -o noupdate --description 'Disables checking for updates.'
complete -c javaws -o headless --description 'Disables download window, other UIs.'
complete -c javaws -o strict --description 'Enables strict checking of JNLP file format.'
complete -c javaws -o umask --description 'Sets the umask for files created by an application.'
complete -c javaws -o Xnofork --description 'Do not create another JVM, even if the JNLP fil… [See Man Page]'
complete -c javaws -o Jjava-option --description 'This passes along java-option to the java binar… [See Man Page]'
complete -c javaws -o help --description 'Print a help message and exit.'

