# jpegtopnm
# Autogenerated from man page /usr/share/man/man1/jpegtopnm.1.gz
# using Deroffing man parser
complete -c jpegtopnm -o dct --description 'Use integer DCT method (default).'
complete -c jpegtopnm -o nosmooth --description 'Use a faster, lower-quality upsampling routine.'
complete -c jpegtopnm -o maxmemory --description 'Set limit on the amount of memory   jpegtopnm u… [See Man Page]'
complete -c jpegtopnm -o notadobe --description 'There are two variations on the CMYK (and likew… [See Man Page]'
complete -c jpegtopnm -o dumpexif --description 'Print the interpreted contents of any Exif head… [See Man Page]'
complete -c jpegtopnm -o exif --description 'Extract the contents of the EXIF header from th… [See Man Page]'
complete -c jpegtopnm -o comments --description 'Print any comments in the input file to the Sta… [See Man Page]'
complete -c jpegtopnm -o verbose --description 'Print details about the conversion to the Standard Error file.'
complete -c jpegtopnm -o adobe --description '.'
complete -c jpegtopnm -o tracelevel --description 'Turn on the JPEG library\'s trace messages to th… [See Man Page]'

