# jrunscript
# Autogenerated from man page /usr/share/man/man1/jrunscript.1.gz
# using Type1
complete -c jrunscript -o classpath --description 'Specify where to find the user\'s .'
complete -c jrunscript -o cp --description 'This is a synonym for -classpath \\f2path.'
complete -c jrunscript -o Dname --description 'Set a Java system property.'
complete -c jrunscript -o 'J<flag>' --description 'Pass <flag> directly to the Java virtual machin… [See Man Page]'
complete -c jrunscript -s l --description 'Use the specified scripting language.'
complete -c jrunscript -s e --description 'Evaluate the given script.'
complete -c jrunscript -o encoding --description 'Specify the character encoding used while reading script files.'
complete -c jrunscript -s f --description 'Evaluate the given script file (batch mode).'
complete -c jrunscript -o help --description 'Output help message and exit.'
complete -c jrunscript -s '?' --description 'Output help message and exit.'

