# jstat
# Autogenerated from man page /usr/share/man/man1/jstat.1.gz
# using Type1
complete -c jstat -o help --description 'Display help message.'
complete -c jstat -o version --description 'Display version information.'
complete -c jstat -o options --description 'Display list of statistics options.'
complete -c jstat -o statOption --description 'Determines the statistics information that \\f3jstat displays.'
complete -c jstat -s h --description 'Display a column header every \\f2n samples (out… [See Man Page]'
complete -c jstat -s t --description 'Display a timestamp column as the first column of output.'

