# kcookiejar4
# Autogenerated from man page /usr/share/man/man8/kcookiejar4.8.gz
# using Deroffing man parser
complete -c kcookiejar4 -l author --description '.'
complete -c kcookiejar4 -l help --description '.'
complete -c kcookiejar4 -l help-all --description '.'
complete -c kcookiejar4 -l help-kde --description '.'
complete -c kcookiejar4 -l help-qt --description '.'
complete -c kcookiejar4 -l license --description '.'
complete -c kcookiejar4 -o v--version --description '.'
complete -c kcookiejar4 -l shutdown --description '.'
complete -c kcookiejar4 -l remove --description '.'
complete -c kcookiejar4 -l remove-all --description '.'
complete -c kcookiejar4 -l reaload-config --description '.'

