# kded4
# Autogenerated from man page /usr/share/man/man8/kded4.8.gz
# using Deroffing man parser
complete -c kded4 -l author --description '.'
complete -c kded4 -l help --description '.'
complete -c kded4 -l help-all --description '.'
complete -c kded4 -l help-kde --description '.'
complete -c kded4 -l help-qt --description '.'
complete -c kded4 -l license --description '.'
complete -c kded4 -s v -l version --description '.'
complete -c kded4 -l check --description '.'

