# kompare
# Autogenerated from man page /usr/share/man/man1/kompare.1.gz
# using Deroffing man parser
complete -c kompare -s b --description 'Blends diff into URL.'
complete -c kompare -s c --description 'Compares URL1 with URL2.'
complete -c kompare -s n --description 'Used with -o to stop Kompare from checking for … [See Man Page]'
complete -c kompare -s o --description 'Opens the given diff file.'

