# krita
# Autogenerated from man page /usr/share/man/man1/krita.1.gz
# using Deroffing man parser
complete -c krita -l help --description ' Show help about options.'
complete -c krita -l help-qt --description ' Show Qt specific options.'
complete -c krita -l help-kde --description ' Show KDE specific options.'
complete -c krita -l help-all --description ' Show all options.'
complete -c krita -l author --description ' Show author information.'
complete -c krita -s v -l version --description ' Show version information.'
complete -c krita -l license --description '.'

