# kross
# Autogenerated from man page /usr/share/man/man1/kross.1.gz
# using Deroffing man parser
complete -c kross -l author --description '.'
complete -c kross -l help --description '.'
complete -c kross -l help-all --description '.'
complete -c kross -l help-kde --description '.'
complete -c kross -l help-qt --description '.'
complete -c kross -l license --description '.'
complete -c kross -o v--version --description '.'

