# landscape-sysinfo
# Autogenerated from man page /usr/share/man/man1/landscape-sysinfo.1.gz
# using Deroffing man parser
complete -c landscape-sysinfo -l version --description 'show program\'s version number and exit.'
complete -c landscape-sysinfo -s h -l help --description 'show this help message and exit.'
complete -c landscape-sysinfo -s c -l config --description 'Use config from this file (any command line opt… [See Man Page]'
complete -c landscape-sysinfo -s d -l data-path --description 'The directory to store data files in (default: … [See Man Page]'
complete -c landscape-sysinfo -l sysinfo-plugins --description 'Comma-delimited list of sysinfo plugins to use.'
complete -c landscape-sysinfo -l exclude-sysinfo-plugins --description 'Comma-delimited list of sysinfo plugins to NOT use.'

