# lattice
# Autogenerated from man page /usr/share/man/man1/lattice.1.gz
# using Deroffing man parser
complete -c lattice -l root --description 'Draw on the root window.'
complete -c lattice -l maxfps --description 'Set maximum frame rate.'
complete -c lattice -l vsync --description 'Limit redraws to specified number of vertical refreshes.'
complete -c lattice -l dpms --description 'Stop rendering new frames if the display is not on.   0 - 1.'
complete -c lattice -l preset --description 'Ds 1 - Regular (--regular) 2 - Chainmail (--cha… [See Man Page]'
complete -c lattice -l longitude --description 'Longitudinal divisions of tori.   4 - 100.   Default: 16.'
complete -c lattice -l latitude --description 'Latitudinal divisions of tori.   2 - 100.   Default: 8.'
complete -c lattice -l thick --description 'Thickness of tori.   1 - 100.   Default: 50.'
complete -c lattice -l density --description 'Density.   1 - 100.   Default: 50.'
complete -c lattice -l drawdepth --description 'Depth.   1 - 8.    Default: 4.'
complete -c lattice -l fov --description 'Field of view.   10 - 150.    Default: 90.'
complete -c lattice -l pathrand --description 'Randomness of camera path.   1 - 10.    Default: 7.'
complete -c lattice -l speed --description 'Speed.   1 - 100.    Default: 10.'
complete -c lattice -l texture --description 'Ds 0 - None 1 - Industrial (--industrial) 2 - C… [See Man Page]'
complete -c lattice -l smooth --description 'Smooth surfaces.'
complete -c lattice -l fog --description 'Enable fog.'

