# lbzcat
# Autogenerated from man page /usr/share/man/man1/lbzcat.1.gz
# using Deroffing man parser
complete -c lbzcat -s n --description 'Set the number of (de)compressor threads to R "WTHRS" .'
complete -c lbzcat -s k -l keep --description 'Don\'t remove  FILE operands after successful (de)compression.'
complete -c lbzcat -s c -l stdout --description 'Write output to standard output, even when  FIL… [See Man Page]'
complete -c lbzcat -s t -l test --description 'Test decompression; discard output instead of w… [See Man Page]'
complete -c lbzcat -s d -l decompress --description 'Force decompression over the mode of operation … [See Man Page]'
complete -c lbzcat -s z -l compress --description 'Force compression over the mode of operation se… [See Man Page]'
complete -c lbzcat -s 1 -s 9 --description 'Set the compression block size to 100K .'
complete -c lbzcat -l fast --description 'Alias for  -1 .'
complete -c lbzcat -l best --description 'Alias for  -9 .  This is the default.'
complete -c lbzcat -s f -l force --description 'Open non-regular input files.'
complete -c lbzcat -s v -l verbose --description 'Be more verbose.'
complete -c lbzcat -s S --description 'Print condition variable statistics to standard… [See Man Page]'
complete -c lbzcat -s s -l small -s q -l quiet -l repetitive-fast --description '--repetitive-best Accepted for compatibility wi… [See Man Page]'
complete -c lbzcat -l exponential --description 'Use an alternative block-sorting algorithm -- b… [See Man Page]'
complete -c lbzcat -s h -l help --description 'Print help on command-line usage on standard ou… [See Man Page]'
complete -c lbzcat -s L -l license -s V -l version --description 'Print license and version information on standa… [See Man Page]'

