# lcf
# Autogenerated from man page /usr/share/man/man1/lcf.1.gz
# using Deroffing man parser
complete -c lcf -s h -l help --description 'Print a short usage message.'
complete -c lcf -s n -l no-action --description 'Dry run.'
complete -c lcf -s d -l debug --description 'Set the debug level to the (optional) level  n … [See Man Page]'
complete -c lcf -s v -l verbose --description 'Make the script be very verbose about setting i… [See Man Page]'

