# ldconfig
# Autogenerated from man page /usr/share/man/man8/ldconfig.8.gz
# using Deroffing man parser
complete -c ldconfig -o v--verbose --description 'Verbose mode.'
complete -c ldconfig -s n --description 'Only process directories specified on the command line.'
complete -c ldconfig -s N --description 'Don\'t rebuild the cache.'
complete -c ldconfig -s X --description 'Don\'t update links.'
complete -c ldconfig -s f --description 'Use  conf instead of R /etc/ld. so. conf .'
complete -c ldconfig -s C --description 'Use  cache instead of R /etc/ld. so. cache .'
complete -c ldconfig -s r --description 'Change to and use  root as the root directory.'
complete -c ldconfig -s l --description 'Library mode.  Manually link individual libraries.'
complete -c ldconfig -o p--print-cache --description 'Print the lists of directories and candidate li… [See Man Page]'
complete -c ldconfig -o c--format --description 'Use  FORMAT for the cache file.'
complete -c ldconfig -s i -l ignore-aux-cache --description 'Ignore auxiliary cache file.'
complete -c ldconfig -o '?--help' -l usage --description 'Print usage information.'
complete -c ldconfig -s p --description 'option.'
complete -c ldconfig -s v -l verbose --description 'Verbose mode.'
complete -c ldconfig -l print-cache --description 'Print the lists of directories and candidate li… [See Man Page]'
complete -c ldconfig -s c -l format --description 'Use FORMAT for the cache file.'
complete -c ldconfig -s '?' -l help --description 'Print usage information.'
complete -c ldconfig -s V -l version --description 'Print version and exit.  EXAMPLES.'

