# lightdm
# Autogenerated from man page /usr/share/man/man1/lightdm.1.gz
# using Deroffing man parser
complete -c lightdm -s h -l help --description 'Show help options.'
complete -c lightdm -s c -l config --description 'Use configuration file.'
complete -c lightdm -s d -l debug --description 'Print debugging messages.'
complete -c lightdm -l test-mode --description 'Run as unprivileged user, skipping things that … [See Man Page]'
complete -c lightdm -l pid-file --description 'File to write PID into.'
complete -c lightdm -l xsessions-dir --description 'Directory to load X sessions from.'
complete -c lightdm -l xgreeters-dir --description 'Directory to load X greeters from.'
complete -c lightdm -l log-dir --description 'Directory to write logs to.'
complete -c lightdm -l run-dir --description 'Directory to store running state.'
complete -c lightdm -l cache-dir --description 'Directory to cached information.'
complete -c lightdm -s v -l version --description 'Show release version FILES /etc/lightdm/lightdm.'

