# loadkeys
# Autogenerated from man page /usr/share/man/man1/loadkeys.1.gz
# using Deroffing man parser
complete -c loadkeys -s C --description '(or.'
complete -c loadkeys -l console --description ') option.'
complete -c loadkeys -s d --description '(or.'
complete -c loadkeys -l default --description ') option is given, loadkeys loads a default key… [See Man Page]'
complete -c loadkeys -s c --description '(or.'
complete -c loadkeys -l clearcompose --description ') option is given, in which case the kernel acc… [See Man Page]'
complete -c loadkeys -s s --description '(or.'
complete -c loadkeys -l clearstrings --description ') clears the kernel string table.'
complete -c loadkeys -s m --description '(or.'
complete -c loadkeys -l mktable --description ') option is given loadkeys prints to the standa… [See Man Page]'
complete -c loadkeys -s b --description '(or.'
complete -c loadkeys -l bkeymap --description ') option is given loadkeys prints to the standa… [See Man Page]'
complete -c loadkeys -s u --description '(or.'
complete -c loadkeys -l unicode --description 'switch forces loadkeys to convert all keymaps to Unicode.'
complete -c loadkeys -s h -l help --description 'loadkeys prints its version number and a short … [See Man Page]'
complete -c loadkeys -s q -l quiet --description 'loadkeys suppresses all normal output.'

