# locate
# Autogenerated from man page /usr/share/man/man1/locate.1.gz
# using Deroffing man parser
complete -c locate -s b -l basename --description 'Match only the base name against the specified patterns.'
complete -c locate -s c -l count --description 'Instead of writing file names on standard outpu… [See Man Page]'
complete -c locate -s d -l database --description 'Replace the default database with DBPATH.'
complete -c locate -s e -l existing --description 'Print only entries that refer to files existing… [See Man Page]'
complete -c locate -s L -l follow --description 'When checking whether files exist (if the  --ex… [See Man Page]'
complete -c locate -s h -l help --description 'Write a summary of the available options to sta… [See Man Page]'
complete -c locate -s i -l ignore-case --description 'Ignore case distinctions when matching patterns.'
complete -c locate -s l -l limit -s n --description 'Exit successfully after finding  LIMIT entries.'
complete -c locate -s m -l mmap --description 'Ignored, for compatibility with . SM BSD and . SM GNU locate.'
complete -c locate -s P -l nofollow -s H --description 'When checking whether files exist (if the  --ex… [See Man Page]'
complete -c locate -s 0 -l null --description 'Separate the entries on output using the .'
complete -c locate -s S -l statistics --description 'Write statistics about each read database to st… [See Man Page]'
complete -c locate -s q -l quiet --description 'Write no messages about errors encountered whil… [See Man Page]'
complete -c locate -s r -l regexp --description 'Search for a basic regexp REGEXP.'
complete -c locate -l regex --description 'Interpret all PATTERNs as extended regexps.'
complete -c locate -s s -l stdio --description 'Ignored, for compatibility with . SM BSD and . SM GNU locate.'
complete -c locate -s V -l version --description 'Write information about the version and licence… [See Man Page]'
complete -c locate -s w -l wholename --description 'Match only the whole path name against the specified patterns.'

