# locale-gen
# Autogenerated from man page /usr/share/man/man8/locale-gen.8.gz
# using Type1
complete -c locale-gen -l help --description 'Display an help message and exit.'
complete -c locale-gen -l purge --description 'Remove all existing locales before processing.'
complete -c locale-gen -l no-purge --description 'Do not remove existing locales before processing.'
complete -c locale-gen -l archive --description 'When this option is set, locale data are stored… [See Man Page]'
complete -c locale-gen -l no-archive --description 'When this option is set, locale data are stored… [See Man Page]'

