# logger
# Autogenerated from man page /usr/share/man/man1/logger.1.gz
# using Darwin man parser
complete -c logger -s d --description 'Use datagram (UDP) instead of the default strea… [See Man Page]'
complete -c logger -s i --description 'Log the process ID of the logger process with each line.'
complete -c logger -s f --description 'Log the contents of the specified \\fIfile\\fR.'
complete -c logger -s h --description 'Display a help text and exit.'
complete -c logger -s n --description 'Write to the specified remote syslog server usi… [See Man Page]'
complete -c logger -s P --description 'Use the specified UDP port .  The default port number is 514.'
complete -c logger -s p --description 'Enter the message into the log with the specified priority .'
complete -c logger -s s --description 'Output the message to standard error as well as… [See Man Page]'
complete -c logger -s t --description 'Mark every line to be logged with the specified tag .'
complete -c logger -s u --description 'Write to the specified socket instead of to the… [See Man Page]'
complete -c logger -s V --description 'Display version information and exit.'

