# lp
# Autogenerated from man page /usr/share/man/man1/lp.1.gz
# using Deroffing man parser
complete -c lp -s E --description 'br Forces encryption when connecting to the server.'
complete -c lp -s U --description 'br Specifies the username to use when connecting to the server.'
complete -c lp -s c --description 'br This option is provided for backwards-compatibility only.'
complete -c lp -s d --description 'br Prints files to the named printer.'
complete -c lp -s h --description 'br Chooses an alternate server.'
complete -c lp -s i --description 'br Specifies an existing job to modify.'
complete -c lp -s m --description 'br Sends an email when the job is completed.'
complete -c lp -s n --description 'br Sets the number of copies to print from 1 to 100.'
complete -c lp -s o --description 'br Sets one or more job options.'
complete -c lp -s q --description 'br Sets the job priority from 1 (lowest) to 100 (highest).'
complete -c lp -s s --description 'br Do not report the resulting job IDs (silent mode. ).'
complete -c lp -s t --description 'br Sets the job name.'
complete -c lp -s H --description 'br Specifies when the job should be printed.'
complete -c lp -s P --description '.'

