# lpdomatic
# Autogenerated from man page /usr/share/man/man8/lpdomatic.8.gz
# using Deroffing man parser
complete -c lpdomatic -s v --description 'verbose mode for debugging.'
complete -c lpdomatic -s q --description 'quiet mode - minimal information output.'
complete -c lpdomatic -s P --description '<printer> is the configured printer which shoul… [See Man Page]'
complete -c lpdomatic -l ppd --description 'The PPD file <ppdfile> should be applied for pr… [See Man Page]'
complete -c lpdomatic -s J --description 'The <jobtitle> will be printed in the head line… [See Man Page]'
complete -c lpdomatic -s o --description 'Option settings for this job, do .'
complete -c lpdomatic -l ------------------- --description 'This way you can print directly to your printer, use.'

