# lpoptions
# Autogenerated from man page /usr/share/man/man1/lpoptions.1.gz
# using Deroffing man parser
complete -c lpoptions -s E --description '.'
complete -c lpoptions -s U --description '.'
complete -c lpoptions -s d --description '.'
complete -c lpoptions -s h --description '.'
complete -c lpoptions -s l --description '.'
complete -c lpoptions -s o --description '.'
complete -c lpoptions -s p --description '.'
complete -c lpoptions -s r --description '.'
complete -c lpoptions -s x --description '.'

