# lpr
# Autogenerated from man page /usr/share/man/man1/lpr.1.gz
# using Deroffing man parser
complete -c lpr -s E --description 'br Forces encryption when connecting to the server.'
complete -c lpr -s H --description 'br Specifies an alternate server.'
complete -c lpr -s T --description 'br Sets the job name.'
complete -c lpr -s P --description 'br Prints files to the named printer.'
complete -c lpr -s U --description 'br Specifies an alternate username.'
complete -c lpr -s '#' --description 'br Sets the number of copies to print from 1 to 100.'
complete -c lpr -s h --description 'br Disables banner printing.'
complete -c lpr -s l --description 'br Specifies that the print file is already for… [See Man Page]'
complete -c lpr -s m --description 'br Send an email on job completion.'
complete -c lpr -s o --description 'br Sets a job option.'
complete -c lpr -s p --description 'br Specifies that the print file should be form… [See Man Page]'
complete -c lpr -s q --description 'br Hold job for printing.'
complete -c lpr -s C --description '.'
complete -c lpr -s J --description '.'
complete -c lpr -s r --description '.'

