# lpstat
# Autogenerated from man page /usr/share/man/man1/lpstat.1.gz
# using Deroffing man parser
complete -c lpstat -s E --description 'br Forces encryption when connecting to the server.'
complete -c lpstat -s H --description 'br Shows the server hostname and port.'
complete -c lpstat -s R --description 'br Shows the ranking of print jobs.'
complete -c lpstat -s U --description 'br Specifies an alternate username.'
complete -c lpstat -s W --description 'br Specifies which jobs to show, completed or n… [See Man Page]'
complete -c lpstat -s a --description 'br Shows the accepting state of printer queues.'
complete -c lpstat -s c --description 'br Shows the printer classes and the printers t… [See Man Page]'
complete -c lpstat -s d --description 'br Shows the current default destination.'
complete -c lpstat -s h --description 'br Specifies an alternate server.'
complete -c lpstat -s l --description 'br Shows a long listing of printers, classes, or jobs.'
complete -c lpstat -s o --description 'br Shows the jobs queue on the specified destinations.'
complete -c lpstat -s p --description 'br Shows the printers and whether or not they a… [See Man Page]'
complete -c lpstat -s r --description 'br Shows whether the CUPS server is running.'
complete -c lpstat -s s --description 'br Shows a status summary, including the defaul… [See Man Page]'
complete -c lpstat -s t --description 'br Shows all status information.'
complete -c lpstat -s u --description 'br Shows a list of print jobs queued by the specified users.'
complete -c lpstat -s v --description '.'

