# lsb_release
# Autogenerated from man page /usr/share/man/man1/lsb_release.1.gz
# using Deroffing man parser
complete -c lsb_release -s v -l version --description 'Show the version of the LSB against which your … [See Man Page]'
complete -c lsb_release -s i -l id --description 'Display the distributor\'s ID.'
complete -c lsb_release -s d -l description --description 'Display a description of the currently installed distribution.'
complete -c lsb_release -s r -l release --description 'Display the release number of the currently ins… [See Man Page]'
complete -c lsb_release -s c -l codename --description 'Display the code name of the currently installed distribution.'
complete -c lsb_release -s a -l all --description 'Display all of the above information.'
complete -c lsb_release -s s -l short --description 'Use the short output format for any information displayed.'
complete -c lsb_release -s h -l help --description 'Show summary of options.'

