# lshw
# Autogenerated from man page /usr/share/man/man1/lshw.1.gz
# using Deroffing man parser
complete -c lshw -o version --description 'Displays the version of lshw and exits.'
complete -c lshw -o help --description 'Displays the available command line options and quits.'
complete -c lshw -s X --description 'Launch the X11 GUI (if available).'
complete -c lshw -o html --description 'Outputs the device tree as an HTML page.'
complete -c lshw -o xml --description 'Outputs the device tree as an XML tree.'
complete -c lshw -o json --description 'Outputs the device tree as a JSON object (JavaS… [See Man Page]'
complete -c lshw -o short --description 'Outputs the device tree showing hardware paths,… [See Man Page]'
complete -c lshw -o businfo --description 'Outputs the device list showing bus information… [See Man Page]'
complete -c lshw -o dump --description 'Dump collected information into a file (SQLite database).'
complete -c lshw -o class --description 'Only show the given class of hardware.'
complete -c lshw -s C --description 'Alias for -class class.'
complete -c lshw -o enable --description '.'
complete -c lshw -o disable --description 'Enables or disables a test.'
complete -c lshw -o quiet --description 'Don\'t display status.'
complete -c lshw -o sanitize --description 'Remove potentially sensitive information from o… [See Man Page]'
complete -c lshw -o numeric --description 'Also display numeric IDs (for PCI and USB devices).'

