# lupdate
# Autogenerated from man page /usr/share/man/man1/lupdate.1.gz
# using Deroffing man parser
complete -c lupdate -o disable-heuristic --description 'Disable the named merge heuristic.'
complete -c lupdate -o extensions --description 'Process files with the given extensions only.'
complete -c lupdate -o help --description 'Display the usage and exit.'
complete -c lupdate -o locations --description 'Specify/override how source code references are… [See Man Page]'
complete -c lupdate -o no-obsolete --description 'Drop all obsolete strings.'
complete -c lupdate -o no-recursive --description 'Do not recursively scan the following directories.'
complete -c lupdate -o no-sort --description 'Do not sort contexts in . ts files.'
complete -c lupdate -o pluralonly --description 'Only include plural form messages.'
complete -c lupdate -o pro --description 'Name of a . pro file.  Useful for files with .'
complete -c lupdate -o recursive --description 'Recursively scan the following directories.'
complete -c lupdate -o silent --description 'Don\'t explain what is being done.'
complete -c lupdate -o source-language --description 'Specify/override the language of the source strings.'
complete -c lupdate -o target-language --description 'Specify/override the language of the translation.'
complete -c lupdate -o version --description 'Display the version of lupdate and exit.'

