# lxterm
# Autogenerated from man page /usr/share/man/man1/lxterm.1.gz
# using Deroffing man parser
complete -c lxterm -o class --description '.'
complete -c lxterm -o k8 --description 'and.'
complete -c lxterm -o u8 --description 'options should not be specified because they ar… [See Man Page]'

