# macptopbm
# Autogenerated from man page /usr/share/man/man1/macptopbm.1.gz
# using Deroffing man parser
complete -c macptopbm -o extraskip --description 'This flag is to get around a problem with some … [See Man Page]'

