# mail-unlock
# Autogenerated from man page /usr/share/man/man1/mail-unlock.1.gz
# using Deroffing man parser
complete -c mail-unlock -s q -l quiet --description '.'
complete -c mail-unlock -s v -l verbose --description '.'
complete -c mail-unlock -s l -l lock-name --description '.'
complete -c mail-unlock -s p -l use-pid --description '.'
complete -c mail-unlock -s o -l oneshot --description '.'
complete -c mail-unlock -s r -l retry --description '.'

