# mail-lock
# Autogenerated from man page /usr/share/man/man1/mail-lock.1.gz
# using Deroffing man parser
complete -c mail-lock -s q -l quiet --description '.'
complete -c mail-lock -s v -l verbose --description '.'
complete -c mail-lock -s l -l lock-name --description '.'
complete -c mail-lock -s p -l use-pid --description '.'
complete -c mail-lock -s o -l oneshot --description '.'
complete -c mail-lock -s r -l retry --description '.'

