# makeindex
# Autogenerated from man page /usr/share/man/man1/makeindex.1.gz
# using Deroffing man parser
complete -c makeindex -s c --description 'Compress intermediate blanks (ignoring leading … [See Man Page]'
complete -c makeindex -s g --description 'Employ German word ordering in the index, in ac… [See Man Page]'
complete -c makeindex -s i --description 'Take input from R stdin .'
complete -c makeindex -s l --description 'Letter ordering; by default, word ordering is u… [See Man Page]'
complete -c makeindex -s o --description 'Employ  ind as the output index file.'
complete -c makeindex -s p --description 'Set the starting page number of the output inde… [See Man Page]'
complete -c makeindex -s q --description 'Quiet mode; send no messages to R stderr .'
complete -c makeindex -s r --description 'Disable implicit page range formation; page ran… [See Man Page]'
complete -c makeindex -s s --description 'Employ  sty as the style file (no default).'
complete -c makeindex -s t --description 'Employ  log as the transcript file.'
complete -c makeindex -s L --description 'sort based on locale settings.  Not available on all systems.'
complete -c makeindex -s T --description 'special support for Thai documents.'
complete -c makeindex -o ms --description 'macros (note that at some sites, this macro sho… [See Man Page]'

