# mandb
# Autogenerated from man page /usr/share/man/man8/mandb.8.gz
# using Deroffing man parser
complete -c mandb -s d -l debug --description 'Print debugging information.'
complete -c mandb -s q -l quiet --description 'Produce no warnings.'
complete -c mandb -s s -l no-straycats --description 'Do not spend time looking for or adding informa… [See Man Page]'
complete -c mandb -s p -l no-purge --description 'Do not spend time checking for deleted manual p… [See Man Page]'
complete -c mandb -s c -l create --description 'By default,   mandb will try to update any prev… [See Man Page]'
complete -c mandb -s u -l user-db --description 'Create user databases only, even with write per… [See Man Page]'
complete -c mandb -s t -l test --description 'Perform correctness checks on manual pages in t… [See Man Page]'
complete -c mandb -s f -l filename --description 'Update only the entries for the given filename.'
complete -c mandb -s C -l config-file --description 'Use this user configuration file rather than th… [See Man Page]'
complete -c mandb -s h -l help --description 'Show the usage message, then exit.'
complete -c mandb -l 'no-purge.' --description 'This may be necessary if a database becomes cor… [See Man Page]'
complete -c mandb -s V -l version --description 'Show the version, then exit.  EXIT STATUS.'

