# mcedit
# Autogenerated from man page /usr/share/man/man1/mcedit.1.gz
# using Deroffing man parser
complete -c mcedit -s b --description 'Force black and white display.'
complete -c mcedit -s c --description 'Force ANSI color mode on terminals that don\'t s… [See Man Page]'
complete -c mcedit -s C --description 'Specify a different color set.'
complete -c mcedit -s d --description 'Disable mouse support.'
complete -c mcedit -s f --description 'Display the compiled-in search path for GNU Mid… [See Man Page]'
complete -c mcedit -s t --description 'Force using termcap database instead of terminfo.'
complete -c mcedit -s V --description 'Display the version of the program.'
complete -c mcedit -s x --description 'Force xterm mode.'

