# mcview
# Autogenerated from man page /usr/share/man/man1/mcview.1.gz
# using Deroffing man parser
complete -c mcview -s b --description 'Force black and white display.'
complete -c mcview -s c --description 'Force color mode on terminals where  mcview def… [See Man Page]'
complete -c mcview -s C --description 'Specify a different color set.'
complete -c mcview -s d --description 'Disable mouse support.'
complete -c mcview -s f --description 'Display the compiled-in search paths for Midnig… [See Man Page]'
complete -c mcview -s t --description 'Used only if the code was compiled with S-Lang … [See Man Page]'
complete -c mcview -s V --description 'Displays the version of the program.'
complete -c mcview -s x --description 'Forces xterm mode.'

