# mdatopbm
# Autogenerated from man page /usr/share/man/man1/mdatopbm.1.gz
# using Deroffing man parser
complete -c mdatopbm -s a --description 'Output the PBM in ASCII rather than binary.'
complete -c mdatopbm -s d --description 'Double the height of the output file, to compen… [See Man Page]'
complete -c mdatopbm -s i --description 'Invert the colours used.'

