# mediainfo
# Autogenerated from man page /usr/share/man/man1/mediainfo.1.gz
# using Type1
complete -c mediainfo -l Help -s h --description 'Display help and exit.'
complete -c mediainfo -l Help-Inform --description 'Display help for --Inform option.'
complete -c mediainfo -l Help-AnOption --description 'Display help for \\*(L"AnOption\\*(R".'
complete -c mediainfo -l Version --description 'Display MediaInfo version and exit.'
complete -c mediainfo -l Full -s f --description 'Full information Display (all internal tags).'
complete -c mediainfo -l Output --description 'Full information Display with \\s-1HTML\\s0 tags.'
complete -c mediainfo -l Inform --description 'Template defined information display.'
complete -c mediainfo -l Info-Parameters --description 'Display list of --Inform parameters.'
complete -c mediainfo -l Language --description 'Dislpay non-translated unique identifiers (internal text).'

