# metaflac
# Autogenerated from man page /usr/share/man/man1/metaflac.1.gz
# using Type1
complete -c metaflac -l preserve-modtime --description 'Preserve the original modification time in spite of edits.'
complete -c metaflac -l with-filename --description 'Prefix each output line with the FLAC file name… [See Man Page]'
complete -c metaflac -l no-filename --description 'Do not prefix each output line with the FLAC fi… [See Man Page]'
complete -c metaflac -l no-utf8-convert --description 'Do not convert tags from UTF-8 to local charset, or vice versa.'

