# meterbridge
# Autogenerated from man page /usr/share/man/man1/meterbridge.1.gz
# using Deroffing man parser
complete -c meterbridge -s r --description 'Use rev-level as the reverence level for 0db on the meter.'
complete -c meterbridge -s c --description 'number of columns that are used for displaying several meters.'
complete -c meterbridge -s n --description 'Use jackname as identifier with the JACK system.'
complete -c meterbridge -s t --description 'Use the one of the following meter types:      … [See Man Page]'

