# mf
# Autogenerated from man page /usr/share/man/man1/mf.1.gz
# using Deroffing man parser
complete -c mf -o base --description 'Use  base as the name of the base to be used, i… [See Man Page]'
complete -c mf -o file-line-error --description 'Print error messages in the form  file:line:err… [See Man Page]'
complete -c mf -o no-file-line-error --description 'Disable printing error messages in the  file:line:error style.'
complete -c mf -o file-line-error-style --description 'This is the old name of the  -file-line-error option.'
complete -c mf -o halt-on-error --description 'Exit with an error code when an error is encoun… [See Man Page]'
complete -c mf -o help --description 'Print help message and exit.'
complete -c mf -o ini --description 'Be  inimf , for dumping bases; this is implicit… [See Man Page]'
complete -c mf -o interaction --description 'Sets the interaction mode.'
complete -c mf -o jobname --description 'Use  name for the job name, instead of deriving… [See Man Page]'
complete -c mf -o kpathsea-debug --description 'Sets path searching debugging flags according to the bitmask.'
complete -c mf -o maketex --description 'Enable . RI mktex fmt , where  fmt must be R mf .'
complete -c mf -o no-maketex --description 'Disable . RI mktex fmt , where  fmt must be R mf .'
complete -c mf -o output-directory --description 'Write output files in  directory instead of the… [See Man Page]'
complete -c mf -o parse-first-line --description 'If the first line of the main input file begins… [See Man Page]'
complete -c mf -o no-parse-first-line --description 'Disable parsing of the first line of the main input file.'
complete -c mf -o progname --description 'Pretend to be program R name .'
complete -c mf -o recorder --description 'Enable the filename recorder.'
complete -c mf -o translate-file --description 'Use the  tcxname translation table.'
complete -c mf -o version --description '.'

