# mkdosfs
# Autogenerated from man page /usr/share/man/man8/mkdosfs.8.gz
# using Deroffing man parser
complete -c mkdosfs -s a --description 'Normally, for any filesystem except very small … [See Man Page]'
complete -c mkdosfs -s A --description 'Use Atari variation of the MS-DOS file system.'
complete -c mkdosfs -s b --description 'Selects the location of the backup boot sector for FAT32.'
complete -c mkdosfs -s c --description 'Check the device for bad blocks before creating… [See Man Page]'
complete -c mkdosfs -s C --description 'Create the file given as device on the command … [See Man Page]'
complete -c mkdosfs -s f --description 'Specify the number of file allocation tables in… [See Man Page]'
complete -c mkdosfs -s F --description 'Specifies the type of file allocation tables us… [See Man Page]'
complete -c mkdosfs -s h --description 'Select the number of hidden sectors in the volume.'
complete -c mkdosfs -s i --description 'Sets the volume ID of the newly created file sy… [See Man Page]'
complete -c mkdosfs -s I --description 'It is typical for fixed disk devices to be part… [See Man Page]'
complete -c mkdosfs -s l --description 'Read the bad blocks list from R filename .'
complete -c mkdosfs -s m --description 'Sets the message the user receives on attempts … [See Man Page]'
complete -c mkdosfs -s n --description 'Sets the volume name (label) of the file system.'
complete -c mkdosfs -s r --description 'Select the number of entries available in the root directory.'
complete -c mkdosfs -s R --description 'Select the number of reserved sectors.'
complete -c mkdosfs -s s --description 'Specify the number of disk sectors per cluster.'
complete -c mkdosfs -s S --description 'Specify the number of bytes per logical sector.'
complete -c mkdosfs -s v --description 'Verbose execution.'

