# mktextfm
# Autogenerated from man page /usr/share/man/man1/mktextfm.1.gz
# using Deroffing man parser
complete -c mktextfm -l destdir --description 'A directory name.'
complete -c mktextfm -l help --description 'Print help message and exit.'
complete -c mktextfm -l version --description '.'

