# mktexfmt
# Autogenerated from man page /usr/share/man/man1/mktexfmt.1.gz
# using Type1
complete -c mktexfmt -l cnffile --description 'specify the configuration file fmtutil should use.'
complete -c mktexfmt -l dolinks --description '(not implemented, just for compatibility).'
complete -c mktexfmt -l fmtdir --description 'set the destination directory for format files … [See Man Page]'
complete -c mktexfmt -l force --description '(not implemented, just for compatibility).'
complete -c mktexfmt -l quiet --description '(not implemented, just for compatibility).'

