# mktexpk
# Autogenerated from man page /usr/share/man/man1/mktexpk.1.gz
# using Deroffing man parser
complete -c mktexpk -l bdpi --description 'Set the base device resolution.'
complete -c mktexpk -l dpi --description 'Generate the font at resolution R num .'
complete -c mktexpk -l help --description 'Print help message and exit.'
complete -c mktexpk -l mag --description 'The \\*(MF magnification that corresponds to the… [See Man Page]'
complete -c mktexpk -l mfmode --description 'The \\*(MF mode to use.'
complete -c mktexpk -l destdir --description 'A directory name.'
complete -c mktexpk -l version --description '.'

