# mktexmf
# Autogenerated from man page /usr/share/man/man1/mktexmf.1.gz
# using Deroffing man parser
complete -c mktexmf -l help --description 'Print help message and exit.'
complete -c mktexmf -l version --description '.'

