# mousetweaks
# Autogenerated from man page /usr/share/man/man1/mousetweaks.1.gz
# using Deroffing man parser
complete -c mousetweaks -l dwell --description 'Automatically perform mouse clicks without usin… [See Man Page]'
complete -c mousetweaks -l ssc --description 'Trigger the secondary mouse button when the pri… [See Man Page]'
complete -c mousetweaks -l dwell-time --description 'Time to keep the pointer motionless before a dw… [See Man Page]'
complete -c mousetweaks -l ssc-time --description 'Time to hold the primary mouse button before a … [See Man Page]'
complete -c mousetweaks -s m -l dwell-mode --description 'Select a dwell mode.'
complete -c mousetweaks -s c -l show-ctw --description 'Show the click-type window.'
complete -c mousetweaks -s t -l threshold --description 'Ignore small pointer movements.  Range: 0 - 30 pixels.'
complete -c mousetweaks -s g -l geometry --description 'Size and position of the click-type window.'
complete -c mousetweaks -s s -l shutdown --description 'Stop the mousetweaks daemon.'
complete -c mousetweaks -l daemonize --description 'Start mousetweaks in the background, ie.'
complete -c mousetweaks -l login --description 'Start mousetweaks in login mode.'

