# mysql_install_db
# Autogenerated from man page /usr/share/man/man1/mysql_install_db.1.gz
# using Deroffing man parser
complete -c mysql_install_db -l user --description 'option to indicate the user name that mysqld will run as.'
complete -c mysql_install_db -l basedir --description 'or.'
complete -c mysql_install_db -l datadir --description 'if mysql_install_db does not use the correct lo… [See Man Page]'
complete -c mysql_install_db -l bootstrap --description 'and.'
complete -c mysql_install_db -l skip-grant-tables --description 'options.'
complete -c mysql_install_db -l ldata --description '.'
complete -c mysql_install_db -l force --description '.'
complete -c mysql_install_db -l rpm --description '.'
complete -c mysql_install_db -l skip-name-resolve --description '.'
complete -c mysql_install_db -l srcdir --description '.'
complete -c mysql_install_db -l verbose --description '.'
complete -c mysql_install_db -l windows --description '.'

