# namei
# Autogenerated from man page /usr/share/man/man1/namei.1.gz
# using Deroffing man parser
complete -c namei -s l -l long --description 'Use the long listing format (same as -m -o -v).'
complete -c namei -s m -l modes --description 'Show the mode bits of each file type in the sty… [See Man Page]'
complete -c namei -s o -l owners --description 'Show owner and group name of each file.'
complete -c namei -s n -l nosymlinks --description 'Don\'t follow symlinks.'
complete -c namei -s v -l vertical --description 'Vertically align the modes and owners.'
complete -c namei -s x -l mountpoints --description 'Show mountpoint directories with a \'D\' rather than a \'d\'.'
complete -c namei -s h -l help --description 'Output help text and exit.'
complete -c namei -s V -l version --description 'Output version information and exit.'

