# nautilus-sendto
# Autogenerated from man page /usr/share/man/man1/nautilus-sendto.1.gz
# using Deroffing man parser
complete -c nautilus-sendto -s '?' -l help --description 'Show a help message listing all the options and their meanings.'

