# nepomukserver
# Autogenerated from man page /usr/share/man/man8/nepomukserver.8.gz
# using Deroffing man parser
complete -c nepomukserver -l author --description '.'
complete -c nepomukserver -l help --description '.'
complete -c nepomukserver -l help-all --description '.'
complete -c nepomukserver -l help-kde --description '.'
complete -c nepomukserver -l help-qt --description '.'
complete -c nepomukserver -l license --description '.'
complete -c nepomukserver -s v -l version --description '.'

