# normalize-mp3
# Autogenerated from man page /usr/share/man/man1/normalize-mp3.1.gz
# using Deroffing man parser
complete -c normalize-mp3 -l ogg --description 'Convert files to OGG, regardless of original format.'
complete -c normalize-mp3 -l mp3 --description 'Convert files to MP3, regardless of original format.'
complete -c normalize-mp3 -l bitrate --description 'Set bitrate of re-encoded file (default 128).'
complete -c normalize-mp3 -l tmpdir --description 'Put temporary WAV files in temp directory TMP.'
complete -c normalize-mp3 -l notags --description 'Do not copy ID3 or OGG tags to the output file .'
complete -c normalize-mp3 -l mp3encode --description 'mp3 encoder.'
complete -c normalize-mp3 -l mp3decode --description 'mp3 decoder.'
complete -c normalize-mp3 -l oggencode --description 'ogg vorbis encoder.'
complete -c normalize-mp3 -l oggdecode --description 'ogg vorbis decoder.'
complete -c normalize-mp3 -s h --description 'Display this help and exit.'
complete -c normalize-mp3 -s V --description 'Display version information and exit.'
complete -c normalize-mp3 -s a --description '.'
complete -c normalize-mp3 -s g --description '.'
complete -c normalize-mp3 -s n --description '.'
complete -c normalize-mp3 -s T --description '.'
complete -c normalize-mp3 -s b --description '.'
complete -c normalize-mp3 -s m --description '.'
complete -c normalize-mp3 -s v --description '.'
complete -c normalize-mp3 -s q --description '.'

