# notify-send
# Autogenerated from man page /usr/share/man/man1/notify-send.1.gz
# using Deroffing man parser
complete -c notify-send -s t -l expire-time --description 'Specifies the timeout in milliseconds at which … [See Man Page]'
complete -c notify-send -s i -l icon --description 'Specifies an icon filename or stock icon to display.'
complete -c notify-send -s c -l category --description 'Specifies the notification category.'
complete -c notify-send -s '?' -l help --description 'Show this help message.'
complete -c notify-send -s h -l hint --description 'Specifies basic extra data to pass.'
complete -c notify-send -s u -l urgency --description 'Specifies the urgency level (low, normal, critical).'

