# ntfsresize
# Autogenerated from man page /usr/share/man/man8/ntfsresize.8.gz
# using Deroffing man parser
complete -c ntfsresize -s c -l check --description 'By using this option ntfsresize will only check… [See Man Page]'
complete -c ntfsresize -s i -l info --description 'By using this option without --expand, ntfsresi… [See Man Page]'
complete -c ntfsresize -s m -l info-mb-only --description 'Like the info option, only print out the shrinkable size in MB.'
complete -c ntfsresize -s s -l size --description 'Resize filesystem to SIZE[k|M|G] bytes by shift… [See Man Page]'
complete -c ntfsresize -s x -l expand --description 'Expand the filesystem to the current partition … [See Man Page]'
complete -c ntfsresize -s f -l force --description 'Forces ntfsresize to proceed with the resize op… [See Man Page]'
complete -c ntfsresize -s n -l no-action --description 'Use this option to make a test run before doing… [See Man Page]'
complete -c ntfsresize -s b -l bad-sectors --description 'Support disks having hardware errors, bad secto… [See Man Page]'
complete -c ntfsresize -s P -l no-progress-bar --description 'Don\'t show progress bars.'
complete -c ntfsresize -s v -l verbose --description 'More output.'
complete -c ntfsresize -s V -l version --description 'Print the version number of  ntfsresize and exit.'
complete -c ntfsresize -l 'info(-mb-only)' --description 'and.'
complete -c ntfsresize -o fv --description 'is equivalent to.'
complete -c ntfsresize -s h -l help --description 'Display help and exit.'

