# ntfsfix
# Autogenerated from man page /usr/share/man/man8/ntfsfix.8.gz
# using Deroffing man parser
complete -c ntfsfix -s b -l clear-bad-sectors --description 'Clear the list of bad sectors.'
complete -c ntfsfix -s d -l clear-dirty --description 'Clear the volume dirty flag if the volume can b… [See Man Page]'
complete -c ntfsfix -s h -l help --description 'Show a list of options with a brief description of each one.'
complete -c ntfsfix -s n -l do-nothing --description 'Do not write anything, just show what would have been done.'
complete -c ntfsfix -o fv --description 'is equivalent to.'
complete -c ntfsfix -s f -s v --description 'Long named options can be abbreviated to any un… [See Man Page]'
complete -c ntfsfix -s V -l version --description 'Show the version number, copyright and license.'

