# ntpdate
# Autogenerated from man page /usr/share/man/man8/ntpdate.8.gz
# using Deroffing man parser
complete -c ntpdate -s a --description 'Enable the authentication function and specify … [See Man Page]'
complete -c ntpdate -s B --description 'Force the time to always be slewed using the ad… [See Man Page]'
complete -c ntpdate -s b --description 'Force the time to be stepped using the settimeo… [See Man Page]'
complete -c ntpdate -s d --description 'Enable the debugging mode, in which ntpdate wil… [See Man Page]'
complete -c ntpdate -s e --description 'Specify the processing delay to perform an auth… [See Man Page]'
complete -c ntpdate -s k --description 'Specify the path for the authentication key fil… [See Man Page]'
complete -c ntpdate -s o --description 'Specify the NTP version for outgoing packets as… [See Man Page]'
complete -c ntpdate -s p --description 'Specify the number of samples to be acquired fr… [See Man Page]'
complete -c ntpdate -s q --description 'Query only - don\'t set the clock.'
complete -c ntpdate -s s --description 'Divert logging output from the standard output … [See Man Page]'
complete -c ntpdate -s t --description 'Specify the maximum time waiting for a server r… [See Man Page]'
complete -c ntpdate -s u --description 'Direct ntpdate to use an unprivileged port for … [See Man Page]'
complete -c ntpdate -s v --description 'Be verbose.'

