# oakdecode
# Autogenerated from man page /usr/share/man/man1/oakdecode.1.gz
# using Deroffing man parser
complete -c oakdecode -s d --description 'Basename of . pbm file for saving decompressed planes.'
complete -c oakdecode -s r --description 'Basename of . jbg file for saving raw planes.'
complete -c oakdecode -s i --description 'Suppress display of image records.'
complete -c oakdecode -s o --description 'Print file offsets.'
complete -c oakdecode -s D --description 'Set Debug level [0].'

