# ocamlyacc
# Autogenerated from man page /usr/share/man/man1/ocamlyacc.1.gz
# using Deroffing man parser
complete -c ocamlyacc -s b --description 'Name the output files R prefix . ml, R prefix . mli, R prefix .'
complete -c ocamlyacc -s q --description 'This option has no effect.'
complete -c ocamlyacc -s v --description 'Generate a description of the parsing tables an… [See Man Page]'
complete -c ocamlyacc -o version --description 'Print version string and exit.'
complete -c ocamlyacc -o vnum --description 'Print short version number and exit.'

