# octave-bug-3
# Autogenerated from man page /usr/share/man/man1/octave-bug-3.2.4.1.gz
# using Deroffing man parser
complete -c octave-bug-3 -s s --description 'Specify a subject line for the bug report.'

