# openvt
# Autogenerated from man page /usr/share/man/man1/openvt.1.gz
# using Deroffing man parser
complete -c openvt -s c --description 'Use the given VT number and not the first available.'
complete -c openvt -s f --description 'Force opening a VT without checking whether it … [See Man Page]'
complete -c openvt -s e --description 'Directly execute the given command, without forking.'
complete -c openvt -s s --description 'Switch to the new VT when starting the command.'
complete -c openvt -s u --description 'Figure out the owner of the current VT, and run… [See Man Page]'
complete -c openvt -s l --description 'Make the command a login shell.'
complete -c openvt -s v --description 'Be a bit more verbose.'
complete -c openvt -s w --description 'wait for command to complete.'

