# optirun
# Autogenerated from man page /usr/share/man/man1/optirun.1.gz
# using Deroffing man parser
complete -c optirun -l failsafe --description 'run a program even if the nvidia card is unavailable.'
complete -c optirun -l no-failsafe --description 'do not run a program if the nvidia card is unavailable.'
complete -c optirun -l no-xorg --description 'do not start secondary X server (implies -b none).'
complete -c optirun -s b -l bridge --description 'acceleration/displaying bridge to use.'
complete -c optirun -s c -l vgl-compress --description 'image compression or transport to use with VirtualGL.'
complete -c optirun -l vgl-options --description 'a space-separated list of command options to be… [See Man Page]'
complete -c optirun -l primus-ldpath --description 'a colon-separated list of paths which are searc… [See Man Page]'
complete -c optirun -s q -l quiet -l silent --description 'supresses all logging messages.'
complete -c optirun -s v -l verbose --description 'increase the verbosity level of log messages.'
complete -c optirun -l debug --description 'show all logging messsages by setting the verbo… [See Man Page]'
complete -c optirun -s C -l config --description 'retrieve settings for Bumblebee from FILE.'
complete -c optirun -s d -l display --description 'find the Bumblebee X server on VDISPLAY.'
complete -c optirun -s l -l ldpath --description 'libraries like libGL.'
complete -c optirun -s s -l socket --description 'use FILENAME for communication with the daemon.'
complete -c optirun -s h -l help --description 'display this help and exit.'
complete -c optirun -l version --description 'output version information and exit EXAMPLES.'

