# orage
# Autogenerated from man page /usr/share/man/man1/orage.1.gz
# using Deroffing man parser
complete -c orage -s v -l version --description 'Print version information and exit.'
complete -c orage -s '?' -l help --description 'Print brief help and exit.'
complete -c orage -s p -l --preferences --description 'Open the preferences setting window.'
complete -c orage -s t -l toggle --description 'Hide orage if it is visible and show it if it is hidden.'
complete -c orage -s a -l --add-foreign --description 'Add a foreign file into orage.'
complete -c orage -s r -l --remove-foreign --description 'Remove foreign file from orage.'

