# pamdeinterlace
# Autogenerated from man page /usr/share/man/man1/pamdeinterlace.1.gz
# using Deroffing man parser
complete -c pamdeinterlace -o takeodd --description 'Take the odd-numbered rows from the input and p… [See Man Page]'
complete -c pamdeinterlace -o takeeven --description 'and.'

