# paplay
# Autogenerated from man page /usr/share/man/man1/paplay.1.gz
# using Deroffing man parser
complete -c paplay -s h -l help --description 'Show help.'
complete -c paplay -l version --description 'Show version information.'
complete -c paplay -s v -l verbose --description 'Enable verbose operation.'
complete -c paplay -s s -l server --description 'Choose the server to connect to.'
complete -c paplay -s d -l device --description 'Specify the symbolic name of the sink to play this file on.'
complete -c paplay -s n -l client-name --description 'Specify the client name paplay shall pass to th… [See Man Page]'
complete -c paplay -l stream-name --description 'Specify the stream name paplay shall pass to th… [See Man Page]'
complete -c paplay -l volume --description 'Specify the initial playback volume to use.'
complete -c paplay -l channel-map --description 'Explicitly choose a channel map when playing back this stream.'

