# paracode
# Autogenerated from man page /usr/share/man/man1/paracode.1.gz
# using Deroffing man parser
complete -c paracode -s t --description '--tables  Use given list of conversion tables, … [See Man Page]'
complete -c paracode -l tables --description '.'
complete -c paracode -s r --description '.'

