# pax11publish
# Autogenerated from man page /usr/share/man/man1/pax11publish.1.gz
# using Deroffing man parser
complete -c pax11publish -s h --description 'Show help.'
complete -c pax11publish -s d --description 'Read the PulseAudio server credentials currentl… [See Man Page]'
complete -c pax11publish -s i --description 'Similar to -d, however dumps them in a Bourne s… [See Man Page]'
complete -c pax11publish -s e --description 'Export the currently locally used sound server,… [See Man Page]'
complete -c pax11publish -s r --description 'Removes the configured PulseAudio configuration… [See Man Page]'
complete -c pax11publish -s D --description 'Connect to the specified X11 display, instead o… [See Man Page]'
complete -c pax11publish -s S --description 'Only valid for -e: export the specified PulseAu… [See Man Page]'
complete -c pax11publish -s O --description 'Only valid for -e: export the specified sink as… [See Man Page]'
complete -c pax11publish -s I --description 'Only valid for -e: export the specified source … [See Man Page]'
complete -c pax11publish -s c --description 'Only valid for -e: export the PulseAudio authen… [See Man Page]'

