# pbmclean
# Autogenerated from man page /usr/share/man/man1/pbmclean.1.gz
# using Deroffing man parser
complete -c pbmclean -o black --description 'or .'
complete -c pbmclean -o white --description 'option).'

