# pbmmake
# Autogenerated from man page /usr/share/man/man1/pbmmake.1.gz
# using Deroffing man parser
complete -c pbmmake -o white --description 'and.'
complete -c pbmmake -o black --description 'this program implements.'
complete -c pbmmake -o gray --description 'This gives a simple 50% gray pattern with 1\'s a… [See Man Page]'

