# pbmtolj
# Autogenerated from man page /usr/share/man/man1/pbmtolj.1.gz
# using Deroffing man parser
complete -c pbmtolj -o resolution --description 'Specifies the resolution of the output device, in dpi.'
complete -c pbmtolj -o float --description 'Suppresses positioning information.'
complete -c pbmtolj -o noreset --description 'Prevents pbmtolj from writing the reset sequenc… [See Man Page]'
complete -c pbmtolj -o packbits --description 'Enables use of TIFF packbits compression.'
complete -c pbmtolj -o delta --description 'Enables use of delta-between-rows compression.'
complete -c pbmtolj -o compress --description 'Enables use of both TIFF packbits, and delta-be… [See Man Page]'
complete -c pbmtolj -o copies --description 'Specifies the the number of copies.  The default is 1.'

