# pcimodules
# Autogenerated from man page /usr/share/man/man8/pcimodules.8.gz
# using Deroffing man parser
complete -c pcimodules -l class -l classmask --description '.'
complete -c pcimodules -l help -s h --description 'Print a help message and exit.  EXAMPLES.'

