# pcre-config
# Autogenerated from man page /usr/share/man/man1/pcre-config.1.gz
# using Deroffing man parser
complete -c pcre-config -l prefix --description 'Writes the directory prefix used in the PCRE in… [See Man Page]'
complete -c pcre-config -l exec-prefix --description 'Writes the directory prefix used in the PCRE in… [See Man Page]'
complete -c pcre-config -l version --description 'Writes the version of PCRE installed to standard output.'
complete -c pcre-config -l libs --description 'Writes to standard output the command line opti… [See Man Page]'
complete -c pcre-config -l libs-posix --description 'Writes to standard output the command line opti… [See Man Page]'
complete -c pcre-config -l cflags --description 'Writes to standard output the command line opti… [See Man Page]'
complete -c pcre-config -l cflags-posix --description 'Writes to standard output the command line opti… [See Man Page]'

