# pdfgrep
# Autogenerated from man page /usr/share/man/man1/pdfgrep.1.gz
# using Deroffing man parser
complete -c pdfgrep -s i -l ignore-case --description 'Ignore case distinctions in both the PATTERN an… [See Man Page]'
complete -c pdfgrep -s H -l with-filename --description 'Print the file name for each match.'
complete -c pdfgrep -s h -l no-filename --description 'Suppress the prefixing of file name on output.'
complete -c pdfgrep -s n -l page-number --description 'Prefix each match with the number of the page w… [See Man Page]'
complete -c pdfgrep -s c -l count --description 'Suppress normal output.'
complete -c pdfgrep -s C -l context --description 'Print at most NUM characters of context around each match.'
complete -c pdfgrep -l color --description 'Surround file names, page numbers and matched t… [See Man Page]'
complete -c pdfgrep -s q -l quiet --description 'Suppress all normal output to stdout.'
complete -c pdfgrep -l help --description 'Print a short summary of the options.'
complete -c pdfgrep -s V -l version --description 'Show version information.'

