# pdfinfo
# Autogenerated from man page /usr/share/man/man1/pdfinfo.1.gz
# using Deroffing man parser
complete -c pdfinfo -s f --description 'Specifies the first page to examine.'
complete -c pdfinfo -s l --description 'Specifies the last page to examine.'
complete -c pdfinfo -o box --description 'Prints the page box bounding boxes: MediaBox, C… [See Man Page]'
complete -c pdfinfo -o meta --description 'Prints document-level metadata.'
complete -c pdfinfo -o enc --description 'Sets the encoding to use for text output.'
complete -c pdfinfo -o listenc --description 'Lits the available encodings.'
complete -c pdfinfo -o opw --description 'Specify the owner password for the PDF file.'
complete -c pdfinfo -o upw --description 'Specify the user password for the PDF file.'
complete -c pdfinfo -s v --description 'Print copyright and version information.'
complete -c pdfinfo -s h --description 'Print usage information.  ( -help and.'
complete -c pdfinfo -l help --description 'are equivalent.'

