# pdfimages
# Autogenerated from man page /usr/share/man/man1/pdfimages.1.gz
# using Deroffing man parser
complete -c pdfimages -s f --description 'Specifies the first page to scan.'
complete -c pdfimages -s l --description 'Specifies the last page to scan.'
complete -c pdfimages -s j --description 'Normally, all images are written as PBM (for mo… [See Man Page]'
complete -c pdfimages -o opw --description 'Specify the owner password for the PDF file.'
complete -c pdfimages -o upw --description 'Specify the user password for the PDF file.'
complete -c pdfimages -s p --description 'Include page numbers in output file names.'
complete -c pdfimages -s q --description 'Don\'t print any messages or errors.'
complete -c pdfimages -s v --description 'Print copyright and version information.'
complete -c pdfimages -s h --description 'Print usage information.  ( -help and.'
complete -c pdfimages -l help --description 'are equivalent.'

