# pfsflip
# Autogenerated from man page /usr/share/man/man1/pfsflip.1.gz
# using Deroffing man parser
complete -c pfsflip -l h -s h --description 'Flip the image horizontally.'
complete -c pfsflip -l v -s v --description '.'

