# pfsgamma
# Autogenerated from man page /usr/share/man/man1/pfsgamma.1.gz
# using Deroffing man parser
complete -c pfsgamma -l gamma -s g --description 'Perform gamma correction (input^(1/gamma)).'
complete -c pfsgamma -l inverse-gamma -s i --description 'Perform inverse gamma correction (input^(gamma)).'
complete -c pfsgamma -l mul -s m --description 'Multiply data by this value before gamma correction.'

