# pfsoutexr
# Autogenerated from man page /usr/share/man/man1/pfsoutexr.1.gz
# using Deroffing man parser
complete -c pfsoutexr -l compression -s c --description 'Use one the the available compression methods: … [See Man Page]'
complete -c pfsoutexr -l keep-xyz --description 'By default, color channels XYZ from pfs stream … [See Man Page]'
complete -c pfsoutexr -l fix-halfmax --description 'The maximum value that can be stored in OpenEXR… [See Man Page]'

