# pfsouthdrhtml
# Autogenerated from man page /usr/share/man/man1/pfsouthdrhtml.1.gz
# using Deroffing man parser
complete -c pfsouthdrhtml -l quality -s q --description 'Quality of the interpolated exposures, from the… [See Man Page]'
complete -c pfsouthdrhtml -l image-dir -s d --description 'Specify where to store the resulting image files.'
complete -c pfsouthdrhtml -l page-template -s p -l image-template -s i --description 'Replaces the template files used to generate an HTML web page.'
complete -c pfsouthdrhtml -l object-output -s o --description 'Store JavaScript objects (hdr_<base_name>) asso… [See Man Page]'
complete -c pfsouthdrhtml -l html-output -s l --description 'Store HTML code that shows HDRHTML viewer for e… [See Man Page]'

