# pfsoutimgmagick
# Autogenerated from man page /usr/share/man/man1/pfsoutimgmagick.1.gz
# using Deroffing man parser
complete -c pfsoutimgmagick -l frames --description 'Range is given in mathlab / octave format:   "s… [See Man Page]'
complete -c pfsoutimgmagick -l srgb -s s --description 'Apply the sRGB non-linearity (approximately 2.'
complete -c pfsoutimgmagick -l quality -s q --description 'Set JPEG/PNG compression level from 1 to 100.  Default 75.'
complete -c pfsoutimgmagick -l bit-depth -s b --description 'Enforce bit-depth (per color channel).'

