# pfspad
# Autogenerated from man page /usr/share/man/man1/pfspad.1.gz
# using Deroffing man parser
complete -c pfspad -l left -s l --description 'Width in pixels of the left border.'
complete -c pfspad -l right -s r --description 'Width in pixels of the right border.'
complete -c pfspad -l top -s t --description 'Height in pixels of the top border.'
complete -c pfspad -l bottom -s b --description 'Height in pixels of the bottom border.'
complete -c pfspad -l width -s W --description 'Width of an output image.'
complete -c pfspad -l height -s H --description 'Height of an output image.'
complete -c pfspad -l R -s R -l G -s G -l B -s B --description 'Color of borders in RGB mode.'
complete -c pfspad -l Y -s Y --description 'Color of borders in luminance mode.'
complete -c pfspad -l help -s h --description 'Print a list of commandline options.  EXAMPLES.'

