# pfssize
# Autogenerated from man page /usr/share/man/man1/pfssize.1.gz
# using Deroffing man parser
complete -c pfssize -l x -s x --description 'New x resolution in pixels.'
complete -c pfssize -l y -s y --description 'New y resolution in pixels.'
complete -c pfssize -l ratio -s r --description 'Resize both width and height using the given ratio.'
complete -c pfssize -l minx -l miny --description 'Make sure that the resulting image has at least… [See Man Page]'
complete -c pfssize -l maxx -l maxy --description 'Make sure that the resulting image has at most … [See Man Page]'
complete -c pfssize -l filter -s f --description '.'

