# pfstag
# Autogenerated from man page /usr/share/man/man1/pfstag.1.gz
# using Deroffing man parser
complete -c pfstag -l set -s s -l add --description 'Change existing or add a new tag of the given name.'
complete -c pfstag -l remove -s r --description 'Remove tag of the given name.'

