# pfstmo_fattal02
# Autogenerated from man page /usr/share/man/man1/pfstmo_fattal02.1.gz
# using Deroffing man parser
complete -c pfstmo_fattal02 -l alpha -s a --description 'Set alpha parameter.'
complete -c pfstmo_fattal02 -l beta -s b --description 'Set beta parameter.'
complete -c pfstmo_fattal02 -l saturation -s s --description 'Amount of color saturation.  Suggested range is 0. 4 to 0. 8.'
complete -c pfstmo_fattal02 -l noise -s n --description 'Reduces gradient amplification value for gradie… [See Man Page]'
complete -c pfstmo_fattal02 -l verbose --description 'Print additional information during program execution.'
complete -c pfstmo_fattal02 -l help --description '.'

