# pg_isready
# Autogenerated from man page /usr/share/man/man1/pg_isready.1.gz
# using Deroffing man parser
complete -c pg_isready -s d -l dbname --description 'Specifies the name of the database to connect to.'
complete -c pg_isready -s h -l host --description 'Specifies the host name of the machine on which… [See Man Page]'
complete -c pg_isready -s p -l port --description 'Specifies the TCP port or the local Unix-domain… [See Man Page]'
complete -c pg_isready -s q -l quiet --description 'Do not display status message.  This is useful when scripting.'
complete -c pg_isready -s t -l timeout --description 'The maximum number of seconds to wait when atte… [See Man Page]'
complete -c pg_isready -s U -l username --description 'Connect to the database as the user username in… [See Man Page]'
complete -c pg_isready -s V -l version --description 'Print the pg_isready version and exit.'
complete -c pg_isready -s '?' -l help --description 'Show help about pg_isready command line arguments, and exit.'

