# pg_resetxlog
# Autogenerated from man page /usr/share/man/man1/pg_resetxlog.1.gz
# using Deroffing man parser
complete -c pg_resetxlog -s f --description '(force) option.'
complete -c pg_resetxlog -s o --description '.'
complete -c pg_resetxlog -s x --description '.'
complete -c pg_resetxlog -s e --description '.'
complete -c pg_resetxlog -s m --description '.'
complete -c pg_resetxlog -s O --description '.'
complete -c pg_resetxlog -s l --description 'options allow the next OID, next transaction ID… [See Man Page]'
complete -c pg_resetxlog -o 'm)' --description 'pg_multixact/offsets under the data directory, … [See Man Page]'
complete -c pg_resetxlog -s n --description '(no operation) option instructs pg_resetxlog to… [See Man Page]'
complete -c pg_resetxlog -s V --description 'and.'
complete -c pg_resetxlog -l version --description 'options print the pg_resetxlog version and exit.  The options.'
complete -c pg_resetxlog -s '?' --description 'and.'
complete -c pg_resetxlog -l help --description 'show supported arguments, and exit.  NOTES.'

