# pg_standby
# Autogenerated from man page /usr/share/man/man1/pg_standby.1.gz
# using Deroffing man parser
complete -c pg_standby -s c --description 'Use cp or copy command to restore WAL files from archive.'
complete -c pg_standby -s d --description 'Print lots of debug logging output on stderr.'
complete -c pg_standby -s k --description 'Remove files from archivelocation so that no mo… [See Man Page]'
complete -c pg_standby -s r --description 'Set the maximum number of times to retry the co… [See Man Page]'
complete -c pg_standby -s s --description 'Set the number of seconds (up to 60, default 5)… [See Man Page]'
complete -c pg_standby -s t --description 'Specify a trigger file whose presence should cause failover.'
complete -c pg_standby -s V -l version --description 'Print the pg_standby version and exit.'
complete -c pg_standby -s w --description 'Set the maximum number of seconds to wait for t… [See Man Page]'
complete -c pg_standby -s '?' -l help --description 'Show help about pg_standby command line arguments, and exit.'
complete -c pg_standby -o 'k)' --description 'archivelocation directory must be writable too.'

