# pg_test_timing
# Autogenerated from man page /usr/share/man/man1/pg_test_timing.1.gz
# using Deroffing man parser
complete -c pg_test_timing -s d -l duration --description 'Specifies the test duration, in seconds.'
complete -c pg_test_timing -s V -l version --description 'Print the pg_test_timing version and exit.'
complete -c pg_test_timing -s '?' -l help --description 'Show help about pg_test_timing command line arg… [See Man Page]'

