# pg_xlogdump
# Autogenerated from man page /usr/share/man/man1/pg_xlogdump.1.gz
# using Deroffing man parser
complete -c pg_xlogdump -s b -l bkp-details --description 'Output detailed information about backup blocks.'
complete -c pg_xlogdump -s e -l end --description 'Stop reading at the specified log position, ins… [See Man Page]'
complete -c pg_xlogdump -s n -l limit --description 'Display the specified number of records, then stop.'
complete -c pg_xlogdump -s p -l path --description 'Directory in which to find log segment files.'
complete -c pg_xlogdump -s r -l rmgr --description 'Only display records generated by the specified… [See Man Page]'
complete -c pg_xlogdump -s s -l start --description 'Log position at which to start reading.'
complete -c pg_xlogdump -s t -l timelime --description 'Timeline from which to read log records.'
complete -c pg_xlogdump -s V -l version --description 'Print the pg_xlogdump version and exit.'
complete -c pg_xlogdump -s x -l xid --description 'Only display records marked with the given TransactionId.'
complete -c pg_xlogdump -s '?' -l help --description 'Show help about pg_xlogdump command line arguments, and exit.'

