# pgmramp
# Autogenerated from man page /usr/share/man/man1/pgmramp.1.gz
# using Deroffing man parser
complete -c pgmramp -o lr --description 'A left to right ramp.'
complete -c pgmramp -o tb --description 'A top to bottom ramp.'
complete -c pgmramp -o rectangle --description 'A rectangular ramp.'
complete -c pgmramp -o ellipse --description 'An elliptical ramp.'

