# pgrep
# Autogenerated from man page /usr/share/man/man1/pgrep.1.gz
# using Deroffing man parser
complete -c pgrep -s c --description 'Suppress normal output; instead print a count o… [See Man Page]'
complete -c pgrep -s d --description 'Sets the string used to delimit each process ID… [See Man Page]'
complete -c pgrep -s f --description 'The pattern is normally only matched against the process name.'
complete -c pgrep -s g --description 'Only match processes in the process group IDs listed.'
complete -c pgrep -s G --description 'Only match processes whose real group ID is listed.'
complete -c pgrep -s l --description 'List the process name as well as the process ID.  (pgrep only.'
complete -c pgrep -s n --description 'Select only the newest (most recently started) … [See Man Page]'
complete -c pgrep -s o --description 'Select only the oldest (least recently started)… [See Man Page]'
complete -c pgrep -s P --description 'Only match processes whose parent process ID is listed.'
complete -c pgrep -s s --description 'Only match processes whose process session ID is listed.'
complete -c pgrep -s t --description 'Only match processes whose controlling terminal is listed.'
complete -c pgrep -s u --description 'Only match processes whose effective user ID is listed.'
complete -c pgrep -s U --description 'Only match processes whose real user ID is listed.'
complete -c pgrep -s v --description 'Negates the matching.'
complete -c pgrep -s x --description 'Only match processes whose name (or command lin… [See Man Page]'
complete -c pgrep -o signal --description 'Defines the signal to send to each matched process.'

