# pixelcity
# Autogenerated from man page /usr/share/man/man1/pixelcity.1.gz
# using Deroffing man parser
complete -c pixelcity -l root --description 'Draw on the root window.'
complete -c pixelcity -l maxfps --description 'Set maximum frame rate.'
complete -c pixelcity -l vsync --description 'Limit redraws to specified number of vertical refreshes.'
complete -c pixelcity -l dpms --description 'Stop rendering new frames if the display is not on.   0 - 1.'
complete -c pixelcity -l effect_none --description 'No scene post processing.'
complete -c pixelcity -l effect_bloom --description 'Apply bloom filter to scene.   Default.'
complete -c pixelcity -l effect_bloom_radial --description 'Apply radial bloom filter to scene.'
complete -c pixelcity -l effect_glass --description 'Ethereal rendering of buildings.'
complete -c pixelcity -l effect_color_cycle --description 'Buildings glow with alternating colors.'
complete -c pixelcity -l wireframe --description 'Render building outlines.'
complete -c pixelcity -l letterbox --description 'Wide screen the scene with letter boxing.'
complete -c pixelcity -l no-fog --description 'Disable distance fog.'

