# pkill
# Autogenerated from man page /usr/share/man/man1/pkill.1.gz
# using Deroffing man parser
complete -c pkill -s c --description 'Suppress normal output; instead print a count o… [See Man Page]'
complete -c pkill -s d --description 'Sets the string used to delimit each process ID… [See Man Page]'
complete -c pkill -s f --description 'The pattern is normally only matched against the process name.'
complete -c pkill -s g --description 'Only match processes in the process group IDs listed.'
complete -c pkill -s G --description 'Only match processes whose real group ID is listed.'
complete -c pkill -s l --description 'List the process name as well as the process ID.  (pgrep only.'
complete -c pkill -s n --description 'Select only the newest (most recently started) … [See Man Page]'
complete -c pkill -s o --description 'Select only the oldest (least recently started)… [See Man Page]'
complete -c pkill -s P --description 'Only match processes whose parent process ID is listed.'
complete -c pkill -s s --description 'Only match processes whose process session ID is listed.'
complete -c pkill -s t --description 'Only match processes whose controlling terminal is listed.'
complete -c pkill -s u --description 'Only match processes whose effective user ID is listed.'
complete -c pkill -s U --description 'Only match processes whose real user ID is listed.'
complete -c pkill -s v --description 'Negates the matching.'
complete -c pkill -s x --description 'Only match processes whose name (or command lin… [See Man Page]'
complete -c pkill -o signal --description 'Defines the signal to send to each matched process.'

