# pm-hibernate
# Autogenerated from man page /usr/share/man/man8/pm-hibernate.8.gz
# using Deroffing man parser
complete -c pm-hibernate -l quirk-dpms-on --description 'This option forces the video hardware to turn o… [See Man Page]'
complete -c pm-hibernate -l quirk-dpms-suspend --description 'This option forces the video hardware to turn o… [See Man Page]'
complete -c pm-hibernate -l quirk-radeon-off --description 'This option forces Radeon hardware to turn off … [See Man Page]'
complete -c pm-hibernate -l quirk-s3-bios --description 'This option calls the video BIOS during S3 resume.'
complete -c pm-hibernate -l quirk-s3-mode --description 'This option initializes the video card into a V… [See Man Page]'
complete -c pm-hibernate -l quirk-vbe-post --description 'This option will attempt to reinitialize the vi… [See Man Page]'
complete -c pm-hibernate -l quirk-vbemode-restore --description 'This option will save and restore the current V… [See Man Page]'
complete -c pm-hibernate -l quirk-vbestate-restore --description 'This option saves and restores some low level h… [See Man Page]'
complete -c pm-hibernate -l quirk-vga-mode-3 --description 'This option will try to force the video card in… [See Man Page]'
complete -c pm-hibernate -l quirk-save-pci --description 'Save the PCI config space for the VGA card.'
complete -c pm-hibernate -l store-quirks-as-lkw --description 'Save the quirks the video adaptor required by p… [See Man Page]'

