# pm-is-supported
# Autogenerated from man page /usr/share/man/man1/pm-is-supported.1.gz
# using Deroffing man parser
complete -c pm-is-supported -l suspend --description 'Test whether suspend is supported.'
complete -c pm-is-supported -l hibernate --description 'Test whether hibernate is supported.'
complete -c pm-is-supported -l suspend-hybrid --description 'Test whether hybrid-suspend is supported.'

