# pnmalias
# Autogenerated from man page /usr/share/man/man1/pnmalias.1.gz
# using Deroffing man parser
complete -c pnmalias -o bgcolor --description 'colorb,.'
complete -c pnmalias -o fgcolor --description 'colorf.'
complete -c pnmalias -o bonly --description '.'
complete -c pnmalias -o fonly --description '.'
complete -c pnmalias -o balias --description '.'
complete -c pnmalias -o falias --description '.'
complete -c pnmalias -o weight --description 'w.'

