# pnmarith
# Autogenerated from man page /usr/share/man/man1/pnmarith.1.gz
# using Deroffing man parser
complete -c pnmarith -o difference --description 'calculates the absolute value of pnmarith -subt… [See Man Page]'

