# pnmcolormap
# Autogenerated from man page /usr/share/man/man1/pnmcolormap.1.gz
# using Deroffing man parser
complete -c pnmcolormap -o sort --description 'This option causes the output colormap to be so… [See Man Page]'
complete -c pnmcolormap -o square --description 'By default, pnmcolormap produces as the color m… [See Man Page]'
complete -c pnmcolormap -o verbose --description 'This option causes pnmcolormap to display messa… [See Man Page]'
complete -c pnmcolormap -o center --description '.'
complete -c pnmcolormap -o meancolor --description '.'
complete -c pnmcolormap -o meanpixel --description '.'
complete -c pnmcolormap -o spreadbrightness --description '.'
complete -c pnmcolormap -o spreadluminosity --description 'These options control the quantization algorithm.'

