# pnmcat
# Autogenerated from man page /usr/share/man/man1/pnmcat.1.gz
# using Deroffing man parser
complete -c pnmcat -o topbottom -o jleft --description 'would stack the anymaps on top of each other, f… [See Man Page]'
complete -c pnmcat -o white --description 'and.'
complete -c pnmcat -o black --description 'flags specify what color to use to fill in the … [See Man Page]'

