# pnmmargin
# Autogenerated from man page /usr/share/man/man1/pnmmargin.1.gz
# using Deroffing man parser
complete -c pnmmargin -o white --description '.'
complete -c pnmmargin -o black --description 'and.'
complete -c pnmmargin -o color --description 'flags.   If no color is specified, the program makes a guess.'

