# pnmnorm
# Autogenerated from man page /usr/share/man/man1/pnmnorm.1.gz
# using Deroffing man parser
complete -c pnmnorm -o bpercent --description 'and.'
complete -c pnmnorm -o wpercent --description 'flags, or you can specify the exact pixel value… [See Man Page]'
complete -c pnmnorm -o bvalue --description 'and.'
complete -c pnmnorm -o wvalue --description 'flags.'
complete -c pnmnorm -o keephues --description 'option says to keep each pixel the same hue as … [See Man Page]'
complete -c pnmnorm -o brightmax --description 'option says to use the intensity of the most in… [See Man Page]'

