# pnmremap
# Autogenerated from man page /usr/share/man/man1/pnmremap.1.gz
# using Deroffing man parser
complete -c pnmremap -o floyd --description '.'
complete -c pnmremap -o fs --description '.'
complete -c pnmremap -o nofloyd --description '.'
complete -c pnmremap -o nofs --description 'These options determine whether Floyd-Steinberg… [See Man Page]'
complete -c pnmremap -o firstisdefault --description 'This affects what happens with a pixel in the i… [See Man Page]'
complete -c pnmremap -o missingcolor --description 'pnmremap chooses for the output the color in th… [See Man Page]'
complete -c pnmremap -o verbose --description 'Display helpful messages about the mapping process.'

