# pnmscale
# Autogenerated from man page /usr/share/man/man1/pnmscale.1.gz
# using Deroffing man parser
complete -c pnmscale -o xscale -o yscale --description '.'
complete -c pnmscale -o reduce --description 'reduction_factor option is equivalent to specif… [See Man Page]'
complete -c pnmscale -o xysize --description 'specifies a bounding box.'
complete -c pnmscale -o pixels --description 'specifies a maximum total number of output pixels.'
complete -c pnmscale -o nomix --description 'option.'

