# pnmtorle
# Autogenerated from man page /usr/share/man/man1/pnmtorle.1.gz
# using Deroffing man parser
complete -c pnmtorle -s v --description 'This option will cause pnmtorle to operate in verbose mode.'
complete -c pnmtorle -s h --description 'This option allows the header of the Netpbm ima… [See Man Page]'
complete -c pnmtorle -s a --description 'This option causes pnmtorle to include an alpha… [See Man Page]'
complete -c pnmtorle -s o --description 'If specified, the output will be written to this file.'

