# pod2text
# Autogenerated from man page /usr/share/man/man1/pod2text.1.gz
# using Type1
complete -c pod2text -s a -l alt --description 'Use an alternate output format that, among othe… [See Man Page]'
complete -c pod2text -l code --description 'Include any non-POD text from the input file in… [See Man Page]'
complete -c pod2text -s c -l color --description 'Format the output with \\s-1ANSI\\s0 color escape sequences.'
complete -c pod2text -s i -l indent --description 'Set the number of spaces to indent regular text… [See Man Page]'
complete -c pod2text -s h -l help --description 'Print out usage information and exit.'
complete -c pod2text -s l -l loose --description 'Print a blank line after a \\f(CW\\*(C`=head1\\*(C\' heading.'
complete -c pod2text -s m -l left-margin -l margin --description 'The width of the left margin in spaces.   Defaults to 0.'
complete -c pod2text -s o -l overstrike --description 'Format the output with overstrike printing.'
complete -c pod2text -s q -l quotes --description 'Sets the quote marks used to surround C<> text to quotes.'
complete -c pod2text -s s -l sentence --description 'Assume each sentence ends with two spaces and t… [See Man Page]'
complete -c pod2text -l stderr --description 'By default, pod2text puts any errors detected i… [See Man Page]'
complete -c pod2text -s t -l termcap --description 'Try to determine the width of the screen and th… [See Man Page]'
complete -c pod2text -s u -l utf8 --description 'By default, pod2text tries to use the same outp… [See Man Page]'

