# pod2man
# Autogenerated from man page /usr/share/man/man1/pod2man.1.gz
# using Type1
complete -c pod2man -s c -l center --description 'Sets the centered page header to string.'
complete -c pod2man -s d -l date --description 'Set the left-hand footer string to this value.'
complete -c pod2man -l fixed --description 'The fixed-width font to use for verbatim text and code.'
complete -c pod2man -l fixedbold --description 'Bold version of the fixed-width font.'
complete -c pod2man -l fixeditalic --description 'Italic version of the fixed-width font (actuall… [See Man Page]'
complete -c pod2man -l fixedbolditalic --description 'Bold italic (probably actually oblique) version… [See Man Page]'
complete -c pod2man -s h -l help --description 'Print out usage information.'
complete -c pod2man -s l -l lax --description 'No longer used.'
complete -c pod2man -s n -l name --description 'Set the name of the manual page to name.'
complete -c pod2man -s o -l official --description 'Set the default header to indicate that this pa… [See Man Page]'
complete -c pod2man -s q -l quotes --description 'Sets the quote marks used to surround C<> text to quotes.'
complete -c pod2man -s r -l release --description 'Set the centered footer.'
complete -c pod2man -s s -l section --description 'Set the section for the \\f(CW\\*(C`. TH\\*(C\' macro.'
complete -c pod2man -l stderr --description 'By default, pod2man puts any errors detected in… [See Man Page]'
complete -c pod2man -s u -l utf8 --description 'By default, pod2man produces the most conservat… [See Man Page]'

