# poff
# Autogenerated from man page /usr/share/man/man1/poff.1.gz
# using Deroffing man parser
complete -c poff -s q -l quick --description 'disconnect when ip-up finishes running.'
complete -c poff -s r --description 'causes the connection to be redialed after it is dropped.'
complete -c poff -s d --description 'toggles the state of pppd\'s debug option.'
complete -c poff -s c --description 'causes  pppd (8) to renegotiate compression.'
complete -c poff -s a --description 'stops all running ppp connections.'
complete -c poff -s h --description 'displays help information.'
complete -c poff -s v --description 'prints the version and exits.'

