# ppmdither
# Autogenerated from man page /usr/share/man/man1/ppmdither.1.gz
# using Deroffing man parser
complete -c ppmdither -o dim --description 'The size of the dithering matrix.'
complete -c ppmdither -o red --description 'The number of red shades to be used, including … [See Man Page]'
complete -c ppmdither -o green --description 'The number of green shades to be used, includin… [See Man Page]'
complete -c ppmdither -o blue --description 'The number of blue shades to be used, including… [See Man Page]'

