# ppmforge
# Autogenerated from man page /usr/share/man/man1/ppmforge.1.gz
# using Deroffing man parser
complete -c ppmforge -o clouds --description 'Generate clouds.   A pixmap of fractal clouds is generated.'
complete -c ppmforge -o dimension --description 'Sets the fractal dimension to the specified R d… [See Man Page]'
complete -c ppmforge -o glaciers --description 'The floating point  level setting controls the … [See Man Page]'
complete -c ppmforge -o hour --description 'When generating a planet,  hour is used as the … [See Man Page]'
complete -c ppmforge -o ice --description 'Sets the extent of the polar ice caps to the gi… [See Man Page]'
complete -c ppmforge -o inclination -o tilt --description 'The inclination angle of the planet with regard… [See Man Page]'
complete -c ppmforge -o mesh --description 'A mesh of R size " by " size will be used for t… [See Man Page]'
complete -c ppmforge -o night --description 'A starry sky is generated.'
complete -c ppmforge -o power --description 'Sets the ``power factor\'\' used to scale elevati… [See Man Page]'
complete -c ppmforge -o saturation --description 'Controls the degree of colour saturation of the… [See Man Page]'
complete -c ppmforge -o seed --description 'Sets the seed for the random number generator t… [See Man Page]'
complete -c ppmforge -o stars --description 'Specifies the percentage of pixels, in tenths o… [See Man Page]'
complete -c ppmforge -o xsize -o width --description 'Sets the width of the generated image to  width pixels.'
complete -c ppmforge -o quiet --description 'option).'
complete -c ppmforge -o ysize -o height --description 'Sets the height of the generated image to height pixels.'

