# ppmhist
# Autogenerated from man page /usr/share/man/man1/ppmhist.1.gz
# using Deroffing man parser
complete -c ppmhist -o sort --description 'The  -sort option determines the order in which… [See Man Page]'
complete -c ppmhist -o hexcolor --description 'Print the color components in hexadecimal.'
complete -c ppmhist -o noheader --description 'Do not print the column headings.'
complete -c ppmhist -o map --description 'Generates a PPM file of the colormap for the im… [See Man Page]'
complete -c ppmhist -o nomap --description 'Generates the histogram for human reading.'

