# ppmquantall
# Autogenerated from man page /usr/share/man/man1/ppmquantall.1.gz
# using Deroffing man parser
complete -c ppmquantall -o ext --description 'option.'
complete -c ppmquantall -o map --description 'option to separately quantize each pixmap to that set. ).'

