# ppmrainbow
# Autogenerated from man page /usr/share/man/man1/ppmrainbow.1.gz
# using Deroffing man parser
complete -c ppmrainbow -o width --description 'The width in pixels of the output image.   Default is 600.'
complete -c ppmrainbow -o height --description 'The height in pixels of the output image.   Default is 8.'
complete -c ppmrainbow -o tmpdir --description 'The directory specification of the directory   … [See Man Page]'
complete -c ppmrainbow -o verbose --description 'Print the "commands" (invocations of other Netp… [See Man Page]'

