# ppmtotga
# Autogenerated from man page /usr/share/man/man1/ppmtotga.1.gz
# using Deroffing man parser
complete -c ppmtotga -o mono --description 'Forces Targa file to be of type 8 bit monochrome.'
complete -c ppmtotga -o cmap --description 'Forces Targa file to be of type 24 bit colormapped.'
complete -c ppmtotga -o rgb --description 'Forces Targa file to be of type 24 bit unmapped color.'
complete -c ppmtotga -o norle --description 'Disables run-length encoding, in case you have … [See Man Page]'

