# ppmtopj
# Autogenerated from man page /usr/share/man/man1/ppmtopj.1.gz
# using Deroffing man parser
complete -c ppmtopj -o rle --description 'Run length encode the image.'
complete -c ppmtopj -o back --description 'Enhance the foreground by indicating if the bac… [See Man Page]'
complete -c ppmtopj -o render --description 'Use an internal rendering algorithm (default dither).'
complete -c ppmtopj -o gamma --description 'Gamma correct the image using the integet param… [See Man Page]'
complete -c ppmtopj -o center --description 'Center the image to an 8. 5 by 11 page.'
complete -c ppmtopj -o xpos --description 'Move by pos pixels in the x direction.'
complete -c ppmtopj -o ypos --description 'Move by pos pixels in the y direction.'

