# pppoe-discovery
# Autogenerated from man page /usr/share/man/man8/pppoe-discovery.8.gz
# using Deroffing man parser
complete -c pppoe-discovery -s I --description 'RS The -I option specifies the Ethernet interface to use.'
complete -c pppoe-discovery -s D --description 'RS The -D option causes every packet to be dump… [See Man Page]'
complete -c pppoe-discovery -s U --description 'RS Causes pppoe-discovery to use the Host-Uniq … [See Man Page]'
complete -c pppoe-discovery -s S --description 'RS Specifies the desired service name.'
complete -c pppoe-discovery -s C --description 'RS Specifies the desired access concentrator name.'
complete -c pppoe-discovery -s A --description 'RS This option is accepted for compatibility wi… [See Man Page]'
complete -c pppoe-discovery -s V -s h --description '.'

