# preload
# Autogenerated from man page /usr/share/man/man8/preload.8.gz
# using Deroffing man parser
complete -c preload -s h -l help --description 'Display command line parameters and their defau… [See Man Page]'
complete -c preload -s v -l version --description 'Display version information and exit.'
complete -c preload -s c -l conffile --description 'Set configuration file.  Empty string means no conf file.'
complete -c preload -s s -l statefile --description 'Set state file to load/save.  Empty string means no state.'
complete -c preload -s l -l logfile --description 'Set log file.  Empty string means to log to stderr.'
complete -c preload -s f -l foreground --description 'Run in foreground, do not daemonize.'
complete -c preload -s n -l nice --description 'Nice level.  (default is 15).'
complete -c preload -s V -l verbose --description 'Set the verbosity level.   Levels 0 to 10 are recognized.'
complete -c preload -s d -l debug --description 'Debug mode: --logfile \'\' --foreground --verbose 9 SIGNALS.'

