# prename
# Autogenerated from man page /usr/share/man/man1/prename.1.gz
# using Type1
complete -c prename -s v -l verbose --description 'Verbose: print names of files successfully renamed.'
complete -c prename -s n -l no-act --description 'No Action: show what files would have been renamed.'

