# preunzip
# Autogenerated from man page /usr/share/man/man1/preunzip.1.gz
# using Deroffing man parser
complete -c preunzip -s h -l help --description 'display help.'
complete -c preunzip -s d -l decompress --description 'force decompression.'
complete -c preunzip -s z -l compress --description 'dorce compression.'
complete -c preunzip -s L -l license --description 'display software license.'
complete -c preunzip -s V -l version --description 'display version.'
complete -c preunzip -s c -l stdout --description 'decompress to standard output.'
complete -c preunzip -s f -l force --description 'force.'
complete -c preunzip -s k -l keep --description 'keep input files.'
complete -c preunzip -s s -l sort --description 'sort and remove duplicates before compressing.'
complete -c preunzip -s S -l nocwl --description 'do not rename . wl suffix to . cwl (use . wl. pz instead).'
complete -c preunzip -s q -l quiet --description 'suppress all warnings AUTHOR This manual page w… [See Man Page]'

