# procan
# Autogenerated from man page /usr/share/man/man1/procan.1.gz
# using Type1
complete -c procan -s '?' --description 'Print a help text to stdout describing command … [See Man Page]'
complete -c procan -o '??' --description 'Like -h, plus a list of the short names of all … [See Man Page]'
complete -c procan -o '???' --description 'Like -hh, plus a list of all available address option names.'
complete -c procan -s d --description 'Prints fatal, error, warning, and notice messages.'

