# ps2pdf13
# Autogenerated from man page /usr/share/man/man1/ps2pdf13.1.gz
# using Deroffing man parser
complete -c ps2pdf13 -o dCompatibility --description 'switch in the command line.'
complete -c ps2pdf13 -o dPDFSETTINGS --description 'figure. ps proof. pdf.'
complete -c ps2pdf13 -s t --description 'ps2pdf.'

