# ps4pdf
# Autogenerated from man page /usr/share/man/man1/ps4pdf.1.gz
# using Deroffing man parser
complete -c ps4pdf -l help -s h --description 'Display a short help message.'
complete -c ps4pdf -l version --description 'Display the version of the script.'
complete -c ps4pdf -s v --description 'Be a bit noisy.'
complete -c ps4pdf -s q --description 'Be silent.  AUTHORS ps4pdf was written by Thomas Esser.'

