# psjoin
# Autogenerated from man page /usr/share/man/man1/psjoin.1.gz
# using Deroffing man parser
complete -c psjoin -o a: --description '.'
complete -c psjoin -o s: --description '.'
complete -c psjoin -o p: --description '.'
complete -c psjoin -o h: --description '.'

