# pstopdf
# Autogenerated from man page /usr/share/man/man1/pstopdf.1.gz
# using Deroffing man parser
complete -c pstopdf -l help --description 'Print usage and version information.'
complete -c pstopdf -l convert --description 'Convert EPS to PDF.   This option is assumed if none is given.'
complete -c pstopdf -l method --description 'What method to use for bounding boxes when converting to PDF.'
complete -c pstopdf -l resolution --description 'The resolution to use when when converting to pdf.'
complete -c pstopdf -l request --description 'Handle exa request file.'
complete -c pstopdf -l watch --description 'Watch folders for conversions (untested).'

