# pstopnm
# Autogenerated from man page /usr/share/man/man1/pstopnm.1.gz
# using Deroffing man parser
complete -c pstopnm -o forceplain --description 'forces the output file to be in plain (text) format.'
complete -c pstopnm -o llx --description 'selects   bx as the lower left corner x coordinate (in inches).'
complete -c pstopnm -o lly --description 'selects   by as the lower left corner y coordinate (in inches).'
complete -c pstopnm -o landscape --description 'renders the image in landscape mode.'
complete -c pstopnm -o portrait --description 'renders the image in portrait mode.'
complete -c pstopnm -o nocrop --description 'does not crop the output image dimensions to ma… [See Man Page]'
complete -c pstopnm -o pbm -o pgm -o ppm --description 'selects the format of the output file.'
complete -c pstopnm -o stdout --description 'causes output to go to Standard Output instead … [See Man Page]'
complete -c pstopnm -o urx --description 'selects   tx as the upper right corner x coordi… [See Man Page]'
complete -c pstopnm -o ury --description 'selects   ty as the upper right corner y coordi… [See Man Page]'
complete -c pstopnm -o verbose --description 'prints processing information to stdout.'
complete -c pstopnm -o xborder --description 'specifies that the border width along the Y axi… [See Man Page]'
complete -c pstopnm -o xmax --description 'specifies that the maximum output image width s… [See Man Page]'
complete -c pstopnm -o xsize --description 'specifies that the output image width must be e… [See Man Page]'
complete -c pstopnm -o yborder --description 'specifies that the border width along the X axi… [See Man Page]'
complete -c pstopnm -o ymax --description 'specifies that the maximum output image height … [See Man Page]'
complete -c pstopnm -o ysize --description 'options,  pstopnm  maps the document into the o… [See Man Page]'

