# pstops
# Autogenerated from man page /usr/share/man/man1/pstops.1.gz
# using Deroffing man parser
complete -c pstops -s w --description 'option gives the width which is used by the w d… [See Man Page]'
complete -c pstops -s h --description 'option gives the height which is used by the h … [See Man Page]'
complete -c pstops -s p --description 'option can be used as an alternative, to set th… [See Man Page]'
complete -c pstops -s b --description 'option prevents any bind operators in the PostS… [See Man Page]'
complete -c pstops -s d --description 'option draws a line around the border of each p… [See Man Page]'
complete -c pstops -s q --description 'option suppresses this.'

