# pycentral
# Autogenerated from man page /usr/share/man/man1/pycentral.1.gz
# using Deroffing man parser
complete -c pycentral -s v -l version --description 'Limit the output to the version numbers of the python versions.'
complete -c pycentral -s h -l help --description 'Print a help text. PP pycentral has the following sub commands.'

