# pyclean
# Autogenerated from man page /usr/share/man/man1/pyclean.1.gz
# using Deroffing man parser
complete -c pyclean -l version --description 'show program\\(aqs version number and exit.'
complete -c pyclean -s h -l help --description 'show this help message and exit.'
complete -c pyclean -s v -l verbose --description 'turn verbose more one.'
complete -c pyclean -s q -l quiet --description 'be quiet.'
complete -c pyclean -s p -l package --description 'specify Debian package name to clean.'

