# pycompile
# Autogenerated from man page /usr/share/man/man1/pycompile.1.gz
# using Deroffing man parser
complete -c pycompile -l version --description 'show program\\(aqs version number and exit.'
complete -c pycompile -s h -l help --description 'show this help message and exit.'
complete -c pycompile -s f -l force --description 'force rebuild of byte-code files even if timest… [See Man Page]'
complete -c pycompile -s O --description 'byte-compile to . pyo files.'
complete -c pycompile -s q -l quiet --description 'be quiet.'
complete -c pycompile -s v -l verbose --description 'turn verbose mode on.'
complete -c pycompile -s p -l package --description 'specify Debian package name whose files should be bytecompiled.'
complete -c pycompile -s V --description 'force private modules to be bytecompiled with P… [See Man Page]'
complete -c pycompile -o '3.0' --description '.'
complete -c pycompile -s X -l exclude --description 'exclude items that match given REGEXPR.'

