# pygettext
# Autogenerated from man page /usr/share/man/man1/pygettext.1.gz
# using Deroffing man parser
complete -c pygettext -s a -l extract-all --description 'Extract all strings.'
complete -c pygettext -s d -l default-domain --description 'Rename the default output file from messages. pot to name. pot.'
complete -c pygettext -s E -l escape --description 'Replace non-ASCII characters with octal escape sequences.'
complete -c pygettext -s D -l docstrings --description 'Extract module, class, method, and function docstrings.'
complete -c pygettext -s h -l help --description 'Print this help message and exit.'
complete -c pygettext -s k -l keyword --description 'Keywords to look for in addition to the default… [See Man Page]'
complete -c pygettext -s K -l no-default-keywords --description 'Disable the default set of keywords (see above).'
complete -c pygettext -l no-location --description 'Do not write filename/lineno location comments.'
complete -c pygettext -s n -l add-location --description 'Write filename/lineno location comments indicat… [See Man Page]'
complete -c pygettext -s o -l output --description 'Rename the default output file from messages. pot to FILENAME.'
complete -c pygettext -s p -l output-dir --description 'Output files will be placed in directory DIR.'
complete -c pygettext -s S -l style --description 'Specify which style to use for location comments.'
complete -c pygettext -s v -l verbose --description 'Print the names of the files being processed.'
complete -c pygettext -s V -l version --description 'Print the version of pygettext and exit.'
complete -c pygettext -s w -l width --description 'Set width of output to columns.'
complete -c pygettext -s x -l exclude-file --description 'Specify a file that contains a list of strings … [See Man Page]'
complete -c pygettext -o S/--style --description '.'
complete -c pygettext -s X -l no-docstrings --description 'Specify a file that contains a list of files (o… [See Man Page]'

