# qjackctl
# Autogenerated from man page /usr/share/man/man1/qjackctl.1.gz
# using Deroffing man parser
complete -c qjackctl -s s -l start --description 'Start JACK audio server immediately.'
complete -c qjackctl -s p -l preset --description 'Set default settings preset name.'
complete -c qjackctl -s a -l active-patchbay --description 'Set active patchbay definition file.'
complete -c qjackctl -s n -l server-name --description 'Set default JACK audio server name.'
complete -c qjackctl -s h -l help --description 'Show help about command line options.'
complete -c qjackctl -s v -l version --description 'Show version information.  SEE ALSO jackd(1).'

