# qsynth
# Autogenerated from man page /usr/share/man/man1/qsynth.1.gz
# using Deroffing man parser
complete -c qsynth -s n -l no-midi-in --description 'Don\'t create a midi driver to read MIDI input e… [See Man Page]'
complete -c qsynth -s m -l midi-driver --description 'The name of the midi driver to use [oss,alsa,alsa_seq,. ].'
complete -c qsynth -s K -l midi-channels --description 'The number of midi channels [default = 16].'
complete -c qsynth -s a -l audio-driver --description 'The audio driver [alsa,jack,oss,dsound,. ].'
complete -c qsynth -s j -l connect-jack-outputs --description 'Attempt to connect the jack outputs to the physical ports.'
complete -c qsynth -s L -l audio-channels --description 'The number of stereo audio channels [default = 1].'
complete -c qsynth -s G -l audio-groups --description 'The number of audio groups [default = 1].'
complete -c qsynth -s z -l audio-bufsize --description 'Size of each audio buffer.'
complete -c qsynth -s c -l audio-bufcount --description 'Number of audio buffers.'
complete -c qsynth -s r -l sample-rate --description 'Set the sample rate.'
complete -c qsynth -s R -l reverb --description 'Turn the reverb on or off [1|0|yes|no|on|off, default = on].'
complete -c qsynth -s C -l chorus --description 'Turn the chorus on or off [1|0|yes|no|on|off, default = on].'
complete -c qsynth -s g -l gain --description 'Set the master gain [0 < gain < 10, default = 0. 2].'
complete -c qsynth -s o -l option --description 'Define a setting name=value.'
complete -c qsynth -s s -l server --description 'Create and start server [default = no].'
complete -c qsynth -s i -l no-shell --description 'Don\'t read commands from the shell [ignored].'
complete -c qsynth -s d -l dump --description 'Dump midi router events.'
complete -c qsynth -s v -l verbose --description 'Print out verbose messages about midi events.'
complete -c qsynth -s h -l help --description 'Show help about command line options.'
complete -c qsynth -s V -l version --description 'Show version information AUTHOR Qsynth is writt… [See Man Page]'

