# rawshark
# Autogenerated from man page /usr/share/man/man1/rawshark.1.gz
# using Type1
complete -c rawshark -s d --description 'Specify how the packet data should be dissected.'
complete -c rawshark -s F --description 'Add the matching field to the output.'
complete -c rawshark -s h --description 'Print the version and options and exits.'
complete -c rawshark -s l --description 'Flush the standard output after the information… [See Man Page]'
complete -c rawshark -s n --description 'Disable network object name resolution (such as… [See Man Page]'
complete -c rawshark -s N --description 'Turn on name resolving only for particular type… [See Man Page]'
complete -c rawshark -s o --description 'Set a preference value, overriding the default … [See Man Page]'
complete -c rawshark -s p --description 'Assume that packet data is preceded by a pcap_p… [See Man Page]'
complete -c rawshark -s r --description 'Read packet data from input source.'
complete -c rawshark -s R --description 'Cause the specified filter (which uses the synt… [See Man Page]'
complete -c rawshark -s s --description 'Allows standard pcap files to be used as input,… [See Man Page]'
complete -c rawshark -s S --description 'Use the specified format string to print each field.'
complete -c rawshark -s t --description 'Set the format of the packet timestamp printed … [See Man Page]'

