# readom
# Autogenerated from man page /usr/share/man/man1/readom.1.gz
# using Deroffing man parser
complete -c readom -o version --description 'Print version information and exit.'
complete -c readom -s d --description 'Set the misc debug value to # (with debug=#) or… [See Man Page]'
complete -c readom -o silent -s s --description 'Do not print out a status report for failed SCSI commands.'
complete -c readom -s v --description 'Increment the level of general verbosity by one.'
complete -c readom -s V --description 'Increment the verbose level with respect of SCS… [See Man Page]'
complete -c readom -s w --description 'Switch to write mode.'
complete -c readom -o c2scan --description 'Scans the whole CD or the range specified by th… [See Man Page]'
complete -c readom -o scanbus --description 'Scan all SCSI devices on all SCSI busses and pr… [See Man Page]'
complete -c readom -o notrunc --description 'Do not truncate the output file when opening it.'
complete -c readom -o fulltoc --description 'Retrieve a full TOC from the current disk and print it in hex.'
complete -c readom -o clone --description 'Do a clone read.'
complete -c readom -o noerror --description 'Do not abort if the high level error checking i… [See Man Page]'
complete -c readom -o nocorr --description 'Switch the drive into a mode where it ignores r… [See Man Page]'
complete -c readom -o overhead --description 'Meter the SCSI command overhead time.'
complete -c readom -o dd --description 'this equals to  debug= 2.'
complete -c readom -o debug --description 'slows down the process and may be the reason fo… [See Man Page]'
complete -c readom -o VV --description 'will show data buffer content in addition.  Using.'
complete -c readom -o factor --description 'Output the speed values for meshpoints= # as fa… [See Man Page]'

