# recountdiff
# Autogenerated from man page /usr/share/man/man1/recountdiff.1.gz
# using Deroffing man parser
complete -c recountdiff -l help --description 'Display a short usage message.'
complete -c recountdiff -l version --description 'Display the version number of recountdiff.'

