# regedit
# Autogenerated from man page /usr/share/man/man1/regedit.1.gz
# using Type1
complete -c regedit -s D --description 'Deletes the specified registry key.'
complete -c regedit -s S --description 'Run regedit silently (ignored, CLI mode is always silent).'
complete -c regedit -s V --description 'Run regedit in advanced mode (ignored).'
complete -c regedit -s L --description 'Specifies the location of the system.'
complete -c regedit -s R --description 'Specifies the location of the user.'
complete -c regedit -s '?' --description 'Prints a help message.  Any other options are ignored.'

