# rename
# Autogenerated from man page /usr/share/man/man1/rename.ul.1.gz
# using Deroffing man parser
complete -c rename -s V -l version --description 'Display version information and exit.'
complete -c rename -s h -l help --description 'Display help text and exit.  EXAMPLES Given the files foo1 , .'

