# resize2fs
# Autogenerated from man page /usr/share/man/man8/resize2fs.8.gz
# using Deroffing man parser
complete -c resize2fs -s d --description 'Turns on various resize2fs debugging features, … [See Man Page]'
complete -c resize2fs -s f --description 'Forces resize2fs to proceed with the filesystem… [See Man Page]'
complete -c resize2fs -s F --description 'Flush the filesystem device\'s buffer caches before beginning.'
complete -c resize2fs -s M --description 'Shrink the filesystem to the minimum size.'
complete -c resize2fs -s p --description 'Prints out a percentage completion bars for eac… [See Man Page]'
complete -c resize2fs -s P --description 'Print the minimum size of the filesystem and exit.'
complete -c resize2fs -s S --description 'The resize2fs program will heuristically determ… [See Man Page]'

