# resize
# Autogenerated from man page /usr/share/man/man1/resize.1.gz
# using Deroffing man parser
complete -c resize -s u --description 'This option indicates that Bourne shell command… [See Man Page]'
complete -c resize -s c --description 'This option indicates that C shell commands sho… [See Man Page]'
complete -c resize -s s --description 'This option indicates that Sun console escape s… [See Man Page]'

