# rfcomm
# Autogenerated from man page /usr/share/man/man1/rfcomm.1.gz
# using Deroffing man parser
complete -c rfcomm -s h --description 'Gives a list of possible commands.'
complete -c rfcomm -s a --description 'Prints information about all configured RFCOMM devices.'
complete -c rfcomm -s r --description 'Switch TTY into raw mode (doesn\'t work with "bind").'
complete -c rfcomm -s f --description 'Specify alternate config file.'
complete -c rfcomm -s i --description 'The command is applied to device  -A Enable authentication.'
complete -c rfcomm -s A --description 'Enable authentification.'
complete -c rfcomm -s E --description 'Enable encryption.'
complete -c rfcomm -s S --description 'Secure connection.'
complete -c rfcomm -s M --description 'Become the master of a piconet.'
complete -c rfcomm -s L --description 'Set linger timeout COMMANDS.'

