# rig
# Autogenerated from man page /usr/share/man/man6/rig.6.gz
# using Deroffing man parser
complete -c rig -s f -s m --description 'Respectively, use female and male names.'
complete -c rig -o ddatadir --description 'Use data files found in datadir.'
complete -c rig -s d --description 'Use data files found in datadir.'
complete -c rig -s c --description 'Output num identities.  Default is 1.  FILES.'

