# ripemd160
# Autogenerated from man page /usr/share/man/man1/ripemd160.1ssl.gz
# using Type1
complete -c ripemd160 -s c --description 'print out the digest in two digit groups separa… [See Man Page]'
complete -c ripemd160 -s d --description 'print out \\s-1BIO\\s0 debugging information.'
complete -c ripemd160 -o hex --description 'digest is to be output as a hex dump.'
complete -c ripemd160 -o binary --description 'output the digest or signature in binary form.'
complete -c ripemd160 -o hmac --description 'set the \\s-1HMAC\\s0 key to \\*(L"arg\\*(R".'
complete -c ripemd160 -o non-fips-allow --description 'allow use of non \\s-1FIPS\\s0 digest.'
complete -c ripemd160 -o out --description 'filename to output to, or standard output by default.'
complete -c ripemd160 -o sign --description 'digitally sign the digest using the private key… [See Man Page]'
complete -c ripemd160 -o keyform --description 'Specifies the key format to sign digest with.'
complete -c ripemd160 -o engine --description 'Use engine id for operations (including private key storage).'
complete -c ripemd160 -o sigopt --description 'Pass options to the signature algorithm during … [See Man Page]'
complete -c ripemd160 -o passin --description 'the private key password source.'
complete -c ripemd160 -o verify --description 'verify the signature using the the public key i… [See Man Page]'
complete -c ripemd160 -o prverify --description 'verify the signature using the  the private key… [See Man Page]'
complete -c ripemd160 -o signature --description 'the actual signature to verify.'
complete -c ripemd160 -o mac --description 'create \\s-1MAC\\s0 (keyed Message Authentication Code).'
complete -c ripemd160 -o macopt --description 'Passes options to \\s-1MAC\\s0 algorithm, specified by -mac key.'
complete -c ripemd160 -o rand --description 'a file or files containing random data used to … [See Man Page]'

