# ristretto
# Autogenerated from man page /usr/share/man/man1/ristretto.1.gz
# using Deroffing man parser
complete -c ristretto -s '?' -l help --description 'Show help options.'
complete -c ristretto -l help-all --description 'Show all help options.'
complete -c ristretto -l help-gtk --description 'Show GTK+ Options . SS "Application Options:".'
complete -c ristretto -s v -l version --description 'Version information.'
complete -c ristretto -l display --description 'X display to use.'

