# rnano
# Autogenerated from man page /usr/share/man/man1/rnano.1.gz
# using Deroffing man parser
complete -c rnano -s '?' --description 'Same as -h (--help).'
complete -c rnano -s h --description 'Show a summary of command line options and exit.'
complete -c rnano -s V --description 'Show the current version number and exit.'

