# rstartd
# Autogenerated from man page /usr/share/man/man1/rstartd.1.gz
# using Deroffing man parser
complete -c rstartd -s c --description 'This option specifies the "global" configuratio… [See Man Page]'

