# rstart
# Autogenerated from man page /usr/share/man/man1/rstart.1.gz
# using Deroffing man parser
complete -c rstart -s c --description 'This option specifies the context in which the … [See Man Page]'
complete -c rstart -s g --description 'Interprets command as a generic command, as dis… [See Man Page]'
complete -c rstart -s l --description 'This option is passed to the underlying rsh; it… [See Man Page]'
complete -c rstart -s v --description 'This option requests that rstart be verbose in its operation.'

