# scp
# Autogenerated from man page /usr/share/man/man1/scp.1.gz
# using Darwin man parser
complete -c scp -s 1 --description 'Forces scp to use protocol 1.'
complete -c scp -s 2 --description 'Forces scp to use protocol 2.'
complete -c scp -s 3 --description 'Copies between two remote hosts are transferred… [See Man Page]'
complete -c scp -s 4 --description 'Forces scp to use IPv4 addresses only.'
complete -c scp -s 6 --description 'Forces scp to use IPv6 addresses only.'
complete -c scp -s B --description 'Selects batch mode (prevents asking for passwor… [See Man Page]'
complete -c scp -s C --description 'Compression enable.'
complete -c scp -s c --description 'Selects the cipher to use for encrypting the data transfer.'
complete -c scp -s F --description 'Specifies an alternative per-user configuration… [See Man Page]'
complete -c scp -s i --description 'Selects the file from which the identity (priva… [See Man Page]'
complete -c scp -s l --description 'Limits the used bandwidth, specified in Kbit/s.'
complete -c scp -s o --description 'Can be used to pass options to scp ssh in the f… [See Man Page]'
complete -c scp -s P --description 'Specifies the port to connect to on the remote host.'
complete -c scp -s p --description 'Preserves modification times, access times, and… [See Man Page]'
complete -c scp -s q --description 'Quiet mode: disables the progress meter as well… [See Man Page]'
complete -c scp -s r --description 'Recursively copy entire directories.'
complete -c scp -s S --description 'Name of program to use for the encrypted connection.'
complete -c scp -s v --description 'Verbose mode.'

