# scsi_mandat
# Autogenerated from man page /usr/share/man/man8/scsi_mandat.8.gz
# using Deroffing man parser
complete -c scsi_mandat -s h -l help --description 'print out the usage message then exit.'
complete -c scsi_mandat -s L -l log --description 'the output to stderr (from each SCSI command ex… [See Man Page]'
complete -c scsi_mandat -s q -l quiet --description 'the amount of output is reduced and typically o… [See Man Page]'
complete -c scsi_mandat -s v -l verbose --description 'increase level or verbosity.'

