# scsi_ready
# Autogenerated from man page /usr/share/man/man8/scsi_ready.8.gz
# using Deroffing man parser
complete -c scsi_ready -s b -l brief --description 'for each DEVICE given output a line containing … [See Man Page]'
complete -c scsi_ready -s h -l help --description 'print out the usage message then exit.'
complete -c scsi_ready -s v -l verbose --description 'increase level or verbosity.'

