# scsi_id
# Autogenerated from man page /usr/share/man/man8/scsi_id.8.gz
# using Deroffing man parser
complete -c scsi_id -l blacklisted --description 'The default behaviour - treat the device as bla… [See Man Page]'
complete -c scsi_id -l device --description 'Send SG_IO commands to device, such as /dev/sdc.'
complete -c scsi_id -l config --description 'Read configuration and black/white list entries… [See Man Page]'
complete -c scsi_id -l whitelisted --description 'Treat the device as white listed.'
complete -c scsi_id -l page --description 'Use SCSI INQUIRY VPD page code 0x80, 0x83, or pre-spc3-83.'
complete -c scsi_id -l replace-whitespace --description 'Reformat the output : replace all whitespaces by underscores.'
complete -c scsi_id -l export --description 'Export all data in KEY=<value> format used to i… [See Man Page]'
complete -c scsi_id -l verbose --description 'Generate verbose debugging output.'
complete -c scsi_id -l version --description 'Display version number and exit.  FILES /etc/scsi_id.'

