# setcifsacl
# Autogenerated from man page /usr/share/man/man8/setcifsacl.8.gz
# using Deroffing man parser
complete -c setcifsacl -s v --description 'Print version number and exit.'
complete -c setcifsacl -s a --description '.'
complete -c setcifsacl -s D --description '.'
complete -c setcifsacl -s M --description '.'
complete -c setcifsacl -s S --description '.'

