# setxkbmap
# Autogenerated from man page /usr/share/man/man1/setxkbmap.1.gz
# using Deroffing man parser
complete -c setxkbmap -o help --description 'Prints a message describing the valid input to setxkbmap.'
complete -c setxkbmap -o compat --description 'Specifies the name of the compatibility map com… [See Man Page]'
complete -c setxkbmap -o config --description 'Specifies the name of an XKB configuration file… [See Man Page]'
complete -c setxkbmap -o device --description 'Specifies the numeric device id of the input de… [See Man Page]'
complete -c setxkbmap -o display --description 'Specifies the display to be updated with the ne… [See Man Page]'
complete -c setxkbmap -o geometry --description 'Specifies the name of the geometry component us… [See Man Page]'
complete -c setxkbmap -s I --description 'Adds a directory to the list of directories to … [See Man Page]'
complete -c setxkbmap -o keycodes --description 'Specifies the name of the keycodes component us… [See Man Page]'
complete -c setxkbmap -o keymap --description 'Specifies the name of the keymap description us… [See Man Page]'
complete -c setxkbmap -o layout --description 'Specifies the name of the layout used to determ… [See Man Page]'
complete -c setxkbmap -o model --description 'Specifies the name of the keyboard model used t… [See Man Page]'
complete -c setxkbmap -o option --description 'Specifies the name of an option to determine th… [See Man Page]'
complete -c setxkbmap -o print --description 'With this option setxkbmap just prints componen… [See Man Page]'
complete -c setxkbmap -o query --description 'With this option setxkbmap just prints the curr… [See Man Page]'
complete -c setxkbmap -o rules --description 'Specifies the name of the rules file used to re… [See Man Page]'
complete -c setxkbmap -o symbols --description 'Specifies the name of the symbols component use… [See Man Page]'
complete -c setxkbmap -o synch --description 'Force synchronization for X requests.'
complete -c setxkbmap -o types --description 'Specifies the name of the types component used … [See Man Page]'
complete -c setxkbmap -o variant --description 'Specifies which variant of the keyboard layout … [See Man Page]'
complete -c setxkbmap -o verbose -s v --description 'Specifies level of verbosity in output messages.'

