# sg_format
# Autogenerated from man page /usr/share/man/man8/sg_format.8.gz
# using Deroffing man parser
complete -c sg_format -s C -l cmplst --description 'sets the CMPLST ("complete list") bit in the FO… [See Man Page]'
complete -c sg_format -s c -l count --description 'where COUNT is the number of blocks to be forma… [See Man Page]'
complete -c sg_format -s D -l dcrt --description 'this option sets the DCRT bit in the FORMAT UNI… [See Man Page]'
complete -c sg_format -s e -l early --description 'during a format operation, The default action o… [See Man Page]'
complete -c sg_format -s f -l fmtpinfo --description 'sets the FMTPINFO field in the FORMAT UNIT cdb … [See Man Page]'
complete -c sg_format -s F -l format --description 'issue a SCSI FORMAT UNIT command.'
complete -c sg_format -s h -l help --description 'print out the usage information then exit.'
complete -c sg_format -s l -l long --description 'the default action of this utility is to assume… [See Man Page]'
complete -c sg_format -s P -l pfu --description 'sets the "Protection Field Usage" field in the … [See Man Page]'
complete -c sg_format -s q -l pie --description 'sets the "Protection Interval Exponent" field i… [See Man Page]'
complete -c sg_format -s p -l pinfo --description 'The option is deprecated, use the --fmtpinfo=FP… [See Man Page]'
complete -c sg_format -s x -l poll --description 'where PT is the type of poll used.'
complete -c sg_format -s r -l resize --description 'rather than format the disk, it can be resized.'
complete -c sg_format -s R -l rto_req --description 'The option is deprecated, use the --fmtpinfo=FP… [See Man Page]'
complete -c sg_format -s S -l security --description 'sets the "Security Initialization" (SI) bit in … [See Man Page]'
complete -c sg_format -s 6 -l six --description 'Use 6 byte variants of MODE SENSE and MODE SELECT.'
complete -c sg_format -s s -l size --description 'where SIZE is the block size (i. e.'
complete -c sg_format -s v -l verbose --description 'increase the level of verbosity, (i. e.  debug output).'
complete -c sg_format -s V -l version --description 'print the version string and then exit.'
complete -c sg_format -s w -l wait --description 'the default format action is to set the "IMMED"… [See Man Page]'

