# sg_map26
# Autogenerated from man page /usr/share/man/man8/sg_map26.8.gz
# using Deroffing man parser
complete -c sg_map26 -s d -l dev_dir --description 'where DIR is the directory to search for result… [See Man Page]'
complete -c sg_map26 -s g -l given_is --description 'specifies the DEVICE is either a device special… [See Man Page]'
complete -c sg_map26 -s h -l help --description 'output the usage message then exit.'
complete -c sg_map26 -s r -l result --description 'specifies what variety of file (or files) that … [See Man Page]'
complete -c sg_map26 -s s -l symlink --description 'when a device special file is being sought (i. e.'
complete -c sg_map26 -s v -l verbose --description 'increase the level of verbosity, (i. e.  debug output).'
complete -c sg_map26 -s V -l version --description 'print the version string and then exit.'

