# sg_referrals
# Autogenerated from man page /usr/share/man/man8/sg_referrals.8.gz
# using Deroffing man parser
complete -c sg_referrals -s h -l help --description 'output the usage message then exit.'
complete -c sg_referrals -s H -l hex --description 'output response to this command in ASCII hex.'
complete -c sg_referrals -s l -l lba --description 'where LBA is the Logical Block Address (LBA) in… [See Man Page]'
complete -c sg_referrals -s m -l maxlen --description 'where LEN is the (maximum) response length in bytes.'
complete -c sg_referrals -s s -l one-segment --description 'report the user data segment of the segment spe… [See Man Page]'
complete -c sg_referrals -s r -l raw --description 'output response in binary (to stdout).'
complete -c sg_referrals -s v -l verbose --description 'increase the level of verbosity, (i. e.  debug output).'
complete -c sg_referrals -s V -l version --description 'print the version string and then exit.'

