# sg_reassign
# Autogenerated from man page /usr/share/man/man8/sg_reassign.8.gz
# using Deroffing man parser
complete -c sg_reassign -s a -l address --description 'where A,A.  is a string of comma separated numbers.'
complete -c sg_reassign -s d -l dummy --description 'prepare for but do not execute the SCSI REASSIG… [See Man Page]'
complete -c sg_reassign -s e -l eight --description 'when value is 1 then it sets the \'LONGLBA\' flag… [See Man Page]'
complete -c sg_reassign -s g -l grown --description 'use the SCSI READ DEFECT DATA (10) command to d… [See Man Page]'
complete -c sg_reassign -s h -l help --description 'output the usage message then exit.'
complete -c sg_reassign -s l -l longlist --description 'sets the REASSIGN BLOCKS cdb field of the same … [See Man Page]'
complete -c sg_reassign -s p -l primary --description 'use the SCSI READ DEFECT DATA (10) command to d… [See Man Page]'
complete -c sg_reassign -s v -l verbose --description 'increase the level of verbosity, (i. e.  debug output).'
complete -c sg_reassign -s V -l version --description 'print the version string and then exit.'

