# sg_rdac
# Autogenerated from man page /usr/share/man/man8/sg_rdac.8.gz
# using Deroffing man parser
complete -c sg_rdac -s a --description 'Transfer all (visible) devices.'
complete -c sg_rdac -s f --description 'Transfer the device identified by LUN.'
complete -c sg_rdac -s v --description 'be verbose.'
complete -c sg_rdac -s V --description 'print version string then exit EXIT STATUS The … [See Man Page]'

