# sg_readcap
# Autogenerated from man page /usr/share/man/man8/sg_readcap.8.gz
# using Deroffing man parser
complete -c sg_readcap -s b -l brief --description 'outputs two hex numbers (prefixed with \'0x\' and… [See Man Page]'
complete -c sg_readcap -s h -l help --description 'print out the usage message then exit.'
complete -c sg_readcap -s H -l hex --description 'output the response to the READ CAPACITY comman… [See Man Page]'
complete -c sg_readcap -s L -l lba --description 'used in conjunction with --pmi option.'
complete -c sg_readcap -s l -l long --description 'Use the 16 byte cdb variant of the READ CAPACITY command.'
complete -c sg_readcap -l 16 --description 'Use the 16 byte cdb variant of the READ CAPACITY command.'
complete -c sg_readcap -s O -l old --description 'switch to older style options.'
complete -c sg_readcap -s p -l pmi --description 'partial medium indicator: for finding the next … [See Man Page]'
complete -c sg_readcap -s r -l raw --description 'output response in binary to stdout.'
complete -c sg_readcap -s v -l verbose --description 'increase level of verbosity.  Can be used multiple times.'
complete -c sg_readcap -s V -l version --description 'outputs version string then exits.  NOTES In the 2.'
complete -c sg_readcap -o 16 --description 'Use the 16 byte cdb variant of the READ CAPACITY command.'
complete -c sg_readcap -o lba --description 'used in conjunction with -pmi option.'
complete -c sg_readcap -s N --description 'switch to the newer style options.'
complete -c sg_readcap -o pmi --description 'partial medium indicator: for finding the next … [See Man Page]'

