# sg_senddiag
# Autogenerated from man page /usr/share/man/man8/sg_senddiag.8.gz
# using Deroffing man parser
complete -c sg_senddiag -s d -l doff --description 'set the Device Offline (DevOffL) bit (default is clear).'
complete -c sg_senddiag -s e -l extdur --description 'outputs the expected extended self-test duration.'
complete -c sg_senddiag -s h -l help --description 'print usage message then exit.'
complete -c sg_senddiag -s H -l hex --description 'outputs response from RECEIVE DIAGNOSTIC RESULT… [See Man Page]'
complete -c sg_senddiag -s l -l list --description 'when a DEVICE is also given lists the names of … [See Man Page]'
complete -c sg_senddiag -s O -l old --description 'switch to older style options.'
complete -c sg_senddiag -s p -l pf --description 'set Page Format (PF) bit.  By default it is clear (i. e.'
complete -c sg_senddiag -s r -l raw --description 'string of comma separated hex numbers each of w… [See Man Page]'
complete -c sg_senddiag -s s -l selftest --description 'where ST is the self-test code.'
complete -c sg_senddiag -s t -l test --description 'sets the _default_ Self Test (SelfTest) bit.'
complete -c sg_senddiag -s u -l uoff --description 'set the Unit Offline (UnitOffL) bit (default is clear).'
complete -c sg_senddiag -s v -l verbose --description 'increase level of verbosity.  Can be used multiple times.'
complete -c sg_senddiag -s V -l version --description 'print out version string then exit.'
complete -c sg_senddiag -o doff --description 'set the Device Offline (DevOffL) bit (default is clear).'
complete -c sg_senddiag -s N --description 'switch to the newer style options.'
complete -c sg_senddiag -o pf --description 'set Page Format (PF) bit.  By default it is clear (i. e.'
complete -c sg_senddiag -o raw --description 'string of comma separated hex numbers each of w… [See Man Page]'
complete -c sg_senddiag -o uoff --description 'set the Unit Offline (UnitOffL) bit (default is clear).'
complete -c sg_senddiag -s '?' --description 'output usage message.  Ignore all other parameters.'

