# sg_sat_set_features
# Autogenerated from man page /usr/share/man/man8/sg_sat_set_features.8.gz
# using Deroffing man parser
complete -c sg_sat_set_features -s c -l count --description 'the number CO is placed in the "count" field in… [See Man Page]'
complete -c sg_sat_set_features -s C -l ck_cond --description 'sets the CK_COND bit in the ATA PASS-THROUGH SCSI cdb.'
complete -c sg_sat_set_features -s f -l feature --description 'the value FEA is placed in the "feature" field … [See Man Page]'
complete -c sg_sat_set_features -s h -l help --description 'outputs the usage message summarizing command l… [See Man Page]'
complete -c sg_sat_set_features -s l -l len --description 'this is the length of the SCSI cdb used for the… [See Man Page]'
complete -c sg_sat_set_features -s L -l lba --description 'the number LBA is placed in the "lba" field in … [See Man Page]'
complete -c sg_sat_set_features -s v -l verbose --description 'increases the level or verbosity.'
complete -c sg_sat_set_features -s V -l version --description 'print out version string NOTES In the 2.'

