# sg_sat_phy_event
# Autogenerated from man page /usr/share/man/man8/sg_sat_phy_event.8.gz
# using Deroffing man parser
complete -c sg_sat_phy_event -s c -l ck_cond --description 'sets the CK_COND bit in the ATA PASS-THROUGH SCSI cdb.'
complete -c sg_sat_phy_event -s e -l extend --description 'sets the EXTEND bit in the ATA PASS-THROUGH SCSI cdb.'
complete -c sg_sat_phy_event -s h -l help --description 'outputs the usage message summarizing command l… [See Man Page]'
complete -c sg_sat_phy_event -s H -l hex --description 'outputs the ATA READ LOG EXT response in hex.'
complete -c sg_sat_phy_event -s i -l ignore --description 'usually the phy counter identifier names are decoded.'
complete -c sg_sat_phy_event -s l -l len --description 'this is the length of the SCSI cdb used for the… [See Man Page]'
complete -c sg_sat_phy_event -s r -l raw --description 'output the ATA READ LOG EXT response in binary.'
complete -c sg_sat_phy_event -s R -l reset --description 'reset the counters after the current values are… [See Man Page]'
complete -c sg_sat_phy_event -s v -l verbose --description 'increases the level or verbosity.'
complete -c sg_sat_phy_event -s V -l version --description 'print out version string NOTES The SCSI ATA PAS… [See Man Page]'

