# sg_sanitize
# Autogenerated from man page /usr/share/man/man8/sg_sanitize.8.gz
# using Deroffing man parser
complete -c sg_sanitize -s B -l block --description 'perform a "block erase" sanitize operation.'
complete -c sg_sanitize -s c -l count --description 'where OC is the "overwrite count" associated wi… [See Man Page]'
complete -c sg_sanitize -s C -l crypto --description 'perform a "cryptographic erase" sanitize operation.'
complete -c sg_sanitize -s e -l early --description 'the default action of this utility is to poll t… [See Man Page]'
complete -c sg_sanitize -s h -l help --description 'print out the usage information then exit.'
complete -c sg_sanitize -s i -l ipl --description 'set the initialization pattern length to LEN bytes.'
complete -c sg_sanitize -s I -l invert --description 'set the INVERT bit in the overwrite service act… [See Man Page]'
complete -c sg_sanitize -s O -l overwrite --description 'perform an "overwrite" sanitize operation.'
complete -c sg_sanitize -s p -l pattern --description 'where PF is the filename of a file containing t… [See Man Page]'
complete -c sg_sanitize -s Q -l quick --description 'the default action (i. e.'
complete -c sg_sanitize -s v -l verbose --description 'increase the level of verbosity, (i. e.  debug output).'
complete -c sg_sanitize -s V -l version --description 'print the version string and then exit.'
complete -c sg_sanitize -s w -l wait --description 'the default action (i. e.'

