# sg_verify
# Autogenerated from man page /usr/share/man/man8/sg_verify.8.gz
# using Deroffing man parser
complete -c sg_verify -s b -l bpc --description 'where BPC specifies the maximum number of block… [See Man Page]'
complete -c sg_verify -s c -l count --description 'where COUNT specifies the number of blocks to verify.'
complete -c sg_verify -s d -l dpo --description 'disable page out changes the cache retention pr… [See Man Page]'
complete -c sg_verify -s h -l help --description 'output the usage message then exit.'
complete -c sg_verify -s l -l lba --description 'where LBA specifies the logical block address o… [See Man Page]'
complete -c sg_verify -s v -l verbose --description 'increase the level of verbosity, (i. e.  debug output).'
complete -c sg_verify -s V -l version --description 'print the version string and then exit.'
complete -c sg_verify -s r -l readonly --description 'opens the DEVICE read-only rather than read-wri… [See Man Page]'
complete -c sg_verify -s P -l vrprotect --description 'where VRP is the value in the vrprotect field i… [See Man Page]'

