# shtool-mkdir
# Autogenerated from man page /usr/share/man/man1/shtool-mkdir.1.gz
# using Type1
complete -c shtool-mkdir -s t -l trace --description 'Shows the actually involved shell commands.'
complete -c shtool-mkdir -s f -l force --description 'Forced continuation and no complaints if direct… [See Man Page]'
complete -c shtool-mkdir -s p -l parents --description 'Automatic parent directory creation.'
complete -c shtool-mkdir -s m -l mode --description 'The directory mode applied to the directory, see chmod\\|(1).'
complete -c shtool-mkdir -s o -l owner --description 'The directory owner name or id applied to the d… [See Man Page]'

