# shtool-slo
# Autogenerated from man page /usr/share/man/man1/shtool-slo.1.gz
# using Type1
complete -c shtool-slo -s p -l prefix --description 'Vb 1     FIXME . Ve.'
complete -c shtool-slo -o Ldir --description 'Directory where libraries are searched in.'

