# shtool-version
# Autogenerated from man page /usr/share/man/man1/shtool-version.1.gz
# using Type1
complete -c shtool-version -s v -l verbose --description 'Print verbose information during processing.'
complete -c shtool-version -s l -l language --description 'Choose format of version file file.'
complete -c shtool-version -s n -l name --description 'Name the program the version is maintained for.'
complete -c shtool-version -s p -l prefix -s s -l set --description 'Set the version to version.'
complete -c shtool-version -s e -l edit --description 'Interactively enter a new version.'
complete -c shtool-version -s i -l increase --description 'When option ``-i\'\' is used, the current version… [See Man Page]'

