# shtool-install
# Autogenerated from man page /usr/share/man/man1/shtool-install.1.gz
# using Type1
complete -c shtool-install -s v -l verbose --description 'Display some processing information.'
complete -c shtool-install -s t -l trace --description 'Enable the output of the essential shell comman… [See Man Page]'
complete -c shtool-install -s d -l mkdir --description 'To maximize \\s-1BSD\\s0 compatiblity, the \\s-1BS… [See Man Page]'
complete -c shtool-install -s c -l copy --description 'Copy the file to the target path.  Default is to move.'
complete -c shtool-install -s C -l compare-copy --description 'Same as -c except if the destination file alrea… [See Man Page]'
complete -c shtool-install -s s -l strip --description 'This option strips program executables during t… [See Man Page]'
complete -c shtool-install -s m -l mode --description 'The file mode applied to the target, see chmod\\|(1).'
complete -c shtool-install -s o -l owner --description 'The file owner name or id applied to the target… [See Man Page]'
complete -c shtool-install -s g -l group --description 'The file group name or id applied to the target… [See Man Page]'

