# shtool-rotate
# Autogenerated from man page /usr/share/man/man1/shtool-rotate.1.gz
# using Type1
complete -c shtool-rotate -s v -l verbose --description 'Display some processing information.'
complete -c shtool-rotate -s t -l trace --description 'Enable the output of the essential shell comman… [See Man Page]'
complete -c shtool-rotate -s f -l force --description 'Force silent creation of archive directory if i… [See Man Page]'
complete -c shtool-rotate -s n -l num-files --description 'Create count archive files.  Default is 10.'
complete -c shtool-rotate -s s -l size --description 'Only rotate if logfile exceeds size.'
complete -c shtool-rotate -s c -l copy --description 'Copy file to archive then truncate original.'
complete -c shtool-rotate -s r -l remove --description 'Removes file after rotation instead of providin… [See Man Page]'
complete -c shtool-rotate -s a -l archive-dir --description 'Specify the archive directory.'
complete -c shtool-rotate -s z -l compress --description 'Enables compression of archive files with compr… [See Man Page]'
complete -c shtool-rotate -s b -l background --description 'Enable background compression.'
complete -c shtool-rotate -s d -l delay --description 'Delays the compression of archive file number 0.'
complete -c shtool-rotate -s p -l pad --description 'Enables padding with leading zeros in the numbe… [See Man Page]'
complete -c shtool-rotate -s m -l mode --description 'The file mode applied to the created files, see chmod\\|(1).'
complete -c shtool-rotate -s o -l owner --description 'The file owner name or id applied to the create… [See Man Page]'
complete -c shtool-rotate -s g -l group --description 'The file group name or id applied to the create… [See Man Page]'
complete -c shtool-rotate -s M -l migrate --description 'Execute a \\*(L"migration\\*(R" command just befo… [See Man Page]'
complete -c shtool-rotate -s P -l prolog --description 'Execute a \\*(L"prolog\\*(R" command before the rotation step.'

