# shtool-subst
# Autogenerated from man page /usr/share/man/man1/shtool-subst.1.gz
# using Type1
complete -c shtool-subst -s v -l verbose --description 'Display some processing information.'
complete -c shtool-subst -s t -l trace --description 'Enable the output of the essential shell comman… [See Man Page]'
complete -c shtool-subst -s n -l nop --description 'No operation mode.'
complete -c shtool-subst -s w -l warning --description 'Show warning on substitution operation resultin… [See Man Page]'
complete -c shtool-subst -s q -l quiet --description 'Suppress warning on substitution operation resu… [See Man Page]'
complete -c shtool-subst -s s -l stealth --description 'Stealth operation.  Preserve timestamp on file.'
complete -c shtool-subst -s i -l interactive --description 'Enter interactive mode where the user has to ap… [See Man Page]'
complete -c shtool-subst -s b -l backup --description 'Preserve backup of original file using file name extension ext.'
complete -c shtool-subst -s e -l exec --description 'Specify sed\\|(1) command directly.'

