# shtool-mkshadow
# Autogenerated from man page /usr/share/man/man1/shtool-mkshadow.1.gz
# using Type1
complete -c shtool-mkshadow -s v -l verbose --description 'Display some processing information.'
complete -c shtool-mkshadow -s t -l trace --description 'Enable the output of the essential shell comman… [See Man Page]'

