# simple-scan
# Autogenerated from man page /usr/share/man/man1/simple-scan.1.gz
# using Deroffing man parser
complete -c simple-scan -s d -l debug --description 'Print debugging messages.'
complete -c simple-scan -s v -l version --description 'Show release version.'
complete -c simple-scan -s '?' -l help --description 'Show help options.'
complete -c simple-scan -l help-all --description 'Show all help options.'
complete -c simple-scan -l help-gtk --description 'Show GTK+ options.'

