# six-script
# Autogenerated from man page /usr/share/man/man1/six-script.1.gz
# using Deroffing man parser
complete -c six-script -s : --description 'Comma separated list of run-time options.'
complete -c six-script -s e --description 'Evaluate an expression.'
complete -c six-script -s f --description 'Skip initialization file.'
complete -c six-script -s v --description 'Show version of program.'

