# six
# Autogenerated from man page /usr/share/man/man1/six.1.gz
# using Deroffing man parser
complete -c six -s : --description 'Comma separated list of run-time options.'
complete -c six -s e --description 'Evaluate an expression.'
complete -c six -s f --description 'Skip initialization file.'
complete -c six -s v --description 'Show version of program.'

