# skyrocket
# Autogenerated from man page /usr/share/man/man1/skyrocket.1.gz
# using Deroffing man parser
complete -c skyrocket -l root --description 'Draw on the root window.'
complete -c skyrocket -l maxfps --description 'Set maximum frame rate.'
complete -c skyrocket -l vsync --description 'Limit redraws to specified number of vertical refreshes.'
complete -c skyrocket -l dpms --description 'Stop rendering new frames if the display is not on.   0 - 1.'
complete -c skyrocket -l maxrockets --description 'Maximum number of rockets.   1 - 100.   Default: 8.'
complete -c skyrocket -l smoke --description 'Smoke lifespan (in seconds).   0 - 60.   Default: 5.'
complete -c skyrocket -l explosionsmoke --description 'Amount of smoke in explosions (This will create… [See Man Page]'
complete -c skyrocket -l wind --description 'Wind speed.   0 - 100.   Default: 20.'
complete -c skyrocket -l ambient --description 'Ambient light.   0 - 100.   Default: 10.'
complete -c skyrocket -l stardensity --description 'Star density.   0 - 100.   Default: 20.'
complete -c skyrocket -l flare --description 'Lens flare brightness.   0 - 100.   Default: 20.'
complete -c skyrocket -l moonglow --description 'Moon glow brightness.   0 - 100.   Default: 20.'
complete -c skyrocket -l volume --description 'Sound effects volume.   0 - 100.   Default: 100.'
complete -c skyrocket -l moon --description 'Show moon.   Default: True.'
complete -c skyrocket -l clouds --description 'Show clouds.   Default: True.'
complete -c skyrocket -l earth --description 'Show earth.   Default: True.'
complete -c skyrocket -l illumination --description 'Show illumination (on clouds and earth).'

