# slconsole
# Autogenerated from man page /usr/share/man/man1/slconsole.1.gz
# using Deroffing man parser
complete -c slconsole -s H -l connect-host --description 'connect to sooperlooper engine on given host (d… [See Man Page]'
complete -c slconsole -s P -l connect-port --description 'connect to sooperlooper engine on given port (default is 9951).'
complete -c slconsole -s h -l help --description 'this usage output.'

