# sldtoppm
# Autogenerated from man page /usr/share/man/man1/sldtoppm.1.gz
# using Deroffing man parser
complete -c sldtoppm -o adjust --description 'If the display on which the slide file was crea… [See Man Page]'
complete -c sldtoppm -o dir --description 'The input is assumed to be an AutoCAD slide library file.'
complete -c sldtoppm -o height --description 'Scales the image in the vector domain so it is … [See Man Page]'
complete -c sldtoppm -o info --description 'Dump the slide file header on standard error, d… [See Man Page]'
complete -c sldtoppm -o lib --description 'Extracts the slide with the given  name from th… [See Man Page]'
complete -c sldtoppm -o Lib --description 'Extracts the slide with the given  name from th… [See Man Page]'
complete -c sldtoppm -o scale --description 'Scales the image by factor R s , which may be a… [See Man Page]'
complete -c sldtoppm -o verbose --description 'Dumps the slide file header and lists every vec… [See Man Page]'
complete -c sldtoppm -o width --description 'Scales the image in the vector domain so it is … [See Man Page]'
complete -c sldtoppm -o xsize --description 'Scales the image in the vector domain so it is … [See Man Page]'
complete -c sldtoppm -o ysize --description 'option is specified, the height will be adjuste… [See Man Page]'

