# smbget
# Autogenerated from man page /usr/share/man/man1/smbget.1.gz
# using Deroffing man parser
complete -c smbget -s a -l guest --description 'Work as user guest.'
complete -c smbget -s r -l resume --description 'Automatically resume aborted files.'
complete -c smbget -s R -l recursive --description 'Recursively download files.'
complete -c smbget -s u -l username --description 'Username to use.'
complete -c smbget -s p -l password --description 'Password to use.'
complete -c smbget -s w -l workgroup --description 'Workgroup to use (optional).'
complete -c smbget -s n -l nonprompt --description 'Don\'t ask anything (non-interactive).'
complete -c smbget -s d -l debuglevel --description 'Debuglevel to use.'
complete -c smbget -s D -l dots --description 'Show dots as progress indication.'
complete -c smbget -s P -l keep-permissions --description 'Set same permissions on local file as are set on remote file.'
complete -c smbget -s o -l outputfile --description 'Write the file that is being downloaded to the specified file.'
complete -c smbget -s O -l stdout --description 'Write the file that is being downloaded to standard output.'
complete -c smbget -s f -l rcfile --description 'Use specified rcfile.'
complete -c smbget -s q -l quiet --description 'Be quiet.'
complete -c smbget -s v -l verbose --description 'Be verbose.'
complete -c smbget -s b -l blocksize --description 'Number of bytes to download in a block.  Defaults to 64000.'
complete -c smbget -s '?' -l help --description 'Show help message.'
complete -c smbget -l usage --description 'Display brief usage message.'

