# smidump
# Autogenerated from man page /usr/share/man/man1/smidump.1.gz
# using Deroffing man parser
complete -c smidump -s V -l version --description 'Show the smidump version and exit.'
complete -c smidump -s h -l help --description 'Show a help text and exit.'
complete -c smidump -s c -l config --description 'Read file instead of any other (global and user… [See Man Page]'
complete -c smidump -s f -l format --description 'Use format when dumping a module.'
complete -c smidump -s l -l level --description 'Report errors and warnings up to the given severity level.'
complete -c smidump -s s -l severity --description 'Show the error severity in brackets before error messages.'
complete -c smidump -s m -l error-names --description 'Show the error names in braces before error messages.'
complete -c smidump -s o -l output --description 'Write the output in one or multiple files instead of stdout.'
complete -c smidump -s p -l preload --description 'Preload the module module before reading the main module(s).'
complete -c smidump -s q -l quiet --description 'Suppress comments from dumped modules.'
complete -c smidump -s u -l unified --description 'Dump a unified output in case of multiple modul… [See Man Page]'
complete -c smidump -s k -l keep-going --description 'Continue as much as possible after serious parse errors.'

