# software-center
# Autogenerated from man page /usr/share/man/man1/software-center.1.gz
# using Deroffing man parser
complete -c software-center -l version --description 'show program\'s version number and exit.'
complete -c software-center -s h -l help --description 'show this help message and exit.'
complete -c software-center -l debug --description 'enable debug mode.'

