# spd-conf
# Autogenerated from man page /usr/share/man/man1/spd-conf.1.gz
# using Deroffing man parser
complete -c spd-conf -s h -l help --description 'show this help message and exit.'
complete -c spd-conf -s e -l espeak --description 'Use espeak to synthesize messages.'
complete -c spd-conf -l test-festival --description 'Test whether Festival works as a server.'
complete -c spd-conf -s s -l test-spd-say --description 'Test connection to Speech Dispatcher using spd-say.'
complete -c spd-conf -l test-pulse --description 'Test Pulse Audio.'
complete -c spd-conf -s c -l config-basic-settings-user --description 'Configure basic settings in user configuration.'
complete -c spd-conf -s u -l create-user-conf --description 'Create Speech Dispatcher configuration for the given user.'
complete -c spd-conf -s C -l config-basic-settings-system --description 'Configure basic settings in system-wide configuration.'
complete -c spd-conf -s n -l dont-ask --description 'Do not ask any questions, always use default values.'
complete -c spd-conf -l test-alsa --description 'Test ALSA audio.'
complete -c spd-conf -l test-espeak --description 'Test whether Espeak works as a standalone binary.'
complete -c spd-conf -s d -l diagnostics --description 'Diagnose problems with the current setup.'
complete -c spd-conf -s D -l debug --description 'Debug a problem and generate a report AUTHOR sp… [See Man Page]'

