# splitindex
# Autogenerated from man page /usr/share/man/man1/splitindex.1.gz
# using Deroffing man parser
complete -c splitindex -s h -l help --description 'show this help and terminate.'
complete -c splitindex -s m -l makeindex --description 'call PROGNAME instead of default `makeindex\'.'
complete -c splitindex -s i -l identify --description 'use regular EXPRESSION to match entries (see al… [See Man Page]'
complete -c splitindex -s r -l resultis --description 'create line to be written from PATTERN after ma… [See Man Page]'
complete -c splitindex -s s -l suffixis --description 'create suffix to be used from PATTERN after mat… [See Man Page]'
complete -c splitindex -s v -l verbose --description 'be more verbose (can be used multiple to increase verbosity).'
complete -c splitindex -l version --description 'show version and terminate COPYRIGHT Copyright … [See Man Page]'

