# ssconvert
# Autogenerated from man page /usr/share/man/man1/ssconvert.1.gz
# using Deroffing man parser
complete -c ssconvert -l recalc --description 'Recalculate all cells before writing the result.'
complete -c ssconvert -l list-exporters --description 'List the available exporters (file formats that… [See Man Page]'
complete -c ssconvert -s T -l export-type --description 'Specify which exporter to use; see below for a list.'
complete -c ssconvert -s O -l export-options --description 'Specify parameters for the chosen exporter.'
complete -c ssconvert -l list-importers --description 'List the available importers (file formats that can be read).'
complete -c ssconvert -s E -l import-encoding --description 'Specify an encoding for imported content.'
complete -c ssconvert -s M -l merge-to --description 'Merge a collection of workbooks into one.'
complete -c ssconvert -s S -l export-file-per-sheet --description 'Export a file for each sheet if the exporter on… [See Man Page]'
complete -c ssconvert -s v -l version --description 'Display ssconvert\'s version.'
complete -c ssconvert -s h -l help -l usage --description 'Display a brief usage message.'
complete -c ssconvert -l help-all --description 'Show all help options.'
complete -c ssconvert -l help-libspreadsheet --description 'Show Gnumeric options. SS "Path options".'
complete -c ssconvert -s L -l lib-dir --description 'Set the root library directory.'
complete -c ssconvert -s I -l import-type --description 'Specify which importer to use; see below for a list.'
complete -c ssconvert -s D -l data-dir --description 'Adjust the root data directory.'

