# ssgrep
# Autogenerated from man page /usr/share/man/man1/ssgrep.1.gz
# using Deroffing man parser
complete -c ssgrep -l recalc --description 'Recalculate all cells  .'
complete -c ssgrep -s f -l keyword-file --description 'The path to a text file containing one key per line.'
complete -c ssgrep -s i -l ignore-case --description 'Ignore differences in letter case.'
complete -c ssgrep -s w -l word-regexp --description 'Match only whole words.'
complete -c ssgrep -s F -l fixed-strings --description 'Pattern is a set of fixed strings.'
complete -c ssgrep -s R -l search-results --description 'Search results of expressions too.'
complete -c ssgrep -s v -l invert-match --description 'Search for cells that do not match  .'
complete -c ssgrep -s c -l count --description 'Only print a count of matches per file.'
complete -c ssgrep -s L -l files-without-matches --description 'Print filenames without matches.'
complete -c ssgrep -s l -l files-with-matches --description 'Print filenames with matches.'
complete -c ssgrep -s q -l quiet --description 'Suppress all normal output.'
complete -c ssgrep -s H -l with-filename --description 'Print the filename for each match.'
complete -c ssgrep -s h -l without-filename --description 'Do not print the filename for each match.'
complete -c ssgrep -s n -l print-locus --description 'Print the location of each match.'
complete -c ssgrep -s T -l print-type --description 'Print the location type of each match  . SS "Help options".'
complete -c ssgrep -s V -l version --description 'Display ssgrep\'s version.'
complete -c ssgrep -s '?' -l help --description 'Display the supported options.'
complete -c ssgrep -l usage --description 'Display a brief usage message EXAMPLE To search… [See Man Page]'

