# st
# Autogenerated from man page /usr/share/man/man1/st.1.gz
# using Deroffing man parser
complete -c st -s t --description 'Overrides the default title (st).'
complete -c st -s c --description 'Overrides the default class ($TERM).'
complete -c st -s v --description 'Prints version information to standard output, then exits.'
complete -c st -s e --description 'Execute cmd instead of the shell.'

