# startx
# Autogenerated from man page /usr/share/man/man1/startx.1.gz
# using Deroffing man parser
complete -c startx -o auth --description 'argument, from automatically setting up insecur… [See Man Page]'

