# start
# Autogenerated from man page /usr/share/man/man8/start.8.gz
# using Deroffing man parser
complete -c start -l session --description 'Connect to  init (8) daemon using the D-Bus ses… [See Man Page]'
complete -c start -l system --description 'Communication with the  init (8) daemon is norm… [See Man Page]'
complete -c start -l dest --description 'Specifies the well-known name of the  init (8) … [See Man Page]'
complete -c start -l no-wait --description 'Applies to the  start ", " stop ", " restart " … [See Man Page]'
complete -c start -l quiet --description 'Reduces output of all commands to errors only.'
complete -c start -s e -l enumerate --description '.'
complete -c start -s i -l ignore-events --description '.'
complete -c start -s w -l warn --description 'If specified, treat any unknown jobs and events as errors.'

