# stat
# Autogenerated from man page /usr/share/man/man1/stat.1.gz
# using Deroffing man parser
complete -c stat -s L -l dereference --description 'follow links.'
complete -c stat -s f -l file-system --description 'display file system status instead of file status.'
complete -c stat -s c -l format --description 'use the specified FORMAT instead of the default… [See Man Page]'
complete -c stat -l printf --description 'like --format, but interpret backslash escapes,… [See Man Page]'
complete -c stat -s t -l terse --description 'print the information in terse form.'
complete -c stat -l help --description 'display this help and exit.'
complete -c stat -l version --description 'output version information and exit .'

