# su
# Autogenerated from man page /usr/share/man/man1/su.1.gz
# using Deroffing man parser
complete -c su -s c -l command --description 'Specify a command that will be invoked by the s… [See Man Page]'
complete -c su -s l -l login --description 'Provide an environment similar to what the user… [See Man Page]'
complete -c su -o 'c.' --description '.'
complete -c su -l 'login)' --description '.'
complete -c su -s s -l shell --description '.'
complete -c su -l preserve-environment --description 'is used, the shell specified by the $SHELL envi… [See Man Page]'
complete -c su -s m -s p --description '.'

