# sudoreplay
# Autogenerated from man page /usr/share/man/man8/sudoreplay.8.gz
# using Type1
complete -c sudoreplay -s d --description 'Use directory to for the session logs instead o… [See Man Page]'
complete -c sudoreplay -s f --description 'By default, sudoreplay will play back the comma… [See Man Page]'
complete -c sudoreplay -s h --description 'The -h (help) option causes sudoreplay to print… [See Man Page]'
complete -c sudoreplay -s l --description 'Enable \\*(L"list mode\\*(R".'
complete -c sudoreplay -s m --description 'Specify an upper bound on how long to wait betw… [See Man Page]'
complete -c sudoreplay -s s --description 'This option causes sudoreplay to adjust the num… [See Man Page]'
complete -c sudoreplay -s V --description 'The -V (version) option causes sudoreplay to pr… [See Man Page]'

