# sundancer2
# Autogenerated from man page /usr/share/man/man1/sundancer2.1.gz
# using Deroffing man parser
complete -c sundancer2 -l root --description 'Draw on the root window.'
complete -c sundancer2 -l maxfps --description 'Set maximum frame rate.'
complete -c sundancer2 -l vsync --description 'Limit redraws to specified number of vertical refreshes.'
complete -c sundancer2 -l dpms --description 'Stop rendering new frames if the display is not on.   0 - 1.'
complete -c sundancer2 -l quad_count --description 'Set number of stacked quads.   1 - 300.   Default: 150.'
complete -c sundancer2 -l speed --description 'Rotational speed.   1 - 40.   Default: 20.'
complete -c sundancer2 -l transparency --description 'Percentage of transparency.   1 - 100.   Default: 75.'
complete -c sundancer2 -l foreground --description 'Color for the top of the heap using hex color codes.'
complete -c sundancer2 -l background --description 'Color for the bottom of the heap using hex color codes.'
complete -c sundancer2 -l reverse --description 'Reverse rotation occasionally.'

