# svn-hot-backup
# Autogenerated from man page /usr/share/man/man1/svn-hot-backup.1.gz
# using Deroffing man parser
complete -c svn-hot-backup -l archive-type --description 'PD Create a compressed archive of the backup, in R . tar.'
complete -c svn-hot-backup -s h -l help --description 'Print this help message and exit.'

