# svnserve
# Autogenerated from man page /usr/share/man/man8/svnserve.8.gz
# using Deroffing man parser
complete -c svnserve -s d -l daemon --description 'Causes svnserve to run in daemon mode.'
complete -c svnserve -l listen-port --description 'Causes svnserve to listen on port when run in daemon mode.'
complete -c svnserve -l listen-host --description 'Causes svnserve to listen on the interface spec… [See Man Page]'
complete -c svnserve -l foreground --description 'When used together with -d, this option causes … [See Man Page]'
complete -c svnserve -s i -l inetd --description 'Causes svnserve to use the stdin/stdout file de… [See Man Page]'
complete -c svnserve -s h -l help --description 'Displays a usage summary and exits.'
complete -c svnserve -l version --description 'Print svnserve\'s version and the repository fil… [See Man Page]'
complete -c svnserve -s r -l root --description 'Sets the virtual root for repositories served by svnserve.'
complete -c svnserve -s R -l read-only --description 'Force all write operations through this svnserv… [See Man Page]'
complete -c svnserve -s t -l tunnel --description 'Causes svnserve to run in tunnel mode, which is… [See Man Page]'
complete -c svnserve -l tunnel-user --description 'When combined with --tunnel, overrides the pre-… [See Man Page]'
complete -c svnserve -s T -l threads --description 'When running in daemon mode, causes svnserve to… [See Man Page]'
complete -c svnserve -l config-file --description 'When specified, svnserve reads filename once at… [See Man Page]'
complete -c svnserve -l pid-file --description 'When specified, svnserve will write its process ID to filename.'
complete -c svnserve -s X -l listen-once --description 'Causes svnserve to accept one connection on the… [See Man Page]'

