# swath
# Autogenerated from man page /usr/share/man/man1/swath.1.gz
# using Deroffing man parser
complete -c swath -s b --description 'Define a string to be used as word delimitor co… [See Man Page]'
complete -c swath -s d --description 'Specify alternative dictionary location.'
complete -c swath -s f --description 'Specify format of the input.'
complete -c swath -s m --description 'Choose word matching scheme when analyzing word boundaries.'
complete -c swath -s u --description 'Specify encodings of input and output.'
complete -c swath -s v -l verbose --description 'Turn on verbose mode.'
complete -c swath -o help -l help --description 'Show help.'

