# switch_root
# Autogenerated from man page /usr/share/man/man8/switch_root.8.gz
# using Deroffing man parser
complete -c switch_root -s h -l help --description 'show help and exit.'
complete -c switch_root -s V -l version --description 'show version number and exit.'

