# system-config-printer-applet
# Autogenerated from man page /usr/share/man/man1/system-config-printer-applet.1.gz
# using Deroffing man parser
complete -c system-config-printer-applet -l help --description 'Display a short usage message.'
complete -c system-config-printer-applet -l version --description 'Display the version of the applet.'
complete -c system-config-printer-applet -l debug --description 'Show debugging information.'
complete -c system-config-printer-applet -l no-tray-icon --description 'option: a desktop file is provided for this, so… [See Man Page]'

