# t1binary
# Autogenerated from man page /usr/share/man/man1/t1binary.1.gz
# using Deroffing man parser
complete -c t1binary -l block-length -s l --description 'Set the maximum length of sections in PFB output to length.'

