# tangle
# Autogenerated from man page /usr/share/man/man1/tangle.1.gz
# using Type1
complete -c tangle -l help --description 'Print help message and exit.'
complete -c tangle -l length --description 'Compare only the first  number characters of id… [See Man Page]'
complete -c tangle -l loose --description 'When checking for collisions between identifier… [See Man Page]'
complete -c tangle -l lowercase --description 'Convert all identifiers to lowercase.'
complete -c tangle -l mixedcase --description 'Retain the case of identifiers.   This is the default.'
complete -c tangle -l strict --description 'When checking for collisions between identifier… [See Man Page]'
complete -c tangle -l underline --description 'Retain underlines (also known as underscores) in identifiers.'
complete -c tangle -l uppercase --description 'Convert all identifiers to uppercase.'

