# taskset
# Autogenerated from man page /usr/share/man/man1/taskset.1.gz
# using Deroffing man parser
complete -c taskset -s a -l all-tasks --description 'Set or retrieve the CPU affinity of all the tas… [See Man Page]'
complete -c taskset -s p -l pid --description 'Operate on an existing PID and do not launch a new task.'
complete -c taskset -s c -l cpu-list --description 'Specify a numerical list of processors instead of a bitmask.'
complete -c taskset -s h -l help --description 'Display usage information and exit.'
complete -c taskset -s V -l version --description 'Display version information and exit.  USAGE.'

