# tc-prio
# Autogenerated from man page /usr/share/man/man8/tc-prio.8.gz
# using Deroffing man parser
complete -c tc-prio -l --------------------------------------- --description '1000   8         Minimize delay (md) 0100   4  … [See Man Page]'
complete -c tc-prio -l ---------------------------------------------------------- --description '0x0     0     Normal Service           0 Best E… [See Man Page]'

