# tempfile
# Autogenerated from man page /usr/share/man/man1/tempfile.1.gz
# using Deroffing man parser
complete -c tempfile -s d -l directory --description 'Place the file in DIR.'
complete -c tempfile -s m -l mode --description 'Open the file with MODE instead of 0600.'
complete -c tempfile -s n -l name --description 'Use FILE for the name instead of  tempnam (3) .'
complete -c tempfile -s p -l prefix --description 'Use up to five letters of STRING to generate the name.'
complete -c tempfile -s s -l suffix --description 'Generate the file with STRING as the suffix.'
complete -c tempfile -l help --description 'Print a usage message on standard output and exit successfully.'
complete -c tempfile -l version --description 'Print version information on standard output an… [See Man Page]'

