# testrb1
# Autogenerated from man page /usr/share/man/man1/testrb1.8.1.gz
# using Deroffing man parser
complete -c testrb1 -s r -l runner --description 'Use the given RUNNER.   (t[k], c[onsole], g[tk], f[ox]).'
complete -c testrb1 -s a -l add --description 'Add TORUN to the list of things to run;  can be… [See Man Page]'
complete -c testrb1 -s p -l pattern --description 'Match files to collect against PATTERN.'
complete -c testrb1 -s n -l name --description 'Runs tests matching NAME.   (patterns may be used. ).'
complete -c testrb1 -s t -l testcase --description 'Runs tests in TestCases matching TESTCASE.'
complete -c testrb1 -s v -l verbose --description 'Set the output level (default is verbose).'
complete -c testrb1 -s h -l help --description 'Display help.  AUTHOR.'

