# texconfig-sys
# Autogenerated from man page /usr/share/man/man1/texconfig-sys.1.gz
# using Deroffing man parser
complete -c texconfig-sys -s P --description 'option is given.'
complete -c texconfig-sys -s O --description 'option in dvips(1).'

