# texdoc
# Autogenerated from man page /usr/share/man/man1/texdoc.1.gz
# using Deroffing man parser
complete -c texdoc -s f -l files --description 'Print the name of the config files being used.'
complete -c texdoc -s w -l view --description 'Use view mode: start a viewer.'
complete -c texdoc -s m -l mixed --description 'Use mixed mode (view or list).'
complete -c texdoc -s l -l list --description 'Use list mode: show a list of results.'
complete -c texdoc -s s -l showall --description 'Use showall mode: show also "bad" results.'
complete -c texdoc -s r -l regex --description 'Use regex mode.  (Deprecated. ).'
complete -c texdoc -s e -l extensions --description 'Set ext_list=L.  (Deprecated. ).'
complete -c texdoc -s a -l alias --description 'Use the alias table.'
complete -c texdoc -s A -l noalias --description 'Don\'t use the alias table.'
complete -c texdoc -s i -l interact --description 'Use interactive menus.'
complete -c texdoc -s I -l nointeract --description 'Use plain lists, no interaction required.'
complete -c texdoc -s v -l verbosity --description 'Set verbosity level to N.'
complete -c texdoc -s d -l 'debug[' --description 'Activate debug for selected items (default all).'
complete -c texdoc -s M -l machine --description 'Use a more machine-friendly output format.'

