# texlinks
# Autogenerated from man page /usr/share/man/man1/texlinks.1.gz
# using Type1
complete -c texlinks -l cnffile -s f --description 'use file as configuration file (default: fmtutil. cnf).'
complete -c texlinks -l help -s h --description 'show some help text.'
complete -c texlinks -l multiplatform -s m --description 'operate in all platform-specific directories (d… [See Man Page]'
complete -c texlinks -l silent -s s --description 'silently skip over existing scripts/binaries in… [See Man Page]'
complete -c texlinks -l unlink -s u --description 'Unlink previously created symlinks.'

