# thinkjettopbm
# Autogenerated from man page /usr/share/man/man1/thinkjettopbm.1.gz
# using Deroffing man parser
complete -c thinkjettopbm -s d --description 'option turns on debugging messages which are wr… [See Man Page]'

