# Thunar
# Autogenerated from man page /usr/share/man/man1/Thunar.1.gz
# using Deroffing man parser
complete -c Thunar -l bulk-rename --description 'option is specified no file managers windows wi… [See Man Page]'
complete -c Thunar -s '?' -l help --description '.'
complete -c Thunar -s v -l version --description '.'
complete -c Thunar -s B --description '.'
complete -c Thunar -l daemon --description '.'
complete -c Thunar -l display --description '.'
complete -c Thunar -s q -l quit --description '.'

