# time
# Autogenerated from man page /usr/share/man/man1/time.1.gz
# using Deroffing man parser
complete -c time -s o -l output --description 'Write the resource use statistics to   FILE  in… [See Man Page]'
complete -c time -s a -l append --description 'Append the resource use information to the outp… [See Man Page]'
complete -c time -s f -l format --description 'Use   FORMAT  as the format string that control… [See Man Page]'
complete -c time -l help --description 'Print a summary of the command line options and exit.'
complete -c time -s p -l portability --description 'Use the following format string, for conformanc… [See Man Page]'
complete -c time -s v -l verbose --description 'Use the built-in verbose format, which displays… [See Man Page]'
complete -c time -l quiet --description 'Do not report the status of the program even if… [See Man Page]'
complete -c time -s V -l version --description 'Print the version number of  time  and exit.'

