# tracepath6
# Autogenerated from man page /usr/share/man/man8/tracepath6.8.gz
# using Type1
complete -c tracepath6 -s n --description 'Print primarily IP addresses numerically.'
complete -c tracepath6 -s b --description 'Print both of host names and IP addresses.'

