# ttftotype42
# Autogenerated from man page /usr/share/man/man1/ttftotype42.1.gz
# using Deroffing man parser
complete -c ttftotype42 -s o -l output --description 'Write output font to R file instead of the standard output.'
complete -c ttftotype42 -s q -l quiet --description 'Do not generate any error messages.  \' . Sp.'
complete -c ttftotype42 -s h -l help --description 'Print usage information and exit.  \' . Sp.'
complete -c ttftotype42 -s v -l version --description 'Print the version number and some short non-war… [See Man Page]'

