# ucs2any
# Autogenerated from man page /usr/share/man/man1/ucs2any.1.gz
# using Deroffing man parser
complete -c ucs2any -s d --description 'omits DEC VT100 graphics characters from the C0… [See Man Page]'

