# udevd
# Autogenerated from man page /usr/share/man/man8/udevd.8.gz
# using Deroffing man parser
complete -c udevd -l daemon --description 'Detach and run in the background.'
complete -c udevd -l debug --description 'Print debug messages to stderr.'
complete -c udevd -l children-max --description 'Limit the number of parallel executed events.'
complete -c udevd -l exec-delay --description 'Number of seconds to delay the execution of RUN instructions.'
complete -c udevd -l resolve-names --description 'Specify when udevd should resolve names of users and groups.'
complete -c udevd -l version --description 'Print version number.'
complete -c udevd -l help --description 'Print help text.'

