# ufw
# Autogenerated from man page /usr/share/man/man8/ufw.8.gz
# using Deroffing man parser
complete -c ufw -l version --description 'show program\'s version number and exit.'
complete -c ufw -s h -l help --description 'show help message and exit.'
complete -c ufw -l dry-run --description 'don\'t modify anything, just show the changes.'
complete -c ufw -l force --description '.'
complete -c ufw -l add-new --description 'allow or deny so the update --add-new command m… [See Man Page]'

