# ul
# Autogenerated from man page /usr/share/man/man1/ul.1.gz
# using Darwin man parser
complete -c ul -s i --description 'Underlining is indicated by a separate line con… [See Man Page]'
complete -c ul -s t --description 'Overrides the terminal type specified in the en… [See Man Page]'

