# unclutter
# Autogenerated from man page /usr/share/man/man1/unclutter.1.gz
# using Deroffing man parser
complete -c unclutter -o display --description 'is followed by the display to open.'
complete -c unclutter -o idle --description 'is followed by the number of seconds between po… [See Man Page]'
complete -c unclutter -o keystroke --description 'tells  unclutter not to use a timeout to determ… [See Man Page]'
complete -c unclutter -o jitter --description 'is followed by the amount of movement of the po… [See Man Page]'
complete -c unclutter -o grab --description 'means use the original method of grabbing the p… [See Man Page]'
complete -c unclutter -o noevents --description 'stops unclutter sending a pseudo EnterNotify ev… [See Man Page]'
complete -c unclutter -o reset --description 'resets the timeout for idleness after the curso… [See Man Page]'
complete -c unclutter -o root --description 'means remove the cursor even if it is on the ro… [See Man Page]'
complete -c unclutter -o onescreen --description 'restricts unclutter to the single screen specif… [See Man Page]'
complete -c unclutter -o visible --description 'ignore visibility events (does not apply to -grab).'
complete -c unclutter -o not --description 'is followed by a list of window names where the… [See Man Page]'
complete -c unclutter -o notname --description 'is exactly the same as -not.'
complete -c unclutter -o notclass --description 'is similar to -notname, except that the WM_CLAS… [See Man Page]'
complete -c unclutter -o regex --description 'treats the first name or class (see above) as a… [See Man Page]'

