# unity-2d-shell
# Autogenerated from man page /usr/share/man/man1/unity-2d-shell.1.gz
# using Deroffing man parser
complete -c unity-2d-shell -o opengl --description 'Run the application using an openGL-enabled widget.'

