# unrar
# Autogenerated from man page /usr/share/man/man1/unrar.1.gz
# using Deroffing man parser
complete -c unrar -o av- --description 'Disable Authenticity Verification check.'
complete -c unrar -o c- --description 'Disable comments show.'
complete -c unrar -s f --description 'Freshen files.'
complete -c unrar -o kb --description 'Keep broken extracted files.'
complete -c unrar -o ierr --description 'Send all messages to stderr.'
complete -c unrar -o inul --description 'Disable all messages.'
complete -c unrar -o o+ --description 'Overwrite existing files.'
complete -c unrar -o o- --description 'Do not overwrite existing files.'
complete -c unrar -o 'p<password>' --description 'Set password.'
complete -c unrar -o p- --description 'Do not query password.'
complete -c unrar -s r --description 'Recurse subdirectories.'
complete -c unrar -s u --description 'Update files.'
complete -c unrar -s v --description 'List all volumes.'
complete -c unrar -o 'x<file>' --description 'Exclude specified file.'
complete -c unrar -o 'x@<list>' --description 'Exclude files in specified list file.'
complete -c unrar -o x@ --description 'Read file names to exclude from stdin.'
complete -c unrar -s y --description 'Assume Yes on all queries.'

