# unshare
# Autogenerated from man page /usr/share/man/man1/unshare.1.gz
# using Deroffing man parser
complete -c unshare -s h -l help --description 'Print a help message,.'
complete -c unshare -s m -l mount --description 'Unshare the mount namespace,.'
complete -c unshare -s u -l uts --description 'Unshare the UTC namespace,.'
complete -c unshare -s i -l ipc --description 'Unshare the IPC namespace,.'
complete -c unshare -s n -l net --description 'Unshare the network namespace.'

