# unstr
# Autogenerated from man page /usr/share/man/man1/unstr.1.gz
# using Deroffing man parser
complete -c unstr -s c --description 'Change the delimiting character from the percen… [See Man Page]'
complete -c unstr -s i --description 'Ignore case when ordering the strings.'
complete -c unstr -s o --description 'Order the strings in alphabetical order.'
complete -c unstr -s r --description 'Randomize access to the strings.'
complete -c unstr -s s --description 'Run silently; don\'t give a summary message when finished.'
complete -c unstr -s x --description 'Note that each alphabetic character in the grou… [See Man Page]'

