# update-java-alternatives
# Autogenerated from man page /usr/share/man/man8/update-java-alternatives.8.gz
# using Deroffing man parser
complete -c update-java-alternatives -s l -l list --description 'List all installed packages (or just <jname>) p… [See Man Page]'
complete -c update-java-alternatives -s a -l auto --description 'Switch all alternatives of registered jre/sdk i… [See Man Page]'
complete -c update-java-alternatives -s s -l set --description 'Set all alternatives of the registered jre/sdk … [See Man Page]'
complete -c update-java-alternatives -l jre --description 'Limit the actions to alternatives belong to a r… [See Man Page]'
complete -c update-java-alternatives -l jre-headless --description 'Limit the actions to alternatives belong to the… [See Man Page]'
complete -c update-java-alternatives -l plugin --description 'Limit the actions to alternatives providing browser plugins.'
complete -c update-java-alternatives -s h -l help --description 'Display a help message.'
complete -c update-java-alternatives -s t -l test --description 'Don\'t actually do anything, just say what would be done.'
complete -c update-java-alternatives -s v -l verbose --description 'Verbose output.'

