# update-mime
# Autogenerated from man page /usr/share/man/man8/update-mime.8.gz
# using Deroffing man parser
complete -c update-mime -l local --description 'Generate files in the current user\'s home direc… [See Man Page]'

