# update-updmap
# Autogenerated from man page /usr/share/man/man1/update-updmap.1.gz
# using Deroffing man parser
complete -c update-updmap -s c -l conf-dir --description 'directory where the user-specific configuration… [See Man Page]'
complete -c update-updmap -s o -l output-file --description 'file to write the output to.'
complete -c update-updmap -l checks --description 'perform sanity checks on the generated config file.'
complete -c update-updmap -l quiet --description 'don\'t write anything to the standard output dur… [See Man Page]'
complete -c update-updmap -l help --description 'print a summary of the command-line usage and exit.'
complete -c update-updmap -l version --description 'output version information and exit.'

