# update-fonts-dir
# Autogenerated from man page /usr/share/man/man8/update-fonts-dir.8.gz
# using Deroffing man parser
complete -c update-fonts-dir -s h -l help --description 'displays a brief usage message and exits.'
complete -c update-fonts-dir -s 7 -l x11r7-layout --description 'switches the font layout to the one introduced … [See Man Page]'

