# update-gconf-defaults
# Autogenerated from man page /usr/share/man/man8/update-gconf-defaults.8.gz
# using Deroffing man parser
complete -c update-gconf-defaults -l source --description 'Specify an alternate source directory where to … [See Man Page]'
complete -c update-gconf-defaults -l destination --description 'Specify an alternate destination directory wher… [See Man Page]'
complete -c update-gconf-defaults -l mandatory --description 'Sets source and destination directories appropr… [See Man Page]'

