# updatedb
# Autogenerated from man page /usr/share/man/man8/updatedb.8.gz
# using Deroffing man parser
complete -c updatedb -s f -l add-prunefs --description 'Add entries in white-space-separated list FS to PRUNEFS.'
complete -c updatedb -s n -l add-prunenames --description 'Add entries in white-space-separated list NAMES to PRUNENAMES.'
complete -c updatedb -s e -l add-prunepaths --description 'Add entries in white-space-separated list PATHS to PRUNEPATHS.'
complete -c updatedb -s U -l database-root --description 'Store only results of scanning the file system … [See Man Page]'
complete -c updatedb -l debug-pruning --description 'Write debugging information about pruning decis… [See Man Page]'
complete -c updatedb -s h -l help --description 'Write a summary of the available options to sta… [See Man Page]'
complete -c updatedb -s o -l output --description 'Write the database to  FILE instead of using th… [See Man Page]'
complete -c updatedb -l prune-bind-mounts --description 'Set  PRUNE_BIND_MOUNTS to FLAG, overriding the … [See Man Page]'
complete -c updatedb -l prunefs --description 'Set PRUNEFS to FS, overriding the configuration file.'
complete -c updatedb -l prunenames --description 'Set PRUNENAMES to NAMES, overriding the configuration file.'
complete -c updatedb -l prunepaths --description 'Set PRUNEPATHS to PATHS, overriding the configuration file.'
complete -c updatedb -s l -l require-visibility --description 'Set the \\*(lqrequire file visibility before rep… [See Man Page]'
complete -c updatedb -s v -l verbose --description 'Output path names of files to standard output, … [See Man Page]'
complete -c updatedb -s V -l version --description 'Write information about the version and licence… [See Man Page]'

