# update-fonts-scale
# Autogenerated from man page /usr/share/man/man8/update-fonts-scale.8.gz
# using Deroffing man parser
complete -c update-fonts-scale -s h -l help --description 'displays a brief usage message and exits.'

