# update-exim4
# Autogenerated from man page /usr/share/man/man8/update-exim4.conf.template.8.gz
# using Deroffing man parser
complete -c update-exim4 -s n -l nobackup --description 'Overwrite existing file, instead of keeping it … [See Man Page]'
complete -c update-exim4 -s r -l run --description 'Actually do something.'
complete -c update-exim4 -l 'output).' --description '.'

