# update-mime-database
# Autogenerated from man page /usr/share/man/man1/update-mime-database.1.gz
# using Deroffing man parser
complete -c update-mime-database -s h --description 'Print out a command summary.'
complete -c update-mime-database -s v --description 'Print out the version information.'
complete -c update-mime-database -s V --description 'Be verbose.'

