# update-catalog
# Autogenerated from man page /usr/share/man/man8/update-catalog.8.gz
# using Deroffing man parser
complete -c update-catalog -l add --description 'Adds an entry for the  centralized_catalog in t… [See Man Page]'
complete -c update-catalog -l remove --description 'Removes the entry for the  centralized_catalog … [See Man Page]'
complete -c update-catalog -l quiet --description 'Prevents the usual diagnostic output.'
complete -c update-catalog -l test --description 'Prevents the update of the catalog and writes t… [See Man Page]'
complete -c update-catalog -l version --description 'Displays the version information and exits.'
complete -c update-catalog -l help --description 'Display the usage information and exits.'

