# update-language-def
# Autogenerated from man page /usr/share/man/man1/update-language-def.1.gz
# using Deroffing man parser
complete -c update-language-def -s c -l conf-dir --description 'directory where the user-specific configuration… [See Man Page]'
complete -c update-language-def -s o -l output-file --description 'file to write the output to.'
complete -c update-language-def -l checks --description 'perform sanity checks on the generated config file.'
complete -c update-language-def -l quiet --description 'don\'t write anything to the standard output dur… [See Man Page]'
complete -c update-language-def -l help --description 'print a summary of the command-line usage and exit.'
complete -c update-language-def -l version --description 'output version information and exit.'

