# updmap-sys
# Autogenerated from man page /usr/share/man/man1/updmap-sys.1.gz
# using Type1
complete -c updmap-sys -l cnffile --description 'Specify a configuration file.'
complete -c updmap-sys -l dvipsoutputdir --description 'Specify the output directory for map files gene… [See Man Page]'
complete -c updmap-sys -l pdftexoutputdir --description 'Specify the output directory for map files gene… [See Man Page]'
complete -c updmap-sys -l dvipdfmoutputdir --description 'Specify the output directory for map files gene… [See Man Page]'
complete -c updmap-sys -l outputdir --description 'Specify the output directory for all generated map files.'
complete -c updmap-sys -l nohash --description 'Do not run texhash(1).'
complete -c updmap-sys -l nomkmap --description 'Do not recreate existing map files.'
complete -c updmap-sys -l quiet --description 'Reduce verbosity.'
complete -c updmap-sys -l edit --description 'Edit the updmap. cfg file.'
complete -c updmap-sys -l help --description 'Show a command and option summary.'
complete -c updmap-sys -l showoptions --description 'Show alternatives for option item.'
complete -c updmap-sys -l setoption --description 'Set option to value, where option is one of:.'
complete -c updmap-sys -l enable --description 'Permanently add or enable a Map or MixedMap for mapfile.'
complete -c updmap-sys -l disable --description 'Disable Map or MixedMap for mapfile.'
complete -c updmap-sys -l syncwithtrees --description 'Disable entries in the config file that refer t… [See Man Page]'
complete -c updmap-sys -l listmaps --description 'List all active and inactive maps.'

