# updmap
# Autogenerated from man page /usr/share/man/man1/updmap.1.gz
# using Type1
complete -c updmap -l cnffile --description 'Specify a configuration file.'
complete -c updmap -l dvipsoutputdir --description 'Specify the output directory for map files gene… [See Man Page]'
complete -c updmap -l pdftexoutputdir --description 'Specify the output directory for map files gene… [See Man Page]'
complete -c updmap -l dvipdfmoutputdir --description 'Specify the output directory for map files gene… [See Man Page]'
complete -c updmap -l outputdir --description 'Specify the output directory for all generated map files.'
complete -c updmap -l nohash --description 'Do not run texhash(1).'
complete -c updmap -l nomkmap --description 'Do not recreate existing map files.'
complete -c updmap -l quiet --description 'Reduce verbosity.'
complete -c updmap -l edit --description 'Edit the updmap. cfg file.'
complete -c updmap -l help --description 'Show a command and option summary.'
complete -c updmap -l showoptions --description 'Show alternatives for option item.'
complete -c updmap -l setoption --description 'Set option to value, where option is one of:.'
complete -c updmap -l enable --description 'Permanently add or enable a Map or MixedMap for mapfile.'
complete -c updmap -l disable --description 'Disable Map or MixedMap for mapfile.'
complete -c updmap -l syncwithtrees --description 'Disable entries in the config file that refer t… [See Man Page]'
complete -c updmap -l listmaps --description 'List all active and inactive maps.'

