# ureadahead
# Autogenerated from man page /usr/share/man/man8/ureadahead.8.gz
# using Deroffing man parser
complete -c ureadahead -l verbose --description 'May be used to report on  ureadahead \'s operation.'
complete -c ureadahead -l daemon --description 'Places  ureadahead into the background once the… [See Man Page]'
complete -c ureadahead -l force-trace --description 'Discards all pack files and forces re-tracing. \\".'
complete -c ureadahead -l timeout --description 'Normally when tracing,  ureadahead will wait fo… [See Man Page]'
complete -c ureadahead -l dump --description 'Dump the contents of the pack file to standard … [See Man Page]'
complete -c ureadahead -l sort --description 'Used with.'

