# usermod
# Autogenerated from man page /usr/share/man/man8/usermod.8.gz
# using Deroffing man parser
complete -c usermod -s a -l append --description 'Add the user to the supplementary group(s).'
complete -c usermod -s c -l comment --description 'The new value of the user\\*(Aqs password file comment field.'
complete -c usermod -s d -l home --description 'The user\\*(Aqs new login directory.'
complete -c usermod -s e -l expiredate --description 'The date on which the user account will be disabled.'
complete -c usermod -s f -l inactive --description 'The number of days after a password expires unt… [See Man Page]'
complete -c usermod -s g -l gid --description 'The group name or number of the user\\*(Aqs new … [See Man Page]'
complete -c usermod -s G -l groups --description 'A list of supplementary groups which the user i… [See Man Page]'
complete -c usermod -s l -l login --description 'The name of the user will be changed from LOGIN to NEW_LOGIN.'
complete -c usermod -s L -l lock --description 'Lock a user\\*(Aqs password.'
complete -c usermod -s m -l move-home --description 'Move the content of the user\\*(Aqs home directo… [See Man Page]'
complete -c usermod -s o -l non-unique --description 'When used with the -u option, this option allow… [See Man Page]'
complete -c usermod -s p -l password --description 'The encrypted password, as returned by crypt(3).'
complete -c usermod -s s -l shell --description 'The name of the user\\*(Aqs new login shell.'
complete -c usermod -s u -l uid --description 'The new numerical value of the user\\*(Aqs ID.'
complete -c usermod -s U -l unlock --description 'Unlock a user\\*(Aqs password.'
complete -c usermod -s Z -l selinux-user --description 'The SELinux user for the user\\*(Aqs login.'
complete -c usermod -o 'U.' --description '.'
complete -c usermod -l 'home)' --description 'usermod will try to adapt the ownership of the … [See Man Page]'
complete -c usermod -o 'L.' --description '.'

