# userdel
# Autogenerated from man page /usr/share/man/man8/userdel.8.gz
# using Deroffing man parser
complete -c userdel -s f -l force --description 'This option forces the removal of the user acco… [See Man Page]'
complete -c userdel -s h -l help --description 'Display help message and exit.'
complete -c userdel -s r -l remove --description 'Files in the user\\*(Aqs home directory will be … [See Man Page]'

