# uzbl
# Autogenerated from man page /usr/share/man/man1/uzbl.1.gz
# using Type1
complete -c uzbl -s u -l uri --description 'Uri to load (equivalent to \'set uri = URI\').'
complete -c uzbl -s v -l verbose --description 'Whether to print all messages or just errors.'
complete -c uzbl -s n -l name --description 'Name of the current instance (defaults to Xorg window id).'
complete -c uzbl -s c -l config --description 'Config file (this is pretty much equivalent to … [See Man Page]'
complete -c uzbl -l display --description 'X display to use.'

