# vboxmanage
# Autogenerated from man page /usr/share/man/man1/vboxmanage.1.gz
# using Deroffing man parser
complete -c vboxmanage -l storagectl --description '.'
complete -c vboxmanage -l port --description '.'
complete -c vboxmanage -l device --description '[--type dvddrive|hdd|fdd] [--medium none|emptyd… [See Man Page]'
complete -c vboxmanage -l name --description '[--add ide|sata|scsi|floppy|sas] [--controller … [See Man Page]'
complete -c vboxmanage -l size -l sizebyte --description '[--format VDI|VMDK|VHD] (default: VDI) [--varia… [See Man Page]'
complete -c vboxmanage -l target --description '.'
complete -c vboxmanage -l action --description '[--active yes|no] (yes) [--vendorid <XXXX>] (nu… [See Man Page]'
complete -c vboxmanage -l hostpath --description '[--transient] [--readonly] [--automount].'
complete -c vboxmanage -l username -l password --description '[--arguments "<arguments>"] [--environment "<NA… [See Man Page]'
complete -c vboxmanage -l 'ip<ipv4>' --description '.'
complete -c vboxmanage -l 'ipv6<ipv6>' --description 'create | remove <name>.'
complete -c vboxmanage -l ifname --description '[--ip <ip_address>.'
complete -c vboxmanage -l netmask --description '.'
complete -c vboxmanage -l lowerip --description '.'
complete -c vboxmanage -l upperip --description '[--enable | --disable].'

