# version
# Autogenerated from man page /usr/share/man/man1/version.1ssl.gz
# using Type1
complete -c version -s a --description 'all information, this is the same as setting al… [See Man Page]'
complete -c version -s v --description 'the current OpenSSL version.'
complete -c version -s b --description 'the date the current version of OpenSSL was built.'
complete -c version -s o --description 'option information: various options set when th… [See Man Page]'
complete -c version -s c --description 'compilation flags.'
complete -c version -s p --description 'platform setting.'

