# viewres
# Autogenerated from man page /usr/share/man/man1/viewres.1.gz
# using Deroffing man parser
complete -c viewres -o top --description 'This option specifies the name of the highest w… [See Man Page]'
complete -c viewres -o variable --description 'This option indicates that the widget variable … [See Man Page]'
complete -c viewres -o vertical --description 'This option indicates that the tree should be d… [See Man Page]'

