# VirtualBox
# Autogenerated from man page /usr/share/man/man1/VirtualBox.1.gz
# using Deroffing man parser
complete -c VirtualBox -l startvm --description 'start a VM by specifying its UUID or name.'
complete -c VirtualBox -l seamless --description 'switch to seamless mode during startup.'
complete -c VirtualBox -l fullscreen --description 'switch to fullscreen mode during startup.'
complete -c VirtualBox -l rmode --description 'select different render mode (default is sdl).'
complete -c VirtualBox -l no-startvm-errormsgbox --description 'do not show a message box for VM start errors.'
complete -c VirtualBox -l dbg --description 'enable the GUI debug menu.'
complete -c VirtualBox -l debug --description 'like --dbg and show debug windows at VM startup.'
complete -c VirtualBox -l debug-command-line --description 'like --dbg and show command line window at VM startup.'
complete -c VirtualBox -l debug-statistics --description 'like --dbg and show statistics window at VM startup.'
complete -c VirtualBox -l no-debug --description 'disable the GUI debug menu and debug windows.'
complete -c VirtualBox -l start-paused --description 'start the VM in the paused state.'
complete -c VirtualBox -l start-running --description 'start the VM running (for overriding --debug*) .'

