# vorbisgain
# Autogenerated from man page /usr/share/man/man1/vorbisgain.1.gz
# using Deroffing man parser
complete -c vorbisgain -s h -l help --description 'Show command help.'
complete -c vorbisgain -s a -l album --description 'Activates album mode, in which the album gain (… [See Man Page]'
complete -c vorbisgain -s g -l album-gain --description 'Sets the album gain value to use.'
complete -c vorbisgain -s c -l clean --description 'Remove any ReplayGain tags from the specified files.'
complete -c vorbisgain -s C -l convert --description 'Convert old format ReplayGain tags to a new for… [See Man Page]'
complete -c vorbisgain -s d -l display-only --description 'Display the result only; do not write anything to disk.'
complete -c vorbisgain -s f -l fast --description 'Only calculate the gain for files that do not c… [See Man Page]'
complete -c vorbisgain -s n -l no-progress --description 'Only display results, but don\'t show progress i… [See Man Page]'
complete -c vorbisgain -s q -l quiet --description 'Do not display any output while processing.'
complete -c vorbisgain -s r -l recursive --description 'Enter directories (recursively) and search for … [See Man Page]'
complete -c vorbisgain -s s -l skip --description 'Silently skip any non-Vorbis files found.'
complete -c vorbisgain -s v -l version --description 'Display the version of the program.  EXAMPLES Simplest version.'

