# winbindd
# Autogenerated from man page /usr/share/man/man8/winbindd.8.gz
# using Deroffing man parser
complete -c winbindd -s D --description 'If specified, this parameter causes the server … [See Man Page]'
complete -c winbindd -s F --description 'If specified, this parameter causes the main wi… [See Man Page]'
complete -c winbindd -s S --description 'If specified, this parameter causes winbindd to… [See Man Page]'
complete -c winbindd -s d -l debuglevel --description 'level is an integer from 0 to 10.'
complete -c winbindd -s V -l version --description 'Prints the program version number.'
complete -c winbindd -s s -l configfile --description 'The file specified contains the configuration d… [See Man Page]'
complete -c winbindd -s l -l log-basename --description 'Base directory name for log/debug files.  The extension ".'
complete -c winbindd -s h -l help --description 'Print a summary of command line options.'
complete -c winbindd -s i --description 'Tells winbindd to not become a daemon and detac… [See Man Page]'
complete -c winbindd -s n --description 'Disable caching.'
complete -c winbindd -s Y --description 'Single daemon mode.'
complete -c winbindd -s U --description 'can be any Domain user that has administrator p… [See Man Page]'

