# wish-default
# Autogenerated from man page /usr/share/man/man1/wish-default.1.gz
# using Deroffing man parser
complete -c wish-default -o encoding --description 'VS 8. 5 Specifies the encoding of the text stored in fileName.'
complete -c wish-default -o colormap --description 'Specifies that the window should have a new pri… [See Man Page]'
complete -c wish-default -o display --description 'Display (and screen) on which to display window.'
complete -c wish-default -o geometry --description 'Initial geometry to use for window.'
complete -c wish-default -o name --description 'Use name as the title to be displayed in the wi… [See Man Page]'
complete -c wish-default -o sync --description 'Execute all X server commands synchronously, so… [See Man Page]'
complete -c wish-default -o use --description 'Specifies that the main window for the applicat… [See Man Page]'
complete -c wish-default -o visual --description 'Specifies the visual to use for the window.'
complete -c wish-default -o container --description '.'

