# wrestool
# Autogenerated from man page /usr/share/man/man1/wrestool.1.gz
# using Deroffing man parser
complete -c wrestool -s x -l extract --description 'Extract resources.'
complete -c wrestool -s l -l list --description 'Output list of resources (default).'
complete -c wrestool -s t -l type -o ']ID' --description 'Resource type identifier of affected resources.'
complete -c wrestool -s n -l name --description 'Resource name identifier of affected resources.'
complete -c wrestool -s L -l language --description 'Resource language identifier.'
complete -c wrestool -l all --description 'Perform operation on all resource (default).'
complete -c wrestool -s o -l output --description 'Where to place extracted resources.'
complete -c wrestool -s R -l raw --description 'Do not parse resource contents - extract raw data.'
complete -c wrestool -s v -l verbose --description 'Explain what is being done.'
complete -c wrestool -l help --description 'Display a help message and exit.'
complete -c wrestool -l version --description 'Output version information and exit.'

