# wvgain
# Autogenerated from man page /usr/share/man/man1/wvgain.1.gz
# using Deroffing man parser
complete -c wvgain -s a --description 'album mode (all files scanned are considered an album).'
complete -c wvgain -s c --description 'clean ReplayGain values from all files.'
complete -c wvgain -s d --description 'display calculated values only (no files are modified).'
complete -c wvgain -s i --description 'ignore . wvc file (forces hybrid lossy).'
complete -c wvgain -s n --description 'new files only (skip files with track info, or … [See Man Page]'
complete -c wvgain -s s --description 'show stored values only (no analysis).'
complete -c wvgain -s q --description 'quiet (keep console output to a minimum).'

