# xbrlapi
# Autogenerated from man page /usr/share/man/man1/xbrlapi.1.gz
# using Deroffing man parser
complete -c xbrlapi -s b --description 'The  BrlAPI server to connect to.'
complete -c xbrlapi -s a --description 'The  BrlAPI authorization/authentication string.'
complete -c xbrlapi -s d --description 'The  X display to connect to.'
complete -c xbrlapi -s q --description 'Do not write any text to the braille device.'
complete -c xbrlapi -s h --description 'Print a command line usage summary and then exit.'
complete -c xbrlapi -s H --description 'Print a thorough command line usage summary and then exit.'

