# xclipboard
# Autogenerated from man page /usr/share/man/man1/xclipboard.1.gz
# using Deroffing man parser
complete -c xclipboard -s w --description 'This option indicates that lines of text that a… [See Man Page]'
complete -c xclipboard -o nw --description 'This option indicates that long lines of text s… [See Man Page]'

