# xconsole
# Autogenerated from man page /usr/share/man/man1/xconsole.1.gz
# using Deroffing man parser
complete -c xconsole -o file --description 'To monitor some other device, use this option t… [See Man Page]'
complete -c xconsole -o notify -o nonotify --description 'When new data are received from the console and… [See Man Page]'
complete -c xconsole -o daemon --description 'This option causes  xconsole to place itself in… [See Man Page]'
complete -c xconsole -o verbose --description 'When set, this option directs  xconsole to disp… [See Man Page]'
complete -c xconsole -o exitOnFail --description 'When set, this option directs  xconsole to exit… [See Man Page]'
complete -c xconsole -o saveLines --description 'When set, xconsole only preserves count lines o… [See Man Page]'

