# xfce4-appearance-settings
# Autogenerated from man page /usr/share/man/man1/xfce4-appearance-settings.1.gz
# using Deroffing man parser
complete -c xfce4-appearance-settings -s '?' -l help --description 'Show help options.'
complete -c xfce4-appearance-settings -l help-all --description 'Show all help options.'
complete -c xfce4-appearance-settings -l help-gtk --description 'Show GTK+ Options . SS "Application Options:".'
complete -c xfce4-appearance-settings -s s -l socket-id --description 'Settings manager socket.'
complete -c xfce4-appearance-settings -s v -l version --description 'Version information.'
complete -c xfce4-appearance-settings -l display --description 'X display to use COPYRIGHT Copyright © 2004-200… [See Man Page]'

