# xfce4-settings-editor
# Autogenerated from man page /usr/share/man/man1/xfce4-settings-editor.1.gz
# using Deroffing man parser
complete -c xfce4-settings-editor -s '?' -l help --description 'Show help options.'
complete -c xfce4-settings-editor -l help-all --description 'Show all help options.'
complete -c xfce4-settings-editor -l help-gtk --description 'Show GTK+ Options . SS "Application Options:".'
complete -c xfce4-settings-editor -s V -l version --description 'Version information.'
complete -c xfce4-settings-editor -l display --description 'X display to use COPYRIGHT Copyright © 2004-200… [See Man Page]'

