# xfce4-power-manager
# Autogenerated from man page /usr/share/man/man1/xfce4-power-manager.1.gz
# using Deroffing man parser
complete -c xfce4-power-manager -l no-daemon --description 'Starts the power manager in non-daemon mode: us… [See Man Page]'
complete -c xfce4-power-manager -l restart --description 'Causes the running power manager to restart.'
complete -c xfce4-power-manager -l customize --description 'Shows the configuration dialog.'
complete -c xfce4-power-manager -l quit --description 'Causes any running instance of xfce4-power-manager to exit.'

