# xfce4-settings-manager
# Autogenerated from man page /usr/share/man/man1/xfce4-settings-manager.1.gz
# using Deroffing man parser
complete -c xfce4-settings-manager -s '?' -l help --description 'Show help options.'
complete -c xfce4-settings-manager -l help-all --description 'Show all help options.'
complete -c xfce4-settings-manager -l help-gtk --description 'Show GTK+ Options . SS "Application Options:".'
complete -c xfce4-settings-manager -s V -l version --description 'Version information.'
complete -c xfce4-settings-manager -s d -l dialog --description 'Settings dialog to show.'
complete -c xfce4-settings-manager -l display --description 'X display to use COPYRIGHT Copyright © 2008    … [See Man Page]'

