# xfce4-notifyd-config
# Autogenerated from man page /usr/share/man/man1/xfce4-notifyd-config.1.gz
# using Deroffing man parser
complete -c xfce4-notifyd-config -s '?' -l help --description 'Show help.'
complete -c xfce4-notifyd-config -s V -l version --description 'Display version information.'
complete -c xfce4-notifyd-config -s s -l socket-id --description 'Settings manager socket.'
complete -c xfce4-notifyd-config -l display --description 'X display to use AUTHORS xfce4-notifyd-config w… [See Man Page]'

