# xfce4-settings-helper
# Autogenerated from man page /usr/share/man/man1/xfce4-settings-helper.1.gz
# using Deroffing man parser
complete -c xfce4-settings-helper -s '?' -l help --description 'Show help options.'
complete -c xfce4-settings-helper -l help-all --description 'Show all help options.'
complete -c xfce4-settings-helper -l help-gtk --description 'Show GTK+ Options . SS "Application Options:".'
complete -c xfce4-settings-helper -s V -l version --description 'Version information.'
complete -c xfce4-settings-helper -s d -l debug --description 'Start in debug mode (don\'t fork to the background).'
complete -c xfce4-settings-helper -l sm-client-id --description 'Client id used when resuming session.'
complete -c xfce4-settings-helper -l display --description 'X display to use COPYRIGHT Copyright © 2008    … [See Man Page]'

