# xfd
# Autogenerated from man page /usr/share/man/man1/xfd.1.gz
# using Type1
complete -c xfd -o fn --description 'This option specifies the core X server side fo… [See Man Page]'
complete -c xfd -o fa --description 'This option specifies a Xft font to be displayed.'
complete -c xfd -o box --description 'This option indicates that a box should be disp… [See Man Page]'
complete -c xfd -o center --description 'This option indicates that each glyph should be… [See Man Page]'
complete -c xfd -o start --description 'This option specifies the glyph index of the up… [See Man Page]'
complete -c xfd -o bc --description 'This option specifies the color to be used if I… [See Man Page]'
complete -c xfd -o rows --description 'This option specifies the number of rows in the grid.'

