# xfdesktop
# Autogenerated from man page /usr/share/man/man1/xfdesktop.1.gz
# using Deroffing man parser
complete -c xfdesktop -l reload --description 'Causes an already-running instance of xfdesktop… [See Man Page]'
complete -c xfdesktop -l menu --description 'Causes an already-running instance of xfdesktop… [See Man Page]'
complete -c xfdesktop -l windowlist --description 'Causes an already-running instance of xfdesktop… [See Man Page]'

