# xfsettingsd
# Autogenerated from man page /usr/share/man/man1/xfsettingsd.1.gz
# using Deroffing man parser
complete -c xfsettingsd -s '?' -l help --description 'Show help options.'
complete -c xfsettingsd -l help-all --description 'Show all help options.'
complete -c xfsettingsd -l help-gtk --description 'Show GTK+ Options . SS "Application Options:".'
complete -c xfsettingsd -s V -l version --description 'Version information.'
complete -c xfsettingsd -s v -l verbose --description 'Verbose output.'
complete -c xfsettingsd -s f -l force --description 'Replace running xsettings daemon (if any).'
complete -c xfsettingsd -s d -l debug --description 'Start in debug mode (don\'t fork to the background).'
complete -c xfsettingsd -l display --description 'X display to use.'

