# xgamma
# Autogenerated from man page /usr/share/man/man1/xgamma.1.gz
# using Deroffing man parser
complete -c xgamma -o display --description 'This argument allows you to specify the server … [See Man Page]'
complete -c xgamma -o screen --description 'When multiple displays are configured as a sing… [See Man Page]'
complete -c xgamma -o quiet --description 'Silence the normal output of  xgamma . PP.'
complete -c xgamma -o help --description 'Print out the `Usage:\' command syntax summary. PP.'
complete -c xgamma -o gamma --description 'The gamma correction can either be defined as a… [See Man Page]'
complete -c xgamma -o rgamma --description 'This argument specifies the red component of th… [See Man Page]'
complete -c xgamma -o ggamma --description 'This argument specifies the green component of … [See Man Page]'
complete -c xgamma -o bgamma --description 'options, xgamma prints the current gamma correc… [See Man Page]'

