# ximtoppm
# Autogenerated from man page /usr/share/man/man1/ximtoppm.1.gz
# using Deroffing man parser
complete -c ximtoppm -l alphaout --description 'ximtoppm  creates a PGM (portable graymap) file… [See Man Page]'

