# xkbvleds
# Autogenerated from man page /usr/share/man/man1/xkbvleds.1.gz
# using Deroffing man parser
complete -c xkbvleds -o indpy --description 'Mask of LEDs to watch.'
complete -c xkbvleds -o watch --description 'turn on synchronization . PP.'
complete -c xkbvleds -o intersection --description 'Watch only LEDs in all desired sets . PP.'
complete -c xkbvleds -o union --description 'Watch LEDs in any desired sets.'

