# xlsatoms
# Autogenerated from man page /usr/share/man/man1/xlsatoms.1.gz
# using Type1
complete -c xlsatoms -o display --description 'This option specifies the X server to which to connect.'
complete -c xlsatoms -o format --description 'This option specifies a printf-style string use… [See Man Page]'
complete -c xlsatoms -o range --description 'This option specifies the range of atom values to check.'

