# xpmtoppm
# Autogenerated from man page /usr/share/man/man1/xpmtoppm.1.gz
# using Deroffing man parser
complete -c xpmtoppm -l alphaout --description 'xpmtoppm  creates a PBM file containing the tra… [See Man Page]'
complete -c xpmtoppm -l verbose --description 'xpmtoppm prints information about its processin… [See Man Page]'

