# xprop
# Autogenerated from man page /usr/share/man/man1/xprop.1.gz
# using Deroffing man parser
complete -c xprop -o help --description 'Print out a summary of command line options. PP.'
complete -c xprop -o grammar --description 'Print out a detailed grammar for all command line options. PP.'
complete -c xprop -o id --description 'This argument allows the user to select window … [See Man Page]'
complete -c xprop -o name --description 'This argument allows the user to specify that t… [See Man Page]'
complete -c xprop -o font --description 'This argument allows the user to specify that t… [See Man Page]'
complete -c xprop -o root --description 'This argument specifies that X\'s root window is… [See Man Page]'
complete -c xprop -o display --description 'This argument allows you to specify the server … [See Man Page]'
complete -c xprop -o len --description 'Specifies that at most n bytes of any property … [See Man Page]'
complete -c xprop -o notype --description 'Specifies that the type of each property should… [See Man Page]'
complete -c xprop -o fs --description 'Specifies that file file should be used as a so… [See Man Page]'
complete -c xprop -o frame --description 'Specifies that when selecting a window by hand (i. e.'
complete -c xprop -o remove --description 'Specifies the name of a property to be removed … [See Man Page]'
complete -c xprop -o set --description 'Specifies the name of a property and a property… [See Man Page]'
complete -c xprop -o spy --description 'Examine window properties forever, looking for … [See Man Page]'
complete -c xprop -s f --description 'Specifies that the format for name should be fo… [See Man Page]'

