# xscreensaver-command
# Autogenerated from man page /usr/share/man/man1/xscreensaver-command.1.gz
# using Deroffing man parser
complete -c xscreensaver-command -o help --description 'Prints a brief summary of command-line options.'
complete -c xscreensaver-command -o demo --description 'This just launches the  xscreensaver-demo (1) p… [See Man Page]'
complete -c xscreensaver-command -o prefs --description 'Like the no-argument form of -demo, but brings … [See Man Page]'
complete -c xscreensaver-command -o activate --description 'Tell xscreensaver to turn on immediately (that … [See Man Page]'
complete -c xscreensaver-command -o deactivate --description 'This tells xscreensaver to pretend that there h… [See Man Page]'
complete -c xscreensaver-command -o cycle --description 'If the screensaver is active (the screen is bla… [See Man Page]'
complete -c xscreensaver-command -o next --description 'This is like either -activate or -cycle, depend… [See Man Page]'
complete -c xscreensaver-command -o prev --description 'This is like -next, but cycles in the other direction.'
complete -c xscreensaver-command -o select --description 'Like -activate, but runs the Nth element in the list of hacks.'
complete -c xscreensaver-command -o exit --description 'Causes the xscreensaver process to exit gracefully.'
complete -c xscreensaver-command -o lock --description 'Tells the running xscreensaver process to lock … [See Man Page]'
complete -c xscreensaver-command -o version --description 'Prints the version of xscreensaver that is curr… [See Man Page]'
complete -c xscreensaver-command -o time --description 'Prints the time at which the screensaver last a… [See Man Page]'
complete -c xscreensaver-command -o restart --description 'Causes the screensaver process to exit and then… [See Man Page]'
complete -c xscreensaver-command -o watch --description 'Prints a line each time the screensaver changes… [See Man Page]'

