# xscreensaver
# Autogenerated from man page /usr/share/man/man1/xscreensaver.1.gz
# using Deroffing man parser
complete -c xscreensaver -o display --description 'The X display to use.'
complete -c xscreensaver -o verbose --description 'Same as setting the verbose resource to true: p… [See Man Page]'
complete -c xscreensaver -o no-capture-stderr --description 'Do not redirect the stdout and stderr streams t… [See Man Page]'
complete -c xscreensaver -o log --description 'This is exactly the same as redirecting stdout … [See Man Page]'

