# xscreensaver-text
# Autogenerated from man page /usr/share/man/man1/xscreensaver-text.1.gz
# using Deroffing man parser
complete -c xscreensaver-text -l columns -l cols --description 'Where to wrap lines; default 72 columns.'
complete -c xscreensaver-text -l verbose -s v --description 'Print diagnostics to stderr.'
complete -c xscreensaver-text -l string --description 'Print the given string.'
complete -c xscreensaver-text -l file --description 'Print the contents of the given file.'
complete -c xscreensaver-text -l program --description 'Run the given program and print its output.'
complete -c xscreensaver-text -l url --description 'Download and print the contents of the HTTP document.'

