# xwininfo
# Autogenerated from man page /usr/share/man/man1/xwininfo.1.gz
# using Deroffing man parser
complete -c xwininfo -o help --description 'Print out the `Usage:\' command syntax summary. PP.'
complete -c xwininfo -o id --description 'This option allows the user to specify a target… [See Man Page]'
complete -c xwininfo -o name --description 'This option allows the user to specify that the… [See Man Page]'
complete -c xwininfo -o root --description 'This option specifies that X\'s root window is t… [See Man Page]'
complete -c xwininfo -o int --description 'This option specifies that all X window ids sho… [See Man Page]'
complete -c xwininfo -o children --description 'This option causes the root, parent, and childr… [See Man Page]'
complete -c xwininfo -o tree --description 'This option is like -children but displays all … [See Man Page]'
complete -c xwininfo -o stats --description 'This option causes the display of various attri… [See Man Page]'
complete -c xwininfo -o bits --description 'This option causes the display of various attri… [See Man Page]'
complete -c xwininfo -o events --description 'This option causes the selected window\'s event … [See Man Page]'
complete -c xwininfo -o size --description 'This option causes the selected window\'s sizing… [See Man Page]'
complete -c xwininfo -o wm --description 'This option causes the selected window\'s window… [See Man Page]'
complete -c xwininfo -o shape --description 'This option causes the selected window\'s window… [See Man Page]'
complete -c xwininfo -o frame --description 'This option causes window manager frames to be … [See Man Page]'
complete -c xwininfo -o metric --description 'This option causes all individual height, width… [See Man Page]'
complete -c xwininfo -o english --description 'This option causes all individual height, width… [See Man Page]'
complete -c xwininfo -o all --description 'This option is a quick way to ask for all information possible.'
complete -c xwininfo -o display --description 'This option allows you to specify the server to… [See Man Page]'

