# xwud
# Autogenerated from man page /usr/share/man/man1/xwud.1.gz
# using Deroffing man parser
complete -c xwud -o bg --description 'If a bitmap image (or a single plane of an imag… [See Man Page]'
complete -c xwud -o display --description 'This option allows you to specify the server to… [See Man Page]'
complete -c xwud -o dumpheader --description 'This option prints out the XWD header information only.'
complete -c xwud -o fg --description 'If a bitmap image (or a single plane of an imag… [See Man Page]'
complete -c xwud -o geometry --description 'This option allows you to specify the size and … [See Man Page]'
complete -c xwud -o help --description 'Print out a short description of the allowable options. PP.'
complete -c xwud -o in --description 'This option allows the user to explicitly speci… [See Man Page]'
complete -c xwud -o new --description 'This option forces creation of a new colormap f… [See Man Page]'
complete -c xwud -o noclick --description 'Clicking any button in the window will terminat… [See Man Page]'
complete -c xwud -o plane --description 'You can select a single bit plane of the image … [See Man Page]'
complete -c xwud -o raw --description 'This option forces the image to be displayed wi… [See Man Page]'
complete -c xwud -o rv --description 'If a bitmap image (or a single plane of an imag… [See Man Page]'
complete -c xwud -o scale --description 'Allow the window to be resized, and scale the i… [See Man Page]'
complete -c xwud -o std --description 'This option causes the image to be displayed us… [See Man Page]'
complete -c xwud -o vis --description 'This option allows you to specify a particular … [See Man Page]'

