# zeisstopnm
# Autogenerated from man page /usr/share/man/man1/zeisstopnm.1.gz
# using Deroffing man parser
complete -c zeisstopnm -o pgm --description 'Force the output to be a  pgm file.'
complete -c zeisstopnm -o ppm --description 'Force the output to be a ppm file.'

