# zic
# Autogenerated from man page /usr/share/man/man8/zic.8.gz
# using Deroffing man parser
complete -c zic -s d --description 'Create time conversion information files in the… [See Man Page]'
complete -c zic -s l --description 'Use the given time zone as local time.'
complete -c zic -s p --description 'Use the given time zone\'s rules when handling P… [See Man Page]'
complete -c zic -s L --description 'Read leap second information from the file with the given name.'
complete -c zic -s v --description 'Complain if a year that appears in a data file … [See Man Page]'
complete -c zic -s s --description 'Limit time values stored in output files to val… [See Man Page]'
complete -c zic -s y --description 'Use the given  command rather than  yearistype … [See Man Page]'

