# zjsdecode
# Autogenerated from man page /usr/share/man/man1/zjsdecode.1.gz
# using Deroffing man parser
complete -c zjsdecode -s d --description 'Basename of . pbm file for saving decompressed planes.'
complete -c zjsdecode -s r --description 'Basename of . jbg file for saving raw planes.'
complete -c zjsdecode -s h --description 'Print hex file offsets.'
complete -c zjsdecode -s o --description 'Print file offsets.'
complete -c zjsdecode -s p --description 'Don\'t do 4 byte padding.'
complete -c zjsdecode -s D --description 'Set Debug level [0].'

